/**
 * DEMO PRESENTATION ACCOUNTS
 * Strictly separated from real-world entities per Section 13 & 14.
 * Clearly labeled as [Demo Account] for platform evaluation and automated test walkthroughs.
 * All demo passwords are set to "Password123!" for seamless developer/evaluator login.
 */

export const demoAccounts = [
  // 1. ADMIN DEMO ACCOUNT
  {
    email: 'admin@startupz.com',
    role: 'ADMIN',
    isAdmin: true,
    isVerified: true,
    verificationBadge: 'Platform Admin',
    profile: {
      fullName: 'Platform Admin [Demo Account]',
      headline: 'StartupZ System Administrator [Demo Account]',
      location: 'Bengaluru / San Francisco',
      bio: '[DEMO ACCOUNT] Demonstrating administrator capabilities, ecosystem moderation, verified badge issuance, and system metrics.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      education: 'Computer Science & Systems Architecture',
      skills: 'Platform Moderation, System Administration, Database Auditing, Ecosystem Stewardship',
      startupInterests: 'Ecosystem Infrastructure, AI, Open Data',
      industries: 'Platform Engineering, Venture Ecosystems',
      preferredRole: 'Platform Administrator',
      availability: 'Full-time',
      startupExperience: 'System Administrator',
      achievements: 'Maintains verified real data pipelines across the StartupZ network.',
      openTo: 'Platform Governance',
      profileCompletion: 100,
    },
  },

  // 2. FOUNDER DEMO ACCOUNTS
  {
    email: 'sarah.chen@aiagri.io',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Sarah Chen [Demo Account]',
      headline: 'Founder @ AgroPulse [Demo Account] | Precision Agriculture',
      location: 'Austin, TX, USA',
      bio: '[DEMO ACCOUNT] Demonstrating founder workflow: discovering real problems, applying for SISFS & YC grants, publishing co-founder roles, and submitting proposals.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      education: 'Agricultural Bioengineering',
      skills: 'Product Management, AgTech, Precision Agriculture, Prototyping',
      startupInterests: 'AgriTech, ClimateTech, Satellite Sensing',
      industries: 'AgriTech, AI',
      preferredRole: 'CEO / Founder',
      availability: 'Full-time',
      startupExperience: 'Founder',
      achievements: 'Validating solar-powered cold storage and sensor telemetry models.',
      openTo: 'Co-Founder,Investment,Mentorship',
      profileCompletion: 100,
    },
  },
  {
    email: 'demo.founder@startupz.com',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Alex Rivera [Demo Account]',
      headline: 'Early-Stage Climate Founder [Demo Account] | Building Decarbonization Tools',
      location: 'Bengaluru, India',
      bio: '[DEMO ACCOUNT] Founder profile for testing startup creation, co-founder discovery, and problem solution proposal workflows.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      education: 'IIT Madras (B.Tech Mechanical)',
      skills: 'Hardware Engineering, CleanTech, Battery Systems, Embedded Firmware',
      startupInterests: 'CleanTech, Energy Storage, Circular Economy',
      industries: 'CleanTech, Robotics',
      preferredRole: 'Technical Co-Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Developed low-cost smart water audit sensor prototype.',
      openTo: 'Co-Founder,Mentorship,Grants',
      profileCompletion: 95,
    },
  },

  // 3. DEVELOPER / BUILDER DEMO ACCOUNT
  {
    email: 'marcus.dev@codeflow.dev',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Marcus Brody [Demo Account]',
      headline: 'Senior Full-Stack & ML Systems Builder [Demo Account]',
      location: 'Berlin, Germany / Remote',
      bio: '[DEMO ACCOUNT] Demonstrating candidate workflow: browsing real startup opportunities, submitting applications to DeHaat and Ninjacart, and joining co-founder matchmaking.',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      education: 'TU Munich (M.Sc Computer Science)',
      skills: 'TypeScript, React, Node.js, Python, PyTorch, Docker, PostgreSQL',
      startupInterests: 'AI, B2B SaaS, Developer Tools',
      industries: 'Technology & Innovation, Artificial Intelligence',
      preferredRole: 'Lead Full-Stack Engineer / Founding Engineer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      achievements: 'Engineered high-throughput event queues processing 50M daily events.',
      openTo: 'Startup Team,Co-Founder',
      profileCompletion: 90,
    },
  },

  // 4. INVESTOR DEMO ACCOUNT
  {
    email: 'elena.investor@apexventures.vc',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Elena Rostova [Demo Account]',
      headline: 'Partner @ Apex VC [Demo Account] | Seed & Series A Lead',
      location: 'London & San Francisco',
      bio: '[DEMO ACCOUNT] Demonstrating investor workflow: searching real startups by stage and sector, reviewing documented problem market sizes, and reviewing traction.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      education: 'London School of Economics (BSc), Oxford (MBA)',
      skills: 'Venture Capital, Deal Structuring, Cap Table Math, SaaS Metrics, Board Advisory',
      startupInterests: 'AI, FinTech, Enterprise Software, ClimateTech',
      industries: 'Venture Capital, Artificial Intelligence, FinTech',
      preferredRole: 'Board Director / Lead Investor',
      availability: 'Board Advisory',
      startupExperience: 'Venture Capitalist',
      achievements: 'Led 14 early-stage seed checks with 4 portfolio company exits.',
      openTo: 'Investment,Board Advisory',
      profileCompletion: 95,
    },
  },
  {
    email: 'demo.investor@startupz.com',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Ecosystem Capital [Demo Account]',
      headline: 'Venture Scout [Demo Account] | Early Check Syndicate',
      location: 'Bengaluru, India',
      bio: '[DEMO ACCOUNT] Scout account for reviewing verified startups addressing documented national problems.',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80',
      education: 'IIM Ahmedabad (PGP)',
      skills: 'Seed Syndication, Financial Due Diligence, Market Sizing',
      startupInterests: 'AgriTech, DeepTech, FinTech',
      industries: 'Venture Capital',
      preferredRole: 'Angel / Seed Investor',
      availability: 'Part-time',
      startupExperience: 'Angel Investor',
      achievements: 'Active participant in India Angel Network syndicates.',
      openTo: 'Investment',
      profileCompletion: 90,
    },
  },

  // 5. MENTOR DEMO ACCOUNT
  {
    email: 'dr.aravind@healthventures.in',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Dr. Aravind Raman [Demo Account]',
      headline: 'Senior Clinical Advisor [Demo Account] | HealthTech Incubation',
      location: 'Bengaluru, Karnataka, India',
      bio: '[DEMO ACCOUNT] Demonstrating mentor workflow: receiving founder advisory requests, reviewing pitch decks, and booking 1:1 video meetings.',
      avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
      education: 'AIIMS New Delhi (MBBS, MD), Harvard T.H. Chan (MPH)',
      skills: 'Clinical Trials, CDSCO & FDA Regulations, Digital Health, Hospital Pilot Procurement',
      startupInterests: 'HealthTech, MedTech, Diagnostic AI',
      industries: 'Healthcare, Life Sciences',
      preferredRole: 'Medical & Regulatory Advisor',
      availability: '2-4 hrs/month',
      startupExperience: 'Advisor to 8 HealthTech Startups',
      achievements: 'Guided 5 medical device startups through ISO 13485 and CDSCO regulatory clearance.',
      openTo: 'Mentorship,Advisory',
      profileCompletion: 95,
    },
  },
  {
    email: 'demo.mentor@startupz.com',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Ecosystem Advisor [Demo Account]',
      headline: 'Startup Mentor & GTM Strategist [Demo Account]',
      location: 'Mumbai, India',
      bio: '[DEMO ACCOUNT] Mentor account for simulating 1:1 founder advisory sessions and video meetings.',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
      education: 'IIT Bombay & ISB',
      skills: 'Enterprise B2B GTM, Pricing Strategy, Hiring Key Engineers',
      startupInterests: 'B2B SaaS, CleanTech, AgriTech',
      industries: 'Technology & Innovation',
      preferredRole: 'Ecosystem Advisor',
      availability: '4 hrs/month',
      startupExperience: 'Ex-Founder & VP Sales',
      achievements: 'Mentored 20+ founders through accelerator cohorts.',
      openTo: 'Mentorship',
      profileCompletion: 90,
    },
  },

  // 6. MARKETER DEMO ACCOUNTS
  {
    email: 'priya.growth@marketscale.io',
    role: 'MARKETER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Priya Sharma [Demo Account]',
      headline: 'Growth & Product Marketing Lead [Demo Account] | Scaling B2B SaaS',
      location: 'Bengaluru, Karnataka, India',
      bio: '[DEMO ACCOUNT] Growth marketing leader specializing in PLG loops, early demand generation, content attribution, and performance customer acquisition for startups.',
      avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80',
      education: 'MICA Ahmedabad (PGDM Communications)',
      skills: 'Growth Marketing, Performance Advertising, SEO, Content Strategy, B2B Funnel Optimization, Brand Positioning',
      startupInterests: 'B2B SaaS, AgriTech, FinTech, Consumer Tech',
      industries: 'Technology & Innovation, Marketing & Growth',
      preferredRole: 'Marketing Co-Founder / Head of Growth',
      availability: 'Full-time',
      startupExperience: 'Scaled 2 early-stage startups from 0 to 100k MAU',
      achievements: 'Generated $1.5M in ARR pipeline through inbound organic acquisition loops.',
      openTo: 'Co-Founder,Startup Team',
      profileCompletion: 95,
    },
  },

  // 7. CO-FOUNDER DEMO ACCOUNT
  {
    email: 'david.kim@hyperbuild.co',
    role: 'COFOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'David Kim [Demo Account]',
      headline: 'Technical Co-Founder [Demo Account] | Distributed Cloud & AI Infrastructure',
      location: 'Singapore / Remote',
      bio: '[DEMO ACCOUNT] Full-stack systems engineer seeking a business or domain-expert co-founder to tackle complex logistics and climate infrastructure challenges.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      education: 'National University of Singapore (B.Comp)',
      skills: 'Go, Rust, TypeScript, React, Distributed Systems, Kubernetes, Kafka, Cloud Architecture',
      startupInterests: 'Developer Infrastructure, AI Systems, CleanTech',
      industries: 'Technology & Innovation, Artificial Intelligence',
      preferredRole: 'Technical Co-Founder / CTO',
      availability: 'Full-time',
      startupExperience: 'Ex-Founding Engineer at seed-stage logistics startup',
      achievements: 'Architected distributed event messaging layer serving 10M daily events.',
      openTo: 'Co-Founder',
      profileCompletion: 95,
    },
  },

  // 8. OTHER / DESIGNER DEMO ACCOUNT
  {
    email: 'maya.design@pixelcraft.studio',
    role: 'DESIGNER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Maya Patel [Demo Account]',
      headline: 'Founding Product Designer [Demo Account] | Design Systems & Complex UX',
      location: 'Mumbai, Maharashtra, India',
      bio: '[DEMO ACCOUNT] Product designer crafting intuitive design systems, web dashboards, and mobile user experiences for early-stage startups.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'National Institute of Design (NID Ahmedabad)',
      skills: 'Figma, UI/UX Design, Design Systems, User Research, Interactive Prototyping, Mobile UX',
      startupInterests: 'HealthTech, FinTech, B2B SaaS',
      industries: 'Design & Creative, Technology',
      preferredRole: 'Founding Designer / Design Co-Founder',
      availability: 'Full-time',
      startupExperience: 'Designed flagship mobile app for leading FinTech startup',
      achievements: 'Redesigned core checkout funnel boosting conversion by 28%.',
      openTo: 'Startup Team,Co-Founder',
      profileCompletion: 90,
    },
  },
];
