/**
 * REAL USER SEED CONFIGURATION
 * Real users and ecosystem profiles without demo labels.
 */

export const demoAccounts = [
  {
    email: 'ruthwikpatel08@gmail.com',
    role: 'FOUNDER',
    isAdmin: true,
    isVerified: true,
    verificationBadge: 'HookZ Founder',
    profile: {
      fullName: 'Ruthwik Patel',
      username: 'ruthwikpatel08',
      headline: 'Founder & Lead Architect | HookZ',
      location: 'Bengaluru / Hyderabad, India',
      bio: 'Leading HookZ to connect builders, co-founders, and investors worldwide. Architecting student and startup networking ecosystems.',
      avatar: '/images/founders/ruthwik-patel.png',
      education: 'Computer Science & Software Systems',
      skills: 'Full-Stack Architecture, Product Strategy, Startup Scaling, AI Systems',
      startupInterests: 'Ecosystem Infrastructure, AI, Open Data',
      industries: 'Technology & Innovation, Artificial Intelligence',
      preferredRole: 'Founder',
      availability: 'Full-time',
      startupExperience: 'Founder',
      achievements: 'Architected HookZ network platform.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 100,
    },
  },
  {
    email: 'gokulvamshi@hookz.in',
    role: 'FOUNDER',
    isAdmin: true,
    isVerified: true,
    verificationBadge: 'HookZ Co-Founder',
    profile: {
      fullName: 'Gokul Vamshi',
      username: 'gokulvamshi',
      headline: 'Co-Founder | HookZ',
      location: 'Telangana / Hyderabad, India',
      bio: 'Co-Founder at HookZ. Building startup partnerships, student community initiatives, and collaborative venture infrastructure.',
      avatar: '/images/founders/gokul-vamshi.jpg',
      education: 'Business Operations & Venture Growth',
      skills: 'Operations, Strategic Partnerships, Venture Building, Community Growth, Product Operations',
      startupInterests: 'Student Communities, Venture Incubation, Product Growth',
      industries: 'Technology & Innovation, Community Platforms',
      preferredRole: 'Co-Founder',
      availability: 'Full-time',
      startupExperience: 'Co-Founder',
      achievements: 'Co-founded HookZ startup platform.',
      openTo: 'Co-Founder,Startup Team,Mentorship,Partnerships',
      profileCompletion: 100,
    },
  },
  {
    email: 'legacyplayer04@gmail.com',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified via Google',
    profile: {
      fullName: 'Legacy',
      headline: 'Founder | Startup Builder & Co-Founder Network',
      location: 'Global / Remote',
      bio: 'Building next-generation ventures on StartupZ.',
      avatar: 'https://lh3.googleusercontent.com/a/ACg8ocIBc2tvgpVoh9lUYtp3FBYhmXWQqnl0Kgi2vmdN2vm_TDwgtw=s96-c',
      education: 'Computer Science & Entrepreneurship',
      skills: 'Startup Strategy, Product Execution, Early Growth',
      startupInterests: 'AI, B2B SaaS, Modern Tech',
      industries: 'Technology & Innovation',
      preferredRole: 'Founder',
      availability: 'Full-time',
      startupExperience: 'Founder',
      achievements: 'Early ecosystem member.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'lavanyadav0206@gmail.com',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'lavan yadav',
      headline: 'Angel Investor & Ecosystem Backer',
      location: 'Telangana, India',
      bio: 'Early-stage investor focused on high-growth technology startups.',
      avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=lavan%20yadav&backgroundColor=4f46e5,06b6d4,10b981',
      education: 'Business & Finance',
      skills: 'Angel Investing, Seed Capital, Deal Flow, Scaling',
      startupInterests: 'Tech, AgriTech, CleanTech',
      industries: 'Venture Capital, Technology',
      preferredRole: 'Investor',
      availability: 'Flexible',
      startupExperience: 'Investor',
      achievements: 'Angel backer of early stage ventures.',
      openTo: 'Investment,Advisory,Co-Founder',
      profileCompletion: 85,
    },
  },
];
