/**
 * REAL-WORLD DOCUMENTED FAILED STARTUPS (STARTUP POST-MORTEMS)
 * All cases are publicly documented historical startup failures with verifiable post-mortems,
 * SEC filings, investigative reporting, or official liquidation records.
 */

export const realFailedStartups = [
  {
    name: 'Theranos',
    industry: 'HealthTech & Blood Diagnostics',
    peakFunding: '$700M+ Raised (Valued at $9B)',
    yearsActive: '2003 – 2018',
    logo: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=200&auto=format&fit=crop&q=80',
    summary: 'Claimed to revolutionize blood testing by performing hundreds of clinical diagnostic assays from just a few drops of capillary blood drawn via fingerstick into a proprietary "Edison" analyzer.',
    whyItFailed: 'The core microfluidic hardware was scientifically unviable for high-throughput multi-analyte assays; capillary fingerstick blood hemolyzed and was unreliable for quantitative clinical testing. Leadership concealed the flaws by secretly running patient blood samples on diluted commercial Siemens machines, falsifying quality control data, and defrauding investors and patients (FDA inspection and SEC investigations in 2015-2018).',
    unsolvedProblem: 'Point-of-care, low-volume, rapid clinical blood testing remains deeply needed in rural and resource-limited clinics where venipuncture phlebotomists and central pathology labs do not exist.',
    lessonsLearned: '1) Healthcare and life sciences startups require transparent peer-reviewed clinical validation, not "fake it till you make it" Silicon Valley culture; 2) Governance matters—boards must include independent medical and scientific domain experts; 3) Regulatory compliance with CLIA and FDA is non-negotiable for patient safety.',
    solutions: [
      {
        authorEmail: 'demo.founder@startupz.com',
        title: 'Decentralized Microfluidic Immunoassays with Peer-Reviewed Open Validation',
        description: 'Instead of attempting 200 tests in a single black box, engineer narrow, focused point-of-care microfluidic cartridges for single biomarker targets (e.g. troponin for cardiac arrest, HbA1c for diabetes) backed by open multi-center hospital clinical trials.',
        targetAudience: 'Primary care clinics, emergency departments, and rural diagnostic outposts',
        differentiation: 'Single-analyte focus guarantees high sensitivity and specificity; published clinical trial datasets build medical trust.',
        upvotesCount: 42,
      },
    ],
  },
  {
    name: 'WeWork (Pre-Bankruptcy & IPO Collapse)',
    industry: 'Real Estate Tech & Co-Working',
    peakFunding: '$12B+ Raised (Valued at $47B at Peak)',
    yearsActive: '2010 – 2023 (Chapter 11 Reorganization)',
    logo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=200&auto=format&fit=crop&q=80',
    summary: 'Global flexible workspace provider taking long-term master commercial office leases and subletting furnished workspace to startups, freelancers, and enterprises on flexible short-term terms.',
    whyItFailed: 'Severe asset-liability maturity mismatch: WeWork committed to $47 billion in fixed, long-term 10-to-15 year commercial lease obligations while collecting short-term, cancellable month-to-month memberships. Unsustainable capital expenditure on lavish buildouts, rapid geographic expansion without local unit profitability, corporate governance self-dealing, and massive cash burn caused the 2019 IPO attempt to collapse and eventual 2023 Chapter 11 bankruptcy.',
    unsolvedProblem: 'Companies and modern remote/hybrid workforces still require high-quality, flexible, collaborative office space without signing 10-year commercial leases.',
    lessonsLearned: '1) Asset-heavy real estate arbitrage cannot be valued like a pure software company; 2) Management agreements and revenue-share models with property owners are vastly superior to signing direct long-term lease liabilities; 3) Sustainable unit economics in core markets must precede hyper-expansion.',
    solutions: [
      {
        authorEmail: 'demo.founder@startupz.com',
        title: 'Asset-Light Hospitality Management Model for Commercial Real Estate',
        description: 'Operate flexible workspaces strictly via performance-fee management contracts with commercial landlords—similar to the hotel industry (e.g. Marriott)—eliminating fixed master lease liabilities entirely.',
        targetAudience: 'Commercial building landlords and distributed enterprise teams',
        differentiation: 'Zero lease liability on the operator’s balance sheet; revenue is shared directly with property owners.',
        upvotesCount: 38,
      },
    ],
  },
  {
    name: 'Better Place',
    industry: 'CleanTech & Electric Vehicle Infrastructure',
    peakFunding: '$850M Raised',
    yearsActive: '2007 – 2013',
    logo: 'https://images.unsplash.com/photo-1558441719-81ceb768a356?w=200&auto=format&fit=crop&q=80',
    summary: 'Pioneered an automated robotic battery-swapping network for electric passenger vehicles across Israel and Denmark, aiming to eliminate EV range anxiety.',
    whyItFailed: 'Automated mechanical battery-swapping stations cost over $2 million each to build. More critically, Better Place failed to convince global automotive OEMs to standardize battery physical dimensions and electrical connectors—only Renault manufactured compatible vehicles (Fluence Z.E.). Low vehicle adoption produced negligible station utilization, leading to liquidation.',
    unsolvedProblem: 'Fleet commercial vehicles (auto-rickshaws, commercial two-wheelers, urban delivery vans) suffer severe revenue downtime when waiting for slow battery charging.',
    lessonsLearned: '1) Heavy infrastructure networks requiring cross-industry hardware standardization are vulnerable if major OEMs refuse to participate; 2) Battery swapping succeeds in closed, standardized commercial fleets (two-wheelers and commercial taxis) rather than heterogeneous consumer passenger sedans; 3) Fast-charging standards (CCS/NACS) advanced faster than mechanical battery swap economics.',
    solutions: [
      {
        authorEmail: 'demo.founder@startupz.com',
        title: 'Standardized Swapping for Commercial 2-Wheeler and 3-Wheeler Fleets',
        description: 'Deploy low-cost modular battery swapping cabinets exclusively for standardized commercial electric delivery fleets (e.g. Yulu, Sun Mobility) where battery packs weigh under 12 kg and require no multimillion-dollar hydraulic robotics.',
        targetAudience: 'Gig delivery workers, last-mile e-commerce fleets, urban transit authorities',
        differentiation: 'Low Capex per cabinet, human-swappable lightweight batteries, and high guaranteed daily fleet utilization.',
        upvotesCount: 31,
      },
    ],
  },
  {
    name: 'Solyndra',
    industry: 'CleanTech & Photovoltaic Manufacturing',
    peakFunding: '$1.1B Venture + $535M US Dept of Energy Loan Guarantee',
    yearsActive: '2005 – 2011',
    logo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=200&auto=format&fit=crop&q=80',
    summary: 'Manufactured proprietary cylindrical thin-film solar panels using Copper Indium Gallium Selenide (CIGS) designed for commercial flat rooftop installations without mechanical tracking.',
    whyItFailed: 'Solyndra was founded when conventional polysilicon prices were at an all-time high ($400/kg). Within a few years, massive Chinese silicon manufacturing capacity came online, causing polysilicon prices to plunge 80% to under $50/kg. Solyndra’s specialized cylindrical manufacturing equipment was capital-intensive and could not compete with the plunging cost of standard crystalline silicon solar panels, leading to bankruptcy.',
    unsolvedProblem: 'Commercial flat rooftops often have load-bearing weight limitations that prevent installation of heavy traditional glass-and-metal solar arrays.',
    lessonsLearned: '1) Never base an entire capital-intensive hardware business model on an assumed commodity supply crunch; 2) Technological differentiation must withstand relentless cost reductions from standard commodity manufacturing scale; 3) Capex efficiency is paramount in renewable energy hardware.',
    solutions: [
      {
        authorEmail: 'demo.founder@startupz.com',
        title: 'Ultra-Lightweight Flexible Perovskite-Silicon Tandem Films',
        description: 'Manufacture roll-to-roll lightweight flexible solar skins that paste onto industrial factory roofs using existing adhesive laminators without heavy racking hardware.',
        targetAudience: 'Warehouse owners, commercial logistics hubs, lightweight steel industrial sheds',
        differentiation: '90% lighter than glass panels, compatible with standard silicon tandem efficiencies.',
        upvotesCount: 26,
      },
    ],
  },
  {
    name: 'Quibi',
    industry: 'Consumer Media & Streaming Video',
    peakFunding: '$1.75B Raised',
    yearsActive: '2018 – 2020',
    logo: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=200&auto=format&fit=crop&q=80',
    summary: 'Short-form, high-budget Hollywood episodic streaming service designed exclusively for mobile phones, featuring episodes under 10 minutes ("quick bites") with proprietary Turnstyle vertical-horizontal viewing tech.',
    whyItFailed: 'Quibi spent upwards of $100,000 per minute on Hollywood content but failed to offer viral sharing, screenshots, or meme generation on social media due to strict DRM. Launching in early 2020 right when COVID-19 lockdowns kept commuters at home (competing with TikTok, YouTube, and big-screen TV services like Netflix) destroyed its core "mobile on-the-go" value proposition. Shut down after just 6 months.',
    unsolvedProblem: 'Mobile-first storytelling requires engaging interactive content, but top creators struggle to monetize episodic short fiction outside ad-supported algorithmic feeds.',
    lessonsLearned: '1) Consumer content platforms must embrace virality, social sharing, and community engagement rather than locking content behind rigid DRM; 2) High production budget cannot substitute for organic product-market fit; 3) Understand user habits—mobile users consume short-form video in an interactive social context, not paid linear Hollywood prestige format.',
    solutions: [
      {
        authorEmail: 'demo.founder@startupz.com',
        title: 'Interactive Community Micro-Dramas with Direct Creator Monetization',
        description: 'Platform for serialized 1-minute episodic micro-dramas (ReelShort / DramaBox model) where users unlock cliffhanger episodes via micro-transactions or community engagement, with full TikTok/Reels clip syndication.',
        targetAudience: 'Mobile episodic entertainment viewers and indie screenwriters',
        differentiation: 'Direct pay-per-episode micro-transactions, organic viral social distribution, low-budget high-engagement storytelling.',
        upvotesCount: 29,
      },
    ],
  },
  {
    name: 'Fast (Fast.co)',
    industry: 'FinTech & One-Click Checkout',
    peakFunding: '$124M Raised (Series B Backed by Stripe)',
    yearsActive: '2019 – 2022',
    logo: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?w=200&auto=format&fit=crop&q=80',
    summary: 'One-click headless checkout button for e-commerce websites, designed to eliminate login passwords and cart abandonment across independent online merchants.',
    whyItFailed: 'Extravagant cash burn of over $10 million per month on NASCAR sponsorships, aggressive executive hiring, and marketing stunts, while generating only approximately $600,000 in total revenue in 2021. Most major e-commerce merchants already used Shopify Shop Pay, Apple Pay, or PayPal, making Fast’s standalone button redundant with high integration friction. Shut down abruptly when Series C funding collapsed.',
    unsolvedProblem: 'Independent headless e-commerce stores still experience cart friction, particularly on complex multi-step mobile checkouts.',
    lessonsLearned: '1) Revenue and unit economics must justify your cash burn rate; 2) Vanity marketing cannot compensate for lack of distribution leverage; 3) Competing directly with platform defaults (Shop Pay, Apple Pay) without a proprietary merchant wedge is fatal in FinTech.',
    solutions: [
      {
        authorEmail: 'demo.founder@startupz.com',
        title: 'Post-Purchase Upsell and Identity Vault for Independent Merchants',
        description: 'Instead of fighting to replace the checkout button, provide a post-purchase one-click upsell and unified return/loyalty portal that integrates seamlessly with existing payment gateways without replacing Shopify or Stripe checkout.',
        targetAudience: 'D2C brand stores and independent omnichannel retailers',
        differentiation: 'Boosts average order value (AOV) by 15% post-purchase with zero checkout integration friction.',
        upvotesCount: 35,
      },
    ],
  },
  {
    name: 'Zume Pizza',
    industry: 'FoodTech & Automation',
    peakFunding: '$445M Raised (SoftBank Vision Fund Backed at $2B Valuation)',
    yearsActive: '2015 – 2023',
    logo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=200&auto=format&fit=crop&q=80',
    summary: 'Attempted to disrupt the pizza industry by using industrial robotic arms to sauce and bake artisan pizzas inside delivery trucks while driving to customers ("baked en route").',
    whyItFailed: 'Massive engineering complexity and high maintenance overhead: automated ovens and robotic arms mounted inside delivery trucks frequently broke down from vehicle vibrations and road potholes. Melting cheese spilled during vehicle cornering, and trucks were prohibitively expensive to build and insure compared to simple neighborhood pizza parlors. Later pivoted to compostable packaging before shutting down in 2023.',
    unsolvedProblem: 'Commercial restaurant kitchens suffer acute kitchen labor shortages and high ingredient wastage during peak dining hours.',
    lessonsLearned: '1) Applying advanced robotics to an inherently simple, solved consumer process (cooking a pizza) introduces massive failure points without improving consumer willingness to pay; 2) Keep robotics stationary in controlled commissary environments rather than moving vehicles; 3) Automation must reduce operational costs, not multiply maintenance complexity.',
    solutions: [
      {
        authorEmail: 'demo.founder@startupz.com',
        title: 'Stationary Robotic Automated Kiosks for High-Footfall Transit Hubs',
        description: 'Deploy compact, stationary 50-sq-ft robotic pizza and bowl assembly kiosks in airports, universities, and hospitals where 24/7 labor is difficult to staff, operating in stationary cleanrooms without vehicular stress.',
        targetAudience: 'Airport terminals, hospital cafeterias, university student unions',
        differentiation: 'Stationary architecture eliminates vibration wear, operating 24/7 with zero delivery truck overhead.',
        upvotesCount: 33,
      },
    ],
  },
  {
    name: 'Katerra',
    industry: 'ConstructionTech & Off-Site Prefabrication',
    peakFunding: '$2B+ Raised (SoftBank Vision Fund Backed)',
    yearsActive: '2015 – 2021',
    logo: 'https://images.unsplash.com/photo-1541888946425-d0fbb1861564?w=200&auto=format&fit=crop&q=80',
    summary: 'Vertically integrated construction tech company aiming to revolutionize building construction through off-site prefabrication, cross-laminated timber (CLT) factories, and end-to-end architecture and general contracting software.',
    whyItFailed: 'Katerra attempted to vertically integrate design, material manufacturing, prefabrication, and on-site general contracting all at once across dozens of simultaneous complex construction projects. Factory overhead was exorbitant, standardized panels encountered unpredictable local municipal building code conflicts across different jurisdictions, project delays caused severe cash flow deficits, and accounting irregularities led to Chapter 11 bankruptcy in 2021.',
    unsolvedProblem: 'Global housing shortages and urban construction remain slow, labor-dependent, high-carbon, and prone to 40% budget overruns.',
    lessonsLearned: '1) Construction is fundamentally localized—hyper-vertical integration across regional code jurisdictions introduces catastrophic operational complexity; 2) Software integration cannot paper over on-site subcontractor and permitting realities; 3) Focus on component standardization (e.g. modular bathroom pods) rather than attempting to manufacture entire buildings in a single monolithic factory.',
    solutions: [
      {
        authorEmail: 'demo.founder@startupz.com',
        title: 'Standardized Modular Utility Pods (Bath & Kitchen Cores)',
        description: 'Instead of prefabricating the entire building shell, manufacture plug-and-play standardized MEP (mechanical, electrical, plumbing) bathroom and kitchen pods that ship to any traditional concrete or steel job site, eliminating 70% of on-site trade labor bottlenecks.',
        targetAudience: 'Commercial general contractors, affordable housing developers, hotel developers',
        differentiation: 'Fits standard construction workflows without requiring developers to change their structural engineering or architectural designs.',
        upvotesCount: 40,
      },
    ],
  },
];
