/**
 * REAL-WORLD ECOSYSTEM MENTORSHIP & INCUBATION NETWORKS
 * All programs, organizations, and official websites are verified from official government and academic incubation directories.
 */

export const realMentors = [
  {
    organization: 'Startup India MAARG Portal (Mentorship, Advisory, Assistance, Resilience and Growth)',
    expertise: 'National Startup Advisory, Regulatory Compliance, DPIIT Recognition, Government Schemes',
    industries: 'All Sectors, AgriTech, FinTech, DeepTech, CleanTech, Healthcare',
    yearsExperience: 8,
    availableHours: 'Official Government Portal',
    mentoringTopics: 'DPIIT Recognition, Seed Fund Scheme eligibility, Patent filing subsidies, Public procurement benefits (GeM)',
    about: 'Government of India initiative under DPIIT connecting early-stage startups across all stages with verified industry leaders, successful founders, and regulatory advisors.',
    website: 'https://www.startupindia.gov.in/content/sih/en/maarg.html',
    isVerified: true,
  },
  {
    organization: 'NITI Aayog Atal Innovation Mission (Mentor India)',
    expertise: 'Grassroots Innovation, Prototyping, Youth Entrepreneurship, Tinkering Labs',
    industries: 'Education, CleanTech, Robotics, Rural Tech, Agritech',
    yearsExperience: 7,
    availableHours: 'National Volunteer Network',
    mentoringTopics: 'Atal Incubation Centre (AIC) onboarding, Atal New India Challenge (ANIC) grants, Prototype translation',
    about: 'National mentoring network under NITI Aayog driving innovation across 10,000+ Atal Tinkering Labs and 70+ Atal Incubation Centres nationwide.',
    website: 'https://aim.gov.in/mentor.php',
    isVerified: true,
  },
  {
    organization: 'IIT Madras Incubation Cell (IITMIC)',
    expertise: 'DeepTech Engineering, Hardware Prototyping, Patent Strategy, Faculty Spinouts',
    industries: 'DeepTech, SpaceTech, EV Mobility, Robotics, MedTech',
    yearsExperience: 12,
    availableHours: 'Academic & Industry Panel',
    mentoringTopics: 'Design for Manufacturing, Academic IP licensing, Laboratory testing facilities, Government grant matching',
    about: 'India’s premier deep-tech incubator, having nurtured 350+ technology startups including Ather Energy, Agnikul Cosmos, Solinas, and Detect Technologies.',
    website: 'https://incubation.iitm.ac.in',
    isVerified: true,
  },
  {
    organization: 'SINE IIT Bombay (Society for Innovation and Development)',
    expertise: 'High-Tech Incubation, Scientific Commercialization, Seed Capital Matching',
    industries: 'Information Technology, Clean Energy, Biomedical Devices, Advanced Materials',
    yearsExperience: 20,
    availableHours: 'Senior Faculty & Alum Panel',
    mentoringTopics: 'Proof-of-concept validation, Lab-to-market scaling, Corporate R&D partnerships',
    about: 'Pioneering technology business incubator at IIT Bombay supporting science and engineering spinouts with physical laboratories and seed funding.',
    website: 'https://sineiitb.org',
    isVerified: true,
  },
  {
    organization: 'T-Hub Hyderabad',
    expertise: 'Scale-Up Acceleration, Corporate Open Innovation, International Market Access',
    industries: 'AI, B2B SaaS, HealthTech, Smart Cities, FinTech',
    yearsExperience: 9,
    availableHours: 'Global Mentor Roster',
    mentoringTopics: 'Corporate pilot matchmaking, Enterprise sales cycles, Market entry into GCC and North America',
    about: 'World’s largest innovation campus in Hyderabad, bringing together startups, global corporates, venture capital firms, and government stakeholders.',
    website: 'https://t-hub.co',
    isVerified: true,
  },
  {
    organization: 'NSRCEL IIM Bangalore',
    expertise: 'Business Model Innovation, GTM Strategy, Social Impact Scaling, Women Entrepreneurship',
    industries: 'Social Impact, Consumer Products, EdTech, FinTech, Women-Led Startups',
    yearsExperience: 22,
    availableHours: 'Executive Mentorship Sessions',
    mentoringTopics: 'Unit economics, Customer discovery, Governance hygiene, Scaling through non-profit and hybrid funding',
    about: 'Management and business incubator at IIM Bangalore with specialized tracks for rural, social, and female founders.',
    website: 'https://nsrcel.org',
    isVerified: true,
  },
  {
    organization: 'C-CAMP (Centre for Cellular and Molecular Platforms)',
    expertise: 'Biotech Discovery, Life Sciences Regulatory Approvals, CDSCO & US FDA Validation',
    industries: 'BioTech, HealthTech, Agri-Biotechnology, Diagnostics',
    yearsExperience: 14,
    availableHours: 'Scientific Board & Mentors',
    mentoringTopics: 'BIRAC BIG grant preparation, Pre-clinical trials, Bio-safety compliance, Genomics lab access',
    about: 'Department of Biotechnology (Govt of India) initiative operating state-of-the-art life sciences research platforms and incubation for bio-innovators.',
    website: 'https://ccamp.res.in',
    isVerified: true,
  },
  {
    organization: 'Venture Center NCL Pune',
    expertise: 'Chemical & Materials Science, Scientific Startups, Patent Filing & Prior Art Search',
    industries: 'Materials Science, Polymers, Clean Chemistry, Biomedical',
    yearsExperience: 17,
    availableHours: 'Senior Scientist Mentors',
    mentoringTopics: 'NIDHI-PRAYAS grant applications, Chemical safety protocols, Pilot-scale synthesis reactors',
    about: 'National Award-winning science business incubator located at CSIR-National Chemical Laboratory, hosting high-density scientific testing equipment.',
    website: 'https://www.venturecenter.co.in',
    isVerified: true,
  },
  {
    organization: 'Villgro Innovations Foundation',
    expertise: 'Social Impact Incubation, Rural Distribution, Gender-Inclusive Design',
    industries: 'AgriTech, Climate Action, Affordable Healthcare, Inclusive Livelihoods',
    yearsExperience: 23,
    availableHours: 'Field Advisors & Mentors',
    mentoringTopics: 'Last-mile rural distribution, Impact metric auditing (IRIS+), Catalytic debt financing',
    about: 'India’s oldest social enterprise incubator, supporting impact founders with patient capital, deep field mentoring, and government agency tie-ups.',
    website: 'https://villgro.org',
    isVerified: true,
  },
  {
    organization: 'Nexus Startup Hub (American Center New Delhi & ACIR)',
    expertise: 'US Market Entry, Global Venture Pitching, Commercialization Best Practices',
    industries: 'Software, Technology, Clean Energy, Social Innovation',
    yearsExperience: 7,
    availableHours: 'US & Indian Industry Leaders',
    mentoringTopics: 'US venture pitching, Cross-border corporate partnerships, American accelerator admissions',
    about: 'Collaboration between the US Embassy in India and the Alliance for Commercialization and Innovation Research, training top Indian startups.',
    website: 'https://americancornersindia.org/nexus/',
    isVerified: true,
  },
  {
    organization: 'Y Combinator Startup School',
    expertise: 'Founder Mentorship, Finding Product-Market Fit, Early Traction, Pitch Decks',
    industries: 'All Tech, AI, B2B SaaS, Developer Tools, Marketplaces, Consumer',
    yearsExperience: 18,
    availableHours: 'Global Online Co-founder & Advisory Network',
    mentoringTopics: 'Validating early problem statements, talking to users, building MVP in weeks, YC batch application preparation',
    about: 'Free online program by Y Combinator providing education, peer community, and advice from YC alumni founders to over 100,000 entrepreneurs worldwide.',
    website: 'https://www.startupschool.org',
    isVerified: true,
  },
  {
    organization: 'Techstars Worldwide Mentor Network',
    expertise: 'Mentor-Driven Acceleration, Corporate Engagement, International Fundraising',
    industries: 'FinTech, Web3, CleanTech, Healthcare, Mobility, DeepTech',
    yearsExperience: 17,
    availableHours: 'Dedicated Mentor-Driven Sprints',
    mentoringTopics: 'Mentor madness matching, B2B sales acceleration, Term sheet negotiation, Global investor introductions',
    about: 'Techstars pairs early-stage founders with an international network of over 10,000 vetted mentor operators and industry leaders.',
    website: 'https://www.techstars.com/mentorship',
    isVerified: true,
  },
  {
    organization: 'Google for Startups Accelerator',
    expertise: 'Machine Learning Infrastructure, Cloud Architecture, Android Ecosystem, UX Design',
    industries: 'AI, ClimateTech, HealthTech, FinTech, Women Founders',
    yearsExperience: 10,
    availableHours: 'Google Tech Experts & AI Engineers',
    mentoringTopics: 'TensorFlow/JAX model scaling, Google Cloud credits optimization, Responsible AI frameworks, Global Play Store distribution',
    about: 'Tailored 3-month equity-free program matching growth-stage startups with Google technical and product mentors.',
    website: 'https://startup.google.com/accelerator/',
    isVerified: true,
  },
  {
    organization: 'Microsoft for Startups Founders Hub',
    expertise: 'Enterprise Cloud Scaling, OpenAI API Integration, B2B Co-Selling with Microsoft',
    industries: 'Enterprise Software, Generative AI, CyberSecurity, Developer Tools',
    yearsExperience: 8,
    availableHours: 'Microsoft Solutions Architects & 1:1 Advisory',
    mentoringTopics: 'Azure OpenAI architecture, Pegasus program enterprise co-sell validation, SOC2 compliance roadmap',
    about: 'Digital platform providing up to $150k in Azure credits, OpenAI API tokens, GitHub Enterprise, and 1:1 business mentoring for founders at any stage.',
    website: 'https://www.microsoft.com/startups',
    isVerified: true,
  },
  {
    organization: 'Creative Destruction Lab (CDL)',
    expertise: 'Deep Science Commercialization, Quantum Computing, Climate Technologies',
    industries: 'DeepTech, Quantum, Climate, AI, Space, Advanced Materials',
    yearsExperience: 12,
    availableHours: 'Structured Milestone Sessions with Fellow Operators',
    mentoringTopics: 'Objective-setting reviews with serial entrepreneurs, technology derisking, deep science angel syndication',
    about: 'Non-profit program for seed-stage science- and technology-based companies, operating across 12 universities worldwide (Oxford, Rotman, Wisconsin).',
    website: 'https://creativedestructionlab.com',
    isVerified: true,
  },
  {
    organization: 'MassChallenge Mentorship Network',
    expertise: 'Zero-Equity Acceleration, Corporate Pilot Partnering, Government Innovation',
    industries: 'Digital Health, Sustainable Food, FinTech, Space, Clean Energy',
    yearsExperience: 14,
    availableHours: 'Custom Cohort Matchmaking',
    mentoringTopics: 'Non-dilutive funding, Pilot proof-of-concepts with Fortune 500 partners, International market landing',
    about: 'Global zero-equity accelerator that has supported over 4,000 startups raising over $9B in funding without taking founder equity.',
    website: 'https://masschallenge.org',
    isVerified: true,
  },
  {
    organization: 'StartX (Stanford University Accelerator)',
    expertise: 'Stanford Founder Peer Network, Cross-Industry Advisory, Life Sciences Clinical Pilots',
    industries: 'AI, MedTech, Biotechnology, SaaS, Consumer, FinTech',
    yearsExperience: 14,
    availableHours: 'Stanford Faculty & Alum Mentors',
    mentoringTopics: 'Hospital system procurement, FDA breakthrough device applications, Series A syndication',
    about: 'Educational non-profit accelerator for Stanford University students, faculty, and alumni, representing one of the highest-density founder networks in the world.',
    website: 'https://startx.com',
    isVerified: true,
  },
  {
    organization: 'Berkeley SkyDeck (University of California Berkeley)',
    expertise: 'University DeepTech Spinouts, Silicon Valley Market Entry, Key Executive Hiring',
    industries: 'AI, DeepTech, BioTech, Semiconductors, CleanTech',
    yearsExperience: 12,
    availableHours: 'Faculty Advisors & SkyDeck Key Advisors',
    mentoringTopics: 'US market incorporation, Semiconductor tape-out partners, VC demo day preparation',
    about: 'UC Berkeley’s premier global startup accelerator and dedicated VC fund connecting university research spinouts with Silicon Valley capital.',
    website: 'https://skydeck.berkeley.edu',
    isVerified: true,
  },
  {
    organization: 'CIE IIIT Hyderabad (Centre for Innovation and Entrepreneurship)',
    expertise: 'Deep Computer Vision, Speech AI, Robotics, Academic Research Translation',
    industries: 'DeepTech, AI & Machine Learning, Gaming, Medical Devices',
    yearsExperience: 15,
    availableHours: 'Faculty Researchers & Tech Mentors',
    mentoringTopics: 'Academic IP commercialization, Lab prototyping facilities, MeitY TIDE 2.0 grant applications',
    about: 'One of India\'s largest academic incubators based at IIIT Hyderabad, specialized in translating research labs into deep-tech startups.',
    website: 'https://cie.iiit.ac.in',
    isVerified: true,
  },
  {
    organization: 'BITS Pilani TBI (Technology Business Incubator)',
    expertise: 'Student & Alumni Entrepreneurship, Embedded IoT Hardware, Early Prototyping',
    industries: 'CleanTech, Hardware, EdTech, AgriTech, FinTech',
    yearsExperience: 18,
    availableHours: 'BITS Alumni Angel Network Mentors',
    mentoringTopics: 'Hardware lab prototyping, DST NIDHI seed support, Student founder equity structures',
    about: 'Department of Science & Technology recognized incubator at BITS Pilani fostering high-impact ventures from students and alumni nationwide.',
    website: 'https://www.bits-pilani.ac.in/pilani/tbi',
    isVerified: true,
  },
];

