/**
 * REAL-WORLD DOCUMENTED PROBLEM STATEMENTS
 * All statistics and facts are sourced from official publications of the
 * United Nations, WHO, FAO, World Bank, NITI Aayog, IEA, UNEP, UNESCO, and government bodies.
 */

export const realProblems = [
  // 1. AGRICULTURE & FOOD SECURITY
  {
    title: 'Post-Harvest Food Spoilage and Cold Chain Deficits in Emerging Economies',
    description: 'According to the UN Food and Agriculture Organization (FAO) 2023 State of Food and Agriculture, approximately 13.2% of global food production—valued at over $400 billion—is lost between harvest and retail. In South Asia and Sub-Saharan Africa, post-harvest losses for perishable fruits and vegetables exceed 35% due to inadequate farm-gate cold storage, poor rural road infrastructure, and lack of pre-cooling facilities.',
    sourceUrl: 'https://www.fao.org/state-of-food-security-nutrition',
    impactLevel: 9,
    categories: ['Agriculture & Food', 'Food & Water', 'Poverty & Inequality'],
    regions: ['South Asia', 'Africa', 'Global'],
    tags: ['Food Loss', 'Cold Storage', 'Post-Harvest', 'SDG 2', 'Supply Chain', 'Perishables'],
  },
  {
    title: 'Rapid Groundwater Aquifer Depletion in Major Breadbasket Regions',
    description: 'The World Bank Water Global Practice reports that agricultural irrigation accounts for 70% of global freshwater withdrawals. In the Indo-Gangetic Plain and North China Plain, water tables are dropping by 0.5 to 1.5 meters annually due to inefficient flood irrigation and subsidized power. Over 82% of rural drinking water in South Asia depends on these rapidly depleting aquifers.',
    sourceUrl: 'https://www.worldbank.org/en/topic/water-in-agriculture',
    impactLevel: 10,
    categories: ['Water & Sanitation', 'Agriculture & Food', 'Environment/Climate'],
    regions: ['South Asia', 'East Asia', 'Global'],
    tags: ['Groundwater', 'Aquifer Depletion', 'Drip Irrigation', 'Water Scarcity', 'SDG 6'],
  },
  {
    title: 'Severe Soil Degradation and Loss of Arable Land Fertility',
    description: 'The FAO Global Soil Partnership reports that 33% of Earth’s soils are moderately to severely degraded from erosion, salinization, synthetic chemical acidification, and organic matter depletion. Without intervention, 90% of topsoil could be degraded by 2050, threatening global caloric output while human population heads toward 9.8 billion.',
    sourceUrl: 'https://www.fao.org/soils-portal/about',
    impactLevel: 9,
    categories: ['Agriculture & Food', 'Environment/Climate'],
    regions: ['Global', 'South Asia', 'Africa', 'North America'],
    tags: ['Soil Health', 'Regenerative Agriculture', 'Topsoil', 'Erosion', 'Bio-fertilizers'],
  },
  {
    title: 'Invasive Agricultural Pest Outbreaks Accelerated by Climatic Shifts',
    description: 'CABI and the FAO estimate that invasive plant pests and diseases reduce global crop yields by 20% to 40% annually, costing the global economy roughly $220 billion. Warmer winters and changing monsoons have expanded the range of destructive pests like the Fall Armyworm across 70+ countries in Africa and Asia within four years.',
    sourceUrl: 'https://www.fao.org/pest-and-pesticide-management',
    impactLevel: 8,
    categories: ['Agriculture & Food', 'Technology & Innovation'],
    regions: ['Africa', 'South Asia', 'Latin America'],
    tags: ['Pest Management', 'Fall Armyworm', 'Crop Protection', 'Agronomy', 'Climate Shifts'],
  },
  {
    title: 'Smallholder Farmer Credit Gap and Lack of Weather-Indexed Crop Insurance',
    description: 'The International Finance Corporation (IFC) and CGAP document that over 500 million smallholder farming households produce 80% of food in developing countries, yet 85% lack access to formal agricultural bank loans or weather-index crop insurance, leaving them vulnerable to single-season drought bankruptcies.',
    sourceUrl: 'https://www.cgap.org/topics/collections/smallholder-finance',
    impactLevel: 9,
    categories: ['Agriculture & Food', 'Poverty & Inequality', 'Business & Commerce'],
    regions: ['South Asia', 'Africa', 'Latin America'],
    tags: ['AgriFintech', 'Microinsurance', 'Parametric Insurance', 'Financial Inclusion'],
  },
  {
    title: 'Low Efficiency in Smallholder Dairy Yields and Milk Adulteration Risks',
    description: 'India’s National Dairy Development Board (NDDB) and FAO report that while India is the world’s largest milk producer (220M metric tons annually), average dairy yield per cow remains 60% below global developed benchmarks. Smallholders lose income due to lack of cold chain milk chilling within 2 hours of milking, while undetected adulteration affects milk purity.',
    sourceUrl: 'https://www.nddb.coop/information/stats',
    impactLevel: 8,
    categories: ['Agriculture & Food', 'Supply Chain & Logistics'],
    regions: ['South Asia'],
    tags: ['Dairy Tech', 'Cold Chain', 'Milk Quality', 'Livestock Productivity'],
  },

  // 2. HEALTHCARE & PUBLIC HEALTH
  {
    title: 'Escalating Multi-Drug Antimicrobial Resistance (AMR)',
    description: 'A comprehensive study in The Lancet and WHO documents that bacterial antimicrobial resistance directly caused 1.27 million deaths globally in 2019 and contributed to 4.95 million deaths. By 2050, AMR is projected to cause 10 million deaths annually if novel narrow-spectrum antimicrobials and rapid diagnostic alternatives are not commercialized.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance',
    impactLevel: 10,
    categories: ['Healthcare', 'Health & Disease', 'Technology & Innovation'],
    regions: ['Global'],
    tags: ['AMR', 'Superbugs', 'Antibiotics', 'Infectious Disease', 'SDG 3'],
  },
  {
    title: 'Delayed Oncology Detection in Resource-Constrained Rural Clinics',
    description: 'The World Health Organization (WHO) reports that 70% of global cancer mortalities occur in low- and middle-income nations, primarily because more than 60% of patients are diagnosed at Stage III or IV. In rural areas, specialized oncologists, mammography units, and pathology labs are virtually absent.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/cancer',
    impactLevel: 9,
    categories: ['Healthcare', 'Health & Disease', 'Rural Development'],
    regions: ['South Asia', 'Africa', 'Latin America'],
    tags: ['Oncology', 'Cancer Screening', 'Rural Healthcare', 'Diagnostics', 'Early Detection'],
  },
  {
    title: 'Critical Mental Health Treatment Gap in Low- and Middle-Income Countries',
    description: 'The WHO World Mental Health Report reveals that nearly 1 billion individuals live with a mental disorder. In low-income nations, over 75% of individuals with severe conditions receive zero treatment. Many African and South Asian nations have fewer than 1 psychiatrist per 100,000 residents.',
    sourceUrl: 'https://www.who.int/publications/i/item/9789240049338',
    impactLevel: 8,
    categories: ['Healthcare', 'Health & Disease'],
    regions: ['Global', 'Africa', 'South Asia'],
    tags: ['Mental Health', 'Depression', 'Tele-counseling', 'Public Health', 'Stigma'],
  },
  {
    title: 'Preventable Maternal Mortality from Postpartum Complications',
    description: 'UNFPA, WHO, and UNICEF report that approximately 287,000 women died from pregnancy and childbirth complications in 2020—nearly 800 maternal deaths per day. Almost 95% occurred in low- and lower-middle-income countries due to delayed recognition of postpartum hemorrhage and hypertensive pre-eclampsia.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/maternal-mortality',
    impactLevel: 9,
    categories: ['Healthcare', 'Health & Disease', 'Women & Social'],
    regions: ['Africa', 'South Asia'],
    tags: ['Maternal Health', 'Obstetric Care', 'Postpartum', 'Remote Monitoring', 'SDG 3'],
  },
  {
    title: 'High Prevalence of Undetected Chronic Diabetic Retinopathy',
    description: 'The International Diabetes Federation (IDF) Diabetes Atlas estimates that 537 million adults live with diabetes, expected to reach 783 million by 2045. Up to one-third develop diabetic retinopathy—the leading cause of preventable blindness in working-age adults—yet annual fundus screening reaches less than 15% in developing regions.',
    sourceUrl: 'https://diabetesatlas.org/',
    impactLevel: 8,
    categories: ['Healthcare', 'Technology & Innovation'],
    regions: ['South Asia', 'Middle East', 'Global'],
    tags: ['Diabetes', 'Diabetic Retinopathy', 'Preventative Screening', 'Ophthalmology', 'AI Diagnostics'],
  },
  {
    title: 'Lack of Automated Remote ICU Bed Monitoring in Secondary Hospitals',
    description: 'According to NITI Aayog healthcare infrastructure assessments, over 75% of intensive care specialists in India are concentrated in top 10 metropolitan cities. Secondary district hospitals lack 24/7 intensivist coverage, leading to avoidable patient code-blues that went unnoticed on general wards.',
    sourceUrl: 'https://www.niti.gov.in/report-and-indices',
    impactLevel: 8,
    categories: ['Healthcare', 'Rural Development'],
    regions: ['South Asia'],
    tags: ['Tele-ICU', 'Remote Patient Monitoring', 'Vitals Telemetry', 'Hospital Capacity'],
  },

  // 3. CLIMATE, ENERGY & ENVIRONMENT
  {
    title: 'Industrial Greenhouse Gas Emissions from Hard-to-Abate Sectors (Cement, Steel, Chemicals)',
    description: 'The International Energy Agency (IEA) reports that heavy industry (cement, iron and steel, and chemicals) accounts for roughly 70% of global industrial direct CO2 emissions and 25% of total energy system emissions. Decarbonizing these sectors requires commercializing green hydrogen reduction, carbon capture, and novel low-clinker binders.',
    sourceUrl: 'https://www.iea.org/reports/achieving-net-zero-heavy-industry-sectors-in-g7-members',
    impactLevel: 10,
    categories: ['Environment/Climate', 'Energy & Infrastructure', 'Climate & Environment'],
    regions: ['Global', 'North America', 'Europe', 'East Asia'],
    tags: ['Decarbonization', 'Hard-to-Abate', 'Green Hydrogen', 'Cement', 'Steel', 'SDG 13'],
  },
  {
    title: 'Multi-Day Long-Duration Energy Storage (LDES) Deficit on Renewable Power Grids',
    description: 'The US Department of Energy (DOE) Liftoff Report on LDES finds that while 4-hour lithium-ion batteries support intra-day peak shaving, integrating 70%+ intermittent solar and wind requires 10-100+ hour multi-day storage systems (iron-air, thermal, compressed air) to prevent grid curtailments and winter reliability failures.',
    sourceUrl: 'https://liftoff.energy.gov/long-duration-energy-storage/',
    impactLevel: 9,
    categories: ['Energy & Infrastructure', 'Energy', 'Environment/Climate'],
    regions: ['North America', 'Europe', 'Global'],
    tags: ['Grid Storage', 'LDES', 'Clean Energy', 'Renewable Integration', 'Battery Storage'],
  },
  {
    title: 'Methane Emissions from Ruminant Enteric Fermentation and Livestock Manure',
    description: 'The UNEP Global Methane Assessment documents that livestock agriculture accounts for 32% of anthropogenic methane emissions—a greenhouse gas with 80 times the warming potential of CO2 over a 20-year window. Novel natural feed additives (e.g. Asparagopsis seaweed) and biodigester capture are needed at commercial scale.',
    sourceUrl: 'https://www.unep.org/resources/report/global-methane-assessment',
    impactLevel: 8,
    categories: ['Environment/Climate', 'Agriculture & Food'],
    regions: ['Global', 'Latin America', 'North America'],
    tags: ['Methane', 'Livestock', 'Enteric Fermentation', 'Clean Agriculture'],
  },
  {
    title: 'Per- and Polyfluoroalkyl Substances (PFAS) Forever Chemical Contamination in Tap Water',
    description: 'The US Environmental Protection Agency (EPA) and European Environment Agency confirm that PFAS contaminants are present in drinking water systems serving over 100 million people across North America and Europe. These synthetic carbon-fluorine bonds resist natural degradation, accumulating in human blood serum and organs.',
    sourceUrl: 'https://www.epa.gov/pfas',
    impactLevel: 9,
    categories: ['Water & Sanitation', 'Environment/Climate', 'Healthcare'],
    regions: ['North America', 'Europe'],
    tags: ['PFAS', 'Water Treatment', 'Forever Chemicals', 'Nanofiltration'],
  },
  {
    title: 'Household Air Pollution Exposure from Biomass Cooking Stoves',
    description: 'The World Health Organization attributes 3.2 million premature deaths annually to household air pollution caused by cooking with polluting solid biomass and kerosene open fires. Women and children suffer disproportionate rates of chronic obstructive pulmonary disease (COPD) and cataracts.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/household-air-pollution-and-health',
    impactLevel: 9,
    categories: ['Energy', 'Healthcare', 'Women & Social'],
    regions: ['Africa', 'South Asia'],
    tags: ['Clean Cooking', 'Indoor Air Pollution', 'Biomass', 'Women Health', 'SDG 7'],
  },
  {
    title: 'Urban Heat Island Effect Exacerbating Extreme Heat Mortality in Dense Cities',
    description: 'UN-Habitat reports that built-up metropolitan areas in the Global South experience ambient temperatures up to 6°C to 8°C higher than surrounding rural perimeters due to dark asphalt, concrete thermal mass, and lack of reflective vegetative canopy.',
    sourceUrl: 'https://unhabitat.org/topic/climate-change-and-urban-environment',
    impactLevel: 8,
    categories: ['Environment/Climate', 'Energy'],
    regions: ['South Asia', 'Middle East', 'Latin America'],
    tags: ['Urban Heat', 'Cool Roofs', 'Urban Resilience', 'Climate Adaptation'],
  },

  // 4. CIRCULAR ECONOMY, WASTE & WATER
  {
    title: 'Low Mechanical Recycling Rates for Blended Post-Consumer Plastic Polymers',
    description: 'The UN Environment Programme (UNEP) calculates that less than 9% of the 400 million metric tons of annual global plastic waste is successfully recycled. Mechanical recycling centers discard up to 50% of incoming scrap because multi-layer flexible films, PET, HDPE, and polypropylene cannot be separated accurately at conveyor belt speeds.',
    sourceUrl: 'https://www.unep.org/interactives/beat-plastic-pollution/',
    impactLevel: 9,
    categories: ['Waste Management', 'Environment/Climate'],
    regions: ['Global', 'Europe', 'South Asia'],
    tags: ['Plastic Waste', 'Recycling', 'Circular Economy', 'Optical Sorting', 'Polymers'],
  },
  {
    title: 'Toxic Informal Smelting of Global Electrical and Electronic Waste (E-Waste)',
    description: 'The ITU and UNITAR Global E-Waste Monitor 2024 reveals that a record 62 million metric tons of e-waste was generated in 2022, with less than 22.3% formally documented as collected and recycled. Backyard open-air burning and acid-bath leaching release lead, cadmium, and dioxins into surrounding groundwater.',
    sourceUrl: 'https://www.itu.int/hub/publication/d-gen-e_waste-01-2024/',
    impactLevel: 8,
    categories: ['Waste Management', 'Healthcare'],
    regions: ['Africa', 'South Asia', 'Global'],
    tags: ['E-Waste', 'Circular Electronics', 'Heavy Metals', 'Urban Mining'],
  },
  {
    title: 'Municipal Non-Revenue Water Loss from Subsurface Pipe Leaks',
    description: 'The International Water Association (IWA) estimates that over 346 billion liters of treated drinking water are lost every day globally via underground distribution pipeline leaks and pressure ruptures—representing $39 billion in annual utility revenue losses.',
    sourceUrl: 'https://iwa-network.org/programs/non-revenue-water/',
    impactLevel: 8,
    categories: ['Water & Sanitation', 'Rural Development'],
    regions: ['Global', 'South Asia', 'Latin America'],
    tags: ['Non-Revenue Water', 'Pipe Leaks', 'Acoustic Sensors', 'Municipal Utilities'],
  },
  {
    title: 'Single-Use Expanded Polystyrene Packaging Fragmentation into Microplastics',
    description: 'The Ocean Conservancy reports that single-use expanded polystyrene (EPS/Styrofoam) takes upwards of 500 years to decompose in marine environments, fragmenting into microplastic pellets that enter zooplankton and fish digestive systems.',
    sourceUrl: 'https://oceanconservancy.org/trash-free-seas/',
    impactLevel: 8,
    categories: ['Waste Management', 'Environment/Climate'],
    regions: ['Global'],
    tags: ['Packaging', 'Microplastics', 'Biomaterials', 'Seaweed Packaging'],
  },

  // 5. EDUCATION, EMPLOYMENT & SKILLS
  {
    title: 'Foundational Literacy and Numeracy Learning Crisis in Primary Classrooms',
    description: 'The World Bank and UNESCO Global Education Monitoring Report estimate that 70% of 10-year-olds in low- and middle-income nations cannot read or comprehend a simple written text. Classroom overcrowding and static one-size-fits-all curricula leave pupils behind fundamental cognitive milestones.',
    sourceUrl: 'https://www.unesco.org/en/education',
    impactLevel: 9,
    categories: ['Education & Skills', 'Education', 'Poverty & Inequality'],
    regions: ['South Asia', 'Africa', 'Latin America'],
    tags: ['Foundational Literacy', 'EdTech', 'Primary Education', 'Socratic Learning', 'SDG 4'],
  },
  {
    title: 'Severe Youth Unemployment and Vocational Apprenticeship Mismatch',
    description: 'The International Labour Organization (ILO) reports that over 73 million young individuals globally are unemployed, while millions more are underemployed in the informal economy. Technical and polytechnic graduates lack project-based portfolios verified by industry employers.',
    sourceUrl: 'https://www.ilo.org/global/topics/youth-employment/lang--en/index.htm',
    impactLevel: 8,
    categories: ['Education & Skills', 'Poverty & Inequality'],
    regions: ['Global', 'South Asia', 'Africa'],
    tags: ['Vocational Training', 'Youth Employment', 'Apprenticeships', 'Future of Work', 'SDG 8'],
  },
  {
    title: 'Persistent Digital Gender Divide in STEM Education and Venture Funding',
    description: 'UN Women and ITU report that women hold less than 28% of engineering and computer science roles globally, and female-founded startups receive less than 2.3% of venture capital funding worldwide, limiting diverse perspective in technological solutions.',
    sourceUrl: 'https://www.unwomen.org/en/digital-library/publications',
    impactLevel: 8,
    categories: ['Women & Social', 'Education & Skills'],
    regions: ['Global'],
    tags: ['Gender Equality', 'Women in Tech', 'Venture Funding', 'STEM', 'SDG 5'],
  },

  // 6. FINTECH, MSME COMMERCE & SUPPLY CHAIN
  {
    title: 'High Cross-Border Trade Payment Fees and Delayed Settlement for Emerging Market SMEs',
    description: 'The World Bank and WTO estimate that emerging market micro-, small-, and medium-sized enterprises lose $50 billion annually in correspondent banking spreads and currency exchange fees when trading internationally, with settlements averaging 3 to 5 business days.',
    sourceUrl: 'https://www.worldbank.org/en/topic/financialinclusion',
    impactLevel: 8,
    categories: ['Business & Commerce', 'Economy & Inequality', 'Supply Chain & Logistics'],
    regions: ['Africa', 'South Asia', 'Southeast Asia'],
    tags: ['Cross-Border Payments', 'SME Trade', 'FX Hedging', 'Open Banking'],
  },
  {
    title: 'Severe Working Capital Bottlenecks from Delayed 60-90 Day B2B Invoicing',
    description: 'The International Finance Corporation (IFC) documents a $5.2 trillion unmet financing demand for 65 million micro, small, and medium enterprises in developing countries. Large corporate buyers mandate 60 to 120-day credit terms, pushing solvent suppliers into liquidity insolvency.',
    sourceUrl: 'https://www.ifc.org/en/what-we-do/sector-expertise/financial-institutions/msme-finance',
    impactLevel: 9,
    categories: ['Business & Commerce', 'Economy & Inequality'],
    regions: ['South Asia', 'Latin America', 'Africa'],
    tags: ['Invoice Factoring', 'Working Capital', 'MSME Finance', 'Cash Flow'],
  },
  {
    title: 'Empty Return-Trip Trailer Miles in Fragmented Road Freight Transport',
    description: 'The International Transport Forum (ITF) reveals that commercial road freight trucks travel without cargo or substantially under-loaded on roughly 22% of total journey kilometers due to bilateral route asymmetry and lack of digital carrier capacity pooling.',
    sourceUrl: 'https://www.itf-oecd.org/freight-transport',
    impactLevel: 7,
    categories: ['Supply Chain & Logistics', 'Transportation', 'Environment/Climate'],
    regions: ['Europe', 'North America', 'South Asia'],
    tags: ['Freight Logistics', 'Empty Miles', 'Capacity Utilization', 'Transport Emissions'],
  },
  {
    title: 'Excessive E-Commerce Reverse Logistics and Landfill Return Waste',
    description: 'The National Retail Federation (NRF) and Reverse Logistics Association estimate that 16% to 20% of e-commerce apparel and merchandise is returned by consumers, costing retailers $743 billion annually and sending over 5 billion pounds of returns straight to landfills.',
    sourceUrl: 'https://nrf.com/research-insights/consumer-merchandise-returns',
    impactLevel: 8,
    categories: ['Business & Commerce', 'Waste Management'],
    regions: ['North America', 'Europe', 'East Asia'],
    tags: ['Reverse Logistics', 'Retail Returns', 'E-Commerce', 'Inventory Liquidation'],
  },

  // 7. TECHNOLOGY, AI SAFETY & CYBERSECURITY
  {
    title: 'Vulnerability of Enterprise Large Language Models to Indirect Prompt Injections',
    description: 'The OWASP Top 10 for LLM Applications identifies Prompt Injection and Data Poisoning as the primary architectural threat to enterprise AI systems. Malicious text hidden in documents, emails, or websites can hijack LLM agents to exfiltrate database records or execute unauthorized tool calls.',
    sourceUrl: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
    impactLevel: 8,
    categories: ['Technology & Innovation', 'Cybersecurity', 'AI & Technology'],
    regions: ['Global', 'North America', 'Europe'],
    tags: ['AI Safety', 'Prompt Injection', 'LLM Security', 'Enterprise AI', 'OWASP'],
  },
  {
    title: 'Severe Lack of Quality Multilingual Corpora and ASR for Vernacular Dialects',
    description: 'UNESCO and the ITU report that while thousands of languages are spoken globally, over 85% of online digital content and AI training corpora exist in just 10 major languages. Billions of non-English and regional language speakers face an AI literacy divide.',
    sourceUrl: 'https://www.itu.int/hub/2023/11/facts-and-figures-2023',
    impactLevel: 8,
    categories: ['Technology & Innovation', 'Digital Access'],
    regions: ['South Asia', 'Africa', 'Southeast Asia'],
    tags: ['Indic Languages', 'Vernacular AI', 'Digital Divide', 'Speech Recognition', 'Inclusion'],
  },
  {
    title: 'Ransomware Targeting Critical Municipal Healthcare and Water SCADA Systems',
    description: 'The US Cybersecurity and Infrastructure Security Agency (CISA) reports that ransomware and state-sponsored attacks against critical infrastructure increased 73% year-over-year. Hospital IT networks and legacy industrial control systems face severe disruption from extortionists.',
    sourceUrl: 'https://www.cisa.gov/topics/industrial-control-systems',
    impactLevel: 9,
    categories: ['Cybersecurity', 'Healthcare'],
    regions: ['North America', 'Europe', 'Global'],
    tags: ['Ransomware', 'SCADA', 'Critical Infrastructure', 'Cyber Defense'],
  },

  // 8. RURAL DEVELOPMENT & ACCESSIBILITY
  {
    title: 'Lack of Cold-Storage Diagnostic Sample Transportation in Rural Primary Healthcare',
    description: 'The Indian Council of Medical Research (ICMR) and WHO report that blood, sputum, and tissue pathology specimens collected in remote sub-district clinics degrade in transit due to lack of portable temperature-regulated transport, leading to repeat clinic visits and delayed diagnoses.',
    sourceUrl: 'https://www.icmr.gov.in/',
    impactLevel: 8,
    categories: ['Healthcare', 'Rural Development'],
    regions: ['South Asia', 'Africa'],
    tags: ['Point-of-Care', 'Sample Transport', 'Cold Chain', 'Rural Clinics'],
  },
  {
    title: 'Prohibitive Costs of Quality Assistive Technologies for Persons with Disabilities',
    description: 'The WHO and UNICEF Global Report on Assistive Technology estimates that over 2.5 billion individuals require assistive products (hearing aids, prosthetics, communication tablets), yet fewer than 10% in low-income nations have access due to high manufacturing costs.',
    sourceUrl: 'https://www.who.int/publications/i/item/9789240049451',
    impactLevel: 8,
    categories: ['Healthcare', 'Education & Skills'],
    regions: ['Global', 'South Asia', 'Africa'],
    tags: ['Assistive Technology', 'Accessibility', 'Prosthetics', 'Inclusion', 'SDG 10'],
  },

  // 9. MATERNAL HEALTH, PEDIATRICS & INFECTIOUS DISEASE
  {
    title: 'High Rates of Maternal Mortality from Preventable Postpartum Hemorrhage',
    description: 'The World Health Organization (WHO) and UNICEF report that an estimated 287,000 women died during and following pregnancy and childbirth in 2020 alone, with approximately 70% occurring in Sub-Saharan Africa and 16% in South Asia. Postpartum hemorrhage (PPH) remains the leading cause of preventable maternal death due to delays in detection and lack of oxytocin cold storage in primary care facilities.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/maternal-mortality',
    impactLevel: 10,
    categories: ['Healthcare', 'Health & Disease'],
    regions: ['Africa', 'South Asia', 'Global'],
    tags: ['Maternal Health', 'PPH', 'Primary Care', 'SDG 3', 'Obstetrics'],
  },
  {
    title: 'Delayed Detection and High Mortality of Multidrug-Resistant Tuberculosis (MDR-TB)',
    description: 'According to the WHO Global Tuberculosis Report 2023, TB remains one of the world\'s deadliest infectious killers, causing 1.3 million deaths annually. Alarmingly, 410,000 people developed multidrug-resistant or rifampicin-resistant TB (MDR/RR-TB), yet only about 40% accessed treatment due to slow conventional culture diagnostics and high diagnostic cartridge costs.',
    sourceUrl: 'https://www.who.int/teams/global-tuberculosis-programme/tb-reports/global-tuberculosis-report-2023',
    impactLevel: 9,
    categories: ['Healthcare', 'Health & Disease'],
    regions: ['South Asia', 'Africa', 'Eastern Europe', 'Global'],
    tags: ['Tuberculosis', 'MDR-TB', 'Infectious Disease', 'Diagnostics', 'WHO'],
  },
  {
    title: 'Pervasive Global Mental Health Treatment Gap in Low-Resource Settings',
    description: 'The WHO World Mental Health Report documents that nearly 1 billion people live with a mental disorder, yet in low- and middle-income countries, between 75% and 85% receive no treatment. Low availability of licensed clinical psychologists and extreme cultural stigma prevent early intervention for depression, anxiety, and neurodivergence.',
    sourceUrl: 'https://www.who.int/publications/i/item/9789240049338',
    impactLevel: 8,
    categories: ['Healthcare', 'Health & Disease'],
    regions: ['Global', 'South Asia', 'Africa', 'Latin America'],
    tags: ['Mental Health', 'Psychology', 'Telehealth', 'Inclusion', 'Stigma Reduction'],
  },
  {
    title: 'Prohibitive Pricing and Cold-Chain Vulnerabilities in Insulin Access',
    description: 'The WHO Global Report on Diabetes and The Lancet Diabetes & Endocrinology reveal that over 50% of the 60 million people worldwide with type 2 diabetes who require insulin cannot access or afford it reliably. In sub-tropical regions, lack of home refrigeration ruins insulin potency.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/diabetes',
    impactLevel: 8,
    categories: ['Healthcare', 'Health & Disease'],
    regions: ['Africa', 'South Asia', 'Latin America'],
    tags: ['Diabetes', 'Insulin', 'Cold Chain', 'Chronic Disease', 'Affordable Medicine'],
  },
  {
    title: 'Counterfeit and Substandard Pharmaceutical Drugs in Emerging Markets',
    description: 'The WHO Global Surveillance and Monitoring System estimates that 1 in 10 medical products in developing countries is substandard or falsified, leading to an estimated 100,000 child deaths annually from fake antimalarials and antibiotics alone. Fragmented wholesale supply chains lack cryptographic traceability.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/substandard-and-falsified-medical-products',
    impactLevel: 9,
    categories: ['Healthcare', 'Supply Chain & Logistics'],
    regions: ['Africa', 'South Asia', 'Southeast Asia'],
    tags: ['Counterfeit Medicine', 'Drug Safety', 'Supply Chain Traceability', 'Pharma'],
  },

  // 10. CLIMATE, FORESTS, EMISSIONS & ENERGY
  {
    title: 'Severe Urban Heat Island Effect and Extreme Heat Mortalities in Dense Metropolises',
    description: 'The Intergovernmental Panel on Climate Change (IPCC) Sixth Assessment Report warns that urban heat island (UHI) effects elevate city temperatures by 3°C to 7°C above surrounding rural baselines. Dense concrete construction, lack of urban tree canopy, and AC waste heat create lethal thermal conditions for outdoor workers and vulnerable elders in megacities.',
    sourceUrl: 'https://www.ipcc.ch/report/ar6/wg2/',
    impactLevel: 9,
    categories: ['Environment/Climate', 'Urban Planning & Housing'],
    regions: ['South Asia', 'Middle East', 'North America', 'Global'],
    tags: ['Urban Heat', 'Cool Roofs', 'Climate Resilience', 'Extreme Heat', 'Urban Forestry'],
  },
  {
    title: 'Accelerating Tropical Deforestation and Habitat Fragmentation',
    description: 'Global Forest Watch and the UN Food and Agriculture Organization (FAO) report that the world loses approximately 10 million hectares of forest every year—equivalent to an area the size of Portugal. Deforestation in the Amazon, Congo Basin, and Southeast Asia drives 11% of global greenhouse gas emissions and accelerates extinction risks for 1 million species.',
    sourceUrl: 'https://www.globalforestwatch.org/',
    impactLevel: 9,
    categories: ['Environment/Climate', 'Agriculture & Food'],
    regions: ['Latin America', 'Africa', 'Southeast Asia', 'Global'],
    tags: ['Deforestation', 'Carbon Sinks', 'Biodiversity', 'Satellite Monitoring', 'Canopy'],
  },
  {
    title: 'Fugitive Methane Leakages in Fossil Fuel and Coal Mining Infrastructure',
    description: 'The International Energy Agency (IEA) Global Methane Tracker highlights that the global energy sector was responsible for over 120 million tonnes of methane emissions in 2023. Methane is over 80 times more potent than carbon dioxide at warming the atmosphere over a 20-year timescale, yet most pipeline and wellhead leaks remain unmonitored by ground operators.',
    sourceUrl: 'https://www.iea.org/reports/global-methane-tracker-2024',
    impactLevel: 9,
    categories: ['Environment/Climate', 'Clean Energy'],
    regions: ['North America', 'Central Asia', 'Middle East', 'Global'],
    tags: ['Methane', 'Greenhouse Gases', 'Satellite Sensing', 'Leak Detection', 'IEA'],
  },
  {
    title: 'High Embodied Carbon and Resource Intensity of Traditional Portland Cement',
    description: 'The IEA and Global Alliance for Buildings and Construction report that cement production accounts for roughly 7% of total global CO2 emissions. Driven by limestone calcination at 1450°C, every ton of ordinary Portland cement produces approximately 0.6 to 0.9 tons of CO2.',
    sourceUrl: 'https://www.iea.org/reports/cement',
    impactLevel: 8,
    categories: ['Environment/Climate', 'Technology & Innovation'],
    regions: ['Global', 'East Asia', 'South Asia', 'North America'],
    tags: ['Green Cement', 'Embodied Carbon', 'Decarbonization', 'Circular Materials'],
  },
  {
    title: 'Delayed Detection and Catastrophic Spread of Climate-Induced Mega-Wildfires',
    description: 'NASA Earth Observatory and the US Forest Service document that global wildfire seasons have lengthened by 27% since 1979, with megablazes scorching over 4 million hectares annually in Canada, California, and the Mediterranean. Delayed initial-attack dispatch due to reliance on human lookout towers and low-frequency satellite passes results in fires escaping containment.',
    sourceUrl: 'https://earthobservatory.nasa.gov/blogs/earthmatters/category/wildfires/',
    impactLevel: 9,
    categories: ['Environment/Climate', 'Public Safety & Defense'],
    regions: ['North America', 'Europe', 'Australia'],
    tags: ['Wildfire', 'Thermal Sensing', 'Early Warning', 'Forestry', 'Emergency Response'],
  },
  {
    title: 'Household Air Pollution from Inefficient Biomass and Charcoal Cooking Stoves',
    description: 'The World Health Organization (WHO) and Clean Cooking Alliance report that 2.3 billion people—nearly one-third of humanity—still cook over open fires or inefficient biomass stoves burning wood, charcoal, and dung. Household air pollution causes an estimated 3.2 million premature deaths each year, predominantly women and young children.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/household-air-pollution-and-health',
    impactLevel: 9,
    categories: ['Environment/Climate', 'Healthcare', 'Clean Energy'],
    regions: ['Africa', 'South Asia', 'Southeast Asia'],
    tags: ['Clean Cooking', 'Household Air Pollution', 'Biomass', 'SDG 7', 'Respiratory Health'],
  },
  {
    title: 'Coastal Aquifer Salinization and Soil Salinity from Rising Sea Levels',
    description: 'The IPCC Special Report on the Ocean and Cryosphere documents that sea level rise and increased storm surge frequency are driving saltwater intrusion up to 15 kilometers inland into coastal deltas (Mekong, Nile, Sundarbans). Saline water renders thousands of square kilometers of productive rice paddies barren.',
    sourceUrl: 'https://www.ipcc.ch/srocc/',
    impactLevel: 8,
    categories: ['Environment/Climate', 'Water & Sanitation', 'Agriculture & Food'],
    regions: ['South Asia', 'Southeast Asia', 'Middle East'],
    tags: ['Salinity', 'Sea Level Rise', 'Coastal Deltas', 'Desalination', 'Halophyte Crops'],
  },

  // 11. INDUSTRIAL EFFLUENTS, TEXTILES & WATER POLLUTION
  {
    title: 'Toxic Dye Effluents and Water Consumption in Synthetic Textile Manufacturing',
    description: 'The UN Alliance for Sustainable Fashion and Ellen MacArthur Foundation report that clothing production produces 20% of global industrial wastewater and 10% of global carbon emissions. Chemical dyeing releases untreated heavy metals (chromium, copper) and azo dyes into river basins in South and Southeast Asia, destroying aquatic ecosystems.',
    sourceUrl: 'https://unfashionalliance.org/',
    impactLevel: 8,
    categories: ['Environment/Climate', 'Water & Sanitation', 'Waste Management'],
    regions: ['South Asia', 'Southeast Asia', 'East Asia'],
    tags: ['Fast Fashion', 'Textile Waste', 'Water Pollution', 'Circular Fashion', 'Dyeing'],
  },
  {
    title: 'Agricultural Nutrient Runoff and Expanding Freshwater Toxic Algal Blooms',
    description: 'The US Environmental Protection Agency (EPA) and UNEP document that excess nitrogen and phosphorus runoff from commercial synthetic fertilizers causes over 500 oceanic and lake hypoxic dead zones worldwide. Harmful cyanobacteria algal blooms contaminate municipal drinking water reservoirs with neurotoxins.',
    sourceUrl: 'https://www.epa.gov/nutrientpollution',
    impactLevel: 8,
    categories: ['Water & Sanitation', 'Environment/Climate', 'Agriculture & Food'],
    regions: ['North America', 'Europe', 'East Asia', 'Global'],
    tags: ['Eutrophication', 'Algal Blooms', 'Nutrient Runoff', 'Water Quality', 'Fertilizer'],
  },

  // 12. LOGISTICS, INFRASTRUCTURE & URBAN GOVERNANCE
  {
    title: 'High Maritime Port Congestion and Extended Container Dwell Times',
    description: 'UNCTAD Review of Maritime Transport documents that port bottlenecks, delayed terminal customs handoffs, and paper-based bill of lading documentation add an estimated $30 billion annually in demurrage fees and excess fuel burn. Over 80% of global merchandise trade travels by ship.',
    sourceUrl: 'https://unctad.org/topic/transport-and-logistics/review-of-maritime-transport',
    impactLevel: 8,
    categories: ['Supply Chain & Logistics', 'Technology & Innovation'],
    regions: ['Global', 'North America', 'East Asia', 'Europe'],
    tags: ['Maritime', 'Port Logistics', 'Supply Chain', 'Demurrage', 'Trade Finance'],
  },
  {
    title: 'Inadequate Stormwater Drainage and Recurrent Urban Flash Floods',
    description: 'NITI Aayog and UN-Habitat indicate that rapid, unplanned concretization in Global South cities has paved over natural wetland retention basins. A typical 50mm monsoon downpour now causes catastrophic urban flooding, submerging road corridors, contaminating drinking supplies, and inflicting billions in damages.',
    sourceUrl: 'https://www.niti.gov.in/reforms-urban-planning-capacity-india',
    impactLevel: 9,
    categories: ['Urban Planning & Housing', 'Water & Sanitation'],
    regions: ['South Asia', 'Southeast Asia', 'Latin America'],
    tags: ['Urban Floods', 'Stormwater', 'Drainage', 'Sponge Cities', 'Civil Infrastructure'],
  },
  {
    title: 'Lack of Accessible Wheelchair Infrastructure and Universal Transit Design',
    description: 'UN-Habitat and the World Bank report that in emerging economies, fewer than 5% of public buses, rapid transit stations, and sidewalk corridors meet basic accessibility standards for wheelchair users and visually impaired pedestrians, restricting educational and economic opportunities.',
    sourceUrl: 'https://unhabitat.org/topic/urban-mobility',
    impactLevel: 8,
    categories: ['Urban Planning & Housing', 'Public Safety & Defense'],
    regions: ['Global', 'South Asia', 'Latin America', 'Africa'],
    tags: ['Accessibility', 'Universal Design', 'Transit', 'Wheelchair Access', 'Inclusion'],
  },

  // 13. BUSINESS, FINANCIAL LITERACY & DIGITAL GOVERNANCE
  {
    title: 'High Failure Rate of Micro-Enterprises from Manual Ledger Accounting and Tax Non-Compliance',
    description: 'The World Bank Enterprise Surveys show that over 70% of unregistered micro-retailers in emerging economies fail within 3 years due to uncollected customer credit (bahi-khata book deficits), inventory shrinkage, and inability to produce formal financial statements for bank loans.',
    sourceUrl: 'https://www.enterprisesurveys.org/',
    impactLevel: 8,
    categories: ['Business & Commerce', 'Poverty & Inequality'],
    regions: ['South Asia', 'Southeast Asia', 'Latin America', 'Africa'],
    tags: ['MSME', 'Digital Bookkeeping', 'Bahi Khata', 'Working Capital', 'Micro-business'],
  },
  {
    title: 'Proliferation of AI-Generated Deepfake Fraud and Voice Clones in Banking',
    description: 'The World Economic Forum Global Risks Report 2024 ranks AI-powered misinformation and synthetic media identity impersonation among the top immediate global threats. Cybercriminals utilize seconds of audio samples to generate synthetic voice clones that bypass voice biometric telephone banking authentication.',
    sourceUrl: 'https://www.weforum.org/publications/global-risks-report-2024/',
    impactLevel: 8,
    categories: ['Cybersecurity', 'Business & Commerce'],
    regions: ['Global', 'North America', 'Europe', 'South Asia'],
    tags: ['Deepfakes', 'Voice Cloning', 'Biometric Fraud', 'AI Safety', 'Cybercrime'],
  },
  {
    title: 'Cybercrime and Targeted Phishing Schemes Exploiting First-Time Digital Citizens',
    description: 'The FBI Internet Crime Complaint Center (IC3) and India\'s Indian Cyber Crime Coordination Centre (I4C) report that digital financial fraud targeting rural and senior citizens increased over 150% with the advent of real-time instant payment systems (UPI, Pix, FedNow).',
    sourceUrl: 'https://www.ic3.gov/',
    impactLevel: 8,
    categories: ['Cybersecurity', 'Digital Access'],
    regions: ['Global', 'South Asia', 'North America', 'Latin America'],
    tags: ['Phishing', 'Social Engineering', 'Financial Fraud', 'Cyber Awareness', 'UPI Fraud'],
  },

  // 14. EDUCATION, GENDER & SOCIAL RESILIENCE
  {
    title: 'Adolescent School Absenteeism Driven by Inadequate Menstrual Hygiene Facilities',
    description: 'UNICEF and UNESCO report that 1 in 3 schools globally lacks basic sanitation services, and over 500 million women and girls worldwide lack adequate facilities for menstrual hygiene management. In rural schools, adolescent girls miss up to 20% of the academic year during their menstrual cycles.',
    sourceUrl: 'https://www.unicef.org/wash/menstrual-hygiene',
    impactLevel: 8,
    categories: ['Education & Skills', 'Water & Sanitation'],
    regions: ['South Asia', 'Africa', 'Global'],
    tags: ['Menstrual Hygiene', 'Girls Education', 'Sanitation', 'WASH', 'SDG 4'],
  },
  {
    title: 'Prevalence of Chronic Kidney Disease of Unknown Etiology (CKDu) in Agricultural Regions',
    description: 'The World Health Organization (WHO) and The Lancet report that tens of thousands of agricultural field laborers in Sri Lanka, India, and Central America suffer from fatal Chronic Kidney Disease of Unknown Etiology (CKDu). The disease is tied to chronic occupational heat stress, dehydration, and heavy metal/silica contamination in groundwater.',
    sourceUrl: 'https://www.who.int/bulletin/volumes/97/2/18-219196/en/',
    impactLevel: 8,
    categories: ['Healthcare', 'Water & Sanitation', 'Agriculture & Food'],
    regions: ['South Asia', 'Latin America'],
    tags: ['CKDu', 'Occupational Health', 'Heat Stress', 'Water Testing', 'Farm Workers'],
  },
  {
    title: 'Critical Absence of Multi-Hazard Early Warning Systems in Small Island Developing States',
    description: 'The World Meteorological Organization (WMO) and UN Office for Disaster Risk Reduction (UNDRR) report that one-third of the world’s population—predominantly in Small Island Developing States (SIDS) and Least Developed Countries—remains unprotected by early warning disaster services, leading to 8 times higher mortality during extreme cyclone and tsunami events.',
    sourceUrl: 'https://wmo.int/early-warnings-for-all',
    impactLevel: 9,
    categories: ['Environment/Climate', 'Public Safety & Defense'],
    regions: ['Global', 'Africa', 'Southeast Asia'],
    tags: ['Early Warning', 'Disaster Resilience', 'SIDS', 'Extreme Weather', 'WMO'],
  },
  {
    title: 'Extreme Decline in Wild Pollinator Populations Threatening Global Nutritional Crops',
    description: 'The Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES) reveals that over 75% of leading global food crops depend on animal pollination. Wild bee and butterfly populations have crashed by up to 50% in heavily cultivated areas due to systemic neonicotinoid pesticides, monocultures, and habitat destruction.',
    sourceUrl: 'https://www.ipbes.net/assessment-reports/pollinators',
    impactLevel: 9,
    categories: ['Agriculture & Food', 'Environment/Climate'],
    regions: ['Global', 'North America', 'Europe', 'South Asia'],
    tags: ['Pollinators', 'Biodiversity', 'Bee Populations', 'Food Security', 'Agroecology'],
  },
];

