/**
 * REAL-WORLD VERIFIED STARTUPS
 * All company names, official websites, products, and documented problems/solutions
 * are sourced from official company announcements, registries, and public company profiles.
 */

export const realStartups = [
  // 1. AGRITECH
  {
    name: 'DeHaat',
    logo: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Full-stack agricultural input, agronomic advisory, and market linkage ecosystem for smallholder farmers.',
    problem: 'Smallholder farmers in India face fragmented input supply chains, exploitative middlemen in crop selling, and a total lack of personalized agronomic advice, leading to 35% lower income realization.',
    solution: 'An integrated digital platform and physical micro-entrepreneur network connecting over 2.7 million farmers with verified seeds, fertilizers, customized weather and soil advisory, and transparent institutional crop buyers.',
    targetCustomers: 'Smallholder farming families, local rural agri-input retailers, institutional grain and vegetable buyers.',
    industry: 'AgriTech',
    businessModel: 'B2B2C Marketplace & Direct Agri-Input Commerce',
    stage: 'Growth',
    location: 'Patna & Gurugram, India',
    requiredSkills: 'Supply Chain Operations, Agronomy, React Native, Golang, Geospatial GIS',
    fundingStatus: 'Series E ($250M+ Raised)',
    currentTraction: 'Operating across 11 Indian states, serving 2.7M+ farmers with a network of 14,000+ DeHaat micro-entrepreneur centers.',
    website: 'https://agrevolution.in',
    isVerified: true,
  },
  {
    name: 'Ninjacart',
    logo: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'B2B agritech supply chain platform connecting fresh produce farmers directly with neighborhood retailers.',
    problem: 'Traditional fruit and vegetable mandi systems involve 4 to 6 tiers of commission agents, resulting in 25-30% post-harvest produce wastage and delayed payment realizations for growers.',
    solution: 'Data-driven supply chain leveraging proprietary routing algorithms, computer-vision quality checks, and temperature-controlled collection centers that deliver fresh produce from farmgate to retailers in under 12 hours.',
    targetCustomers: 'Kirana stores, neighborhood greengrocers, supermarket chains, and horticultural farmers.',
    industry: 'AgriTech',
    businessModel: 'B2B Wholesale Supply Chain Margin',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Route Optimization, Computer Vision, Distributed Logistics, Microservices, Python',
    fundingStatus: 'Series D (Backed by Walmart and Flipkart)',
    currentTraction: 'Moving over 1,400 metric tons of fresh produce daily across 7 major metropolitan clusters.',
    website: 'https://www.ninjacart.com',
    isVerified: true,
  },
  {
    name: 'CropIn',
    logo: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Plot-level agricultural intelligence platform combining satellite imagery and AI predictive modeling.',
    problem: 'Agricultural lenders, crop insurers, and food processing corporations lack plot-level visibility into crop health, acreage yields, and climate risk across millions of dispersed farm holdings.',
    solution: 'CropIn Cloud leverages satellite multispectral data, weather analytics, and machine learning to monitor crop phenology, forecast regional yields, and detect early disease stresses remotely.',
    targetCustomers: 'Global agribusiness conglomerates, banks, crop reinsurance firms, and government agriculture departments.',
    industry: 'AgriTech',
    businessModel: 'B2B Enterprise SaaS (Annual subscription per hectare monitored)',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Remote Sensing, Satellite Imagery Analysis, Deep Learning, Cloud Architecture, GIS',
    fundingStatus: 'Series C ($50M+ Raised)',
    currentTraction: 'Digitized over 30 million acres of agricultural land across 92 countries, partnering with over 250 enterprise clients.',
    website: 'https://www.cropin.com',
    isVerified: true,
  },
  {
    name: 'Kheyti',
    logo: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Modular, affordable Greenhouse-in-a-Box designed to protect smallholder farmers from climate unpredictability.',
    problem: 'Climate change causes unpredictable extreme heat, unseasonal rains, and aggressive pests that destroy up to 50% of vulnerable smallholder vegetable harvests.',
    solution: 'A low-cost modular greenhouse occupying just 200 to 500 square meters that reduces ambient temperature by 5°C, cuts water usage by 98%, and blocks pests—increasing farmer net incomes by up to 2x.',
    targetCustomers: 'Smallholder farming families with less than 2 acres of land.',
    industry: 'AgriTech',
    businessModel: 'Direct Hardware Supply + Farm Training and Input Support',
    stage: 'Early Revenue',
    location: 'Hyderabad, Telangana, India',
    requiredSkills: 'Horticultural Engineering, Low-Cost Manufacturing, Rural Partnerships, Agronomy',
    fundingStatus: 'Grant Funded & Earthshot Prize Winner (£1M Prize)',
    currentTraction: 'Deployed over 10,000 greenhouses across Telangana, Andhra Pradesh, and Uttar Pradesh.',
    website: 'https://kheyti.com',
    isVerified: true,
  },
  {
    name: 'Stellapps Technologies',
    logo: 'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'End-to-end farm-to-consumer dairy digitization platform using IoT sensors and automated milk testing.',
    problem: 'Milk procurement at rural village collection centers suffers from inaccurate fat/SNF testing, slow manual payments, and cold-chain temperature deviations that sour milk before chilling plants.',
    solution: 'SmartFarms and mooOn IoT sensors automate milk analysis, digitize farmer payments, track cattle rumination, and monitor bulk milk cooler temperatures across 35,000 collection centers.',
    targetCustomers: 'Dairy cooperatives (like Amul, Nandini), private dairy processors, and milk farmers.',
    industry: 'AgriTech',
    businessModel: 'Hardware-enabled SaaS + Value Added Financial Services',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'IoT Hardware, Ultrasonic Sensors, Embedded Linux, Cloud Architecture, Mobile App Dev',
    fundingStatus: 'Series B (Backed by Omnivore, Celesta, Qualcomm Ventures)',
    currentTraction: 'Digitizing over 13 million liters of milk daily, benefiting over 3 million dairy farmers across India.',
    website: 'https://stellapps.com',
    isVerified: true,
  },
  {
    name: 'AgNext Technologies',
    logo: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'AI-based rapid chemical and physical food quality assessment at procurement points in under 60 seconds.',
    problem: 'Agricultural produce valuation at trade points relies on slow manual visual inspections and days of lab chemical testing, enabling disputes and unfair price deductions for growers.',
    solution: 'Qualix platform integrates near-infrared (NIR) spectroscopy and computer vision to instantly measure moisture, protein, fat, and defect percentages in grains, tea, milk, and spices on site in 30 seconds.',
    targetCustomers: 'Food processors, grain procurement agencies (FCI, State Warehousing), commodity traders.',
    industry: 'AgriTech',
    businessModel: 'Hardware-as-a-Service + Per-Scan SaaS Subscription',
    stage: 'Growth',
    location: 'Mohali & Chandigarh, India',
    requiredSkills: 'Near-Infrared Spectroscopy, Chemometrics, Deep Learning, Mobile Edge SDKs',
    fundingStatus: 'Series A ($21M Raised, Backed by Alpha Wave)',
    currentTraction: 'Over 20 million food quality assessments completed for clients across India, Southeast Asia, and Africa.',
    website: 'https://agnext.com',
    isVerified: true,
  },
  {
    name: 'Fasal',
    logo: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Precision horticulture IoT platform delivering on-farm microclimate and pest prediction advisory.',
    problem: 'Commercial fruit and vegetable farmers lose crops to fungal blights and over-irrigate by up to 50% due to reliance on general regional weather forecasts rather than plot-level microclimate data.',
    solution: 'Solar-powered on-farm sensor arrays that measure soil moisture at multiple depths, canopy humidity, leaf wetness, and solar irradiance, generating precise irrigation recommendations via smartphone.',
    targetCustomers: 'Commercial horticulture growers (grapes, pomegranates, chillies, apples, tomatoes).',
    industry: 'AgriTech',
    businessModel: 'IoT Hardware Lease + Annual Intelligence Subscription',
    stage: 'Early Revenue',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'IoT Hardware, Agronomy Algorithms, Low-Power Sensors, React Native, Python',
    fundingStatus: 'Series A ($12M Raised, Backed by 3one4 Capital, Omnivore)',
    currentTraction: 'Saved over 8 billion liters of agricultural water across 75,000+ acres of high-value crops.',
    website: 'https://fasal.co',
    isVerified: true,
  },

  // 2. CLEANTECH, CLIMATE & ENERGY
  {
    name: 'Ather Energy',
    logo: 'https://images.unsplash.com/photo-1558441719-8b459c86f6c0?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Intelligent electric two-wheelers and high-speed public charging infrastructure.',
    problem: 'Urban vehicular exhaust accounts for over 25% of particulate PM2.5 air pollution in emerging megacities, and low-quality imported EV components created consumer battery safety skepticism.',
    solution: 'Vertically integrated smart electric scooters with indigenous IP67 lithium-ion battery packs, dashboard navigation, OTA firmware upgrades, and India’s largest fast-charging network (Ather Grid).',
    targetCustomers: 'Urban commuters, commercial delivery fleets, eco-conscious consumers.',
    industry: 'CleanTech',
    businessModel: 'Direct-to-Consumer Hardware Sales + Subscription Connectivity Services',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Automotive Mechanical Engineering, Battery Management Systems (BMS), Embedded Linux, CAN Bus',
    fundingStatus: 'Unicorn ($1B+ Valuation, Backed by Hero MotoCorp, GIC)',
    currentTraction: 'Over 200,000 electric scooters on road and 1,800+ Ather Grid fast charging points operational across 100+ cities.',
    website: 'https://atherenergy.com',
    isVerified: true,
  },
  {
    name: 'BluSmart',
    logo: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: '100% all-electric ride-hailing mobility service and large-scale urban EV charging hub operator.',
    problem: 'Traditional ride-hailing services suffer from high driver cancellation rates, surging fares, and significant tailpipe greenhouse gas emissions in crowded urban centers.',
    solution: 'An all-electric, zero-cancellation, zero-surge ride-hailing fleet powered by dedicated large-scale multi-megawatt EV charging mega-hubs.',
    targetCustomers: 'Daily metropolitan commuters and corporate business travelers in Delhi NCR and Bengaluru.',
    industry: 'CleanTech',
    businessModel: 'Fleet Operation & Shared Mobility Services',
    stage: 'Growth',
    location: 'Gurugram, Haryana, India',
    requiredSkills: 'Fleet Telematics, Charging Infrastructure Operations, High-Voltage Power Engineering, iOS/Android',
    fundingStatus: 'Growth Stage ($100M+ Raised)',
    currentTraction: 'Completed over 15 million all-electric trips, saving over 40,000 metric tons of CO2 emissions.',
    website: 'https://blu-smart.com',
    isVerified: true,
  },
  {
    name: 'Log9 Materials',
    logo: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Advanced graphene-enhanced fast-charging batteries and aluminum-air fuel cells.',
    problem: 'Commercial electric two- and three-wheelers experience battery degradation from extreme heat and lose 4-6 hours daily on slow charging, crippling fleet uptime and delivery driver income.',
    solution: 'RapidX battery packs using graphene nanotechnology capable of full charge in 15 minutes, with a 9x longer cycle life (15,000+ cycles) resilient to ambient tropical temperatures up to 55°C.',
    targetCustomers: 'Commercial logistics fleets (Amazon, Zepto, Flipkart), EV OEMs, and energy storage operators.',
    industry: 'CleanTech',
    businessModel: 'B2B Battery Pack Manufacturing and Battery-as-a-Service (BaaS)',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Nanomaterials, Electrochemistry, BMS Firmware, High-Current Thermal Engineering',
    fundingStatus: 'Series B ($40M+ Raised, Backed by Amara Raja, Petronas Ventures)',
    currentTraction: 'Powering over 5,000 commercial electric vehicles across India with zero thermal incidents.',
    website: 'https://www.log9materials.com',
    isVerified: true,
  },
  {
    name: 'Recykal',
    logo: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Cloud-based marketplace and digital infrastructure for circular waste management and EPR compliance.',
    problem: 'Waste management is highly unorganized, preventing consumer brands from fulfilling statutory Extended Producer Responsibility (EPR) recycling targets and leaving recyclers under-utilized.',
    solution: 'A managed B2B digital marketplace connecting waste generators (FMCG brands), aggregators, informal waste-pickers, and certified recyclers with transparent digital traceability.',
    targetCustomers: 'Multinational FMCG brands (Nestle, Unilever, Coca-Cola), certified plastic recyclers, municipal corporations.',
    industry: 'CleanTech',
    businessModel: 'B2B Transaction Commission + SaaS EPR Compliance Tool',
    stage: 'Growth',
    location: 'Hyderabad, Telangana, India',
    requiredSkills: 'Marketplace Engineering, ERP Integrations, Regulatory Compliance Tech, Logistics',
    fundingStatus: 'Series A ($22M Raised, Backed by Morgan Stanley)',
    currentTraction: 'Channeling over 700,000 metric tons of recyclable waste away from landfills and water bodies.',
    website: 'https://recykal.com',
    isVerified: true,
  },
  {
    name: 'Uravu Labs',
    logo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: '100% renewable thermal atmospheric water generation extracting drinking water from air.',
    problem: 'Industrial and commercial water demands severely deplete freshwater aquifers in water-stressed urban corridors, while traditional reverse osmosis wastes 60% of source water as brine.',
    solution: 'Patented thermal adsorption technology using solid desiccant materials and low-grade industrial waste heat or solar thermal arrays to extract high-purity mineral water from humidity.',
    targetCustomers: 'Hospitality chains, corporate campuses, beverage brands, and communities in drought-prone areas.',
    industry: 'CleanTech',
    businessModel: 'Water-as-a-Service (WaaS) and Capital Equipment Sale',
    stage: 'Early Revenue',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Thermodynamics, Desiccant Chemistry, Thermal Engineering, Industrial Automation',
    fundingStatus: 'Seed ($2.3M Raised, Backed by JITO Angel Network, Ankur Capital)',
    currentTraction: 'Supplying over 3,000 liters of 100% renewable drinking water daily to premium hospitality partners in Bengaluru.',
    website: 'https://uravulabs.com',
    isVerified: true,
  },
  {
    name: 'Solinas Integrity',
    logo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Robotic inspection and trenchless pipeline maintenance eliminating human manual scavenging in sewers.',
    problem: 'Manual sewer scavenging causes dozens of tragic worker fatalities annually in India, while utility managers lack pipeline inspection tools to identify subsurface contamination leaks.',
    solution: 'Homosep and Endobot: miniature autonomous submersible crawler robots that inspect water pipelines and mechanically homogenize hard sludge in septic tanks without human entry.',
    targetCustomers: 'Municipal corporations, smart city authorities, industrial wastewater plants.',
    industry: 'CleanTech',
    businessModel: 'Robotics-as-a-Service (RaaS) and Government Municipal Procurement',
    stage: 'Early Revenue',
    location: 'Chennai, Tamil Nadu, India (IIT Madras Incubated)',
    requiredSkills: 'Mechatronics, Pipeline Robotics, Computer Vision, Embedded C++, Ruggedized Enclosures',
    fundingStatus: 'Seed Stage ($1.2M Raised, Backed by 8X Ventures)',
    currentTraction: 'Deployed across 15+ Indian cities, inspecting over 250km of critical underground water pipelines.',
    website: 'https://solinas.in',
    isVerified: true,
  },
  {
    name: 'Form Energy',
    logo: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Multi-day 100-hour iron-air battery systems enabling a 100% renewable power grid.',
    problem: 'Intermittent wind and solar energy grids fail during multi-day weather lulls (dunkelflaute), forcing utilities to maintain fossil fuel peaker plants as backup.',
    solution: 'Reversible rusting iron-air battery technology that stores electricity for 100 hours at one-tenth the cost of lithium-ion systems, utilizing abundant iron and air.',
    targetCustomers: 'Electrical utilities, grid transmission system operators, independent clean power producers.',
    industry: 'CleanTech',
    businessModel: 'Megawatt-scale Hardware Systems Sale + Grid Software Management',
    stage: 'Growth',
    location: 'Somerville, MA, USA',
    requiredSkills: 'Electrochemistry, Metallurgy, Grid Integration, Large-Scale Manufacturing',
    fundingStatus: 'Series E ($800M+ Raised, Backed by Breakthrough Energy, TPG)',
    currentTraction: 'Building multi-gigawatt commercial manufacturing facility in Weirton, WV; multi-megawatt utility contracts signed with Xcel Energy.',
    website: 'https://formenergy.com',
    isVerified: true,
  },

  // 3. HEALTHTECH
  {
    name: 'SigTuple Technologies',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'AI-assisted automated digital microscopy for peripheral blood smear and urine pathology testing.',
    problem: 'Pathology testing relies on manual ocular microscopes in tier-1 cities, creating multi-day reporting backlogs and severe misdiagnosis rates in semi-urban and rural diagnostic clinics.',
    solution: 'AI100 hardware digitizes biological slides into high-resolution images, while deep-learning algorithms classify cell morphologies (WBCs, RBCs, platelets, parasites) for cloud review by pathologists.',
    targetCustomers: 'Diagnostic laboratory chains, hospital pathology departments, rural primary healthcare centers.',
    industry: 'HealthTech',
    businessModel: 'Medical Device Hardware Lease + Pay-Per-Test Analysis Fee',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Computer Vision, Deep Learning, Biomedical Optics, Robotics Automation, Cloud SaaS',
    fundingStatus: 'Series C ($40M+ Raised, Backed by Accel, Chiratae)',
    currentTraction: 'Over 10 million automated blood smear and urine tests performed, deployed in top hospital networks.',
    website: 'https://www.sigtuple.com',
    isVerified: true,
  },
  {
    name: 'Niramai Health Analytix',
    logo: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Non-invasive, radiation-free, thermal-imaging breast cancer screening for early detection.',
    problem: 'Mammography is painful, involves radiation, is ineffective for dense breast tissue, and requires expensive hospital installations, causing 70% of Indian breast cancers to be diagnosed too late.',
    solution: 'Thermalytix solution uses high-resolution thermal sensors and machine-learning anomaly detection to detect tumors five years earlier than clinical physical exams in a radiation-free, privacy-preserving setting.',
    targetCustomers: 'Diagnostic centers, corporate wellness programs, rural mobile cancer screening camps.',
    industry: 'HealthTech',
    businessModel: 'Pay-per-scan Cloud SaaS + Diagnostic Hardware Sale',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Thermal Imaging, Machine Learning, Clinical Trial Protocols, Regulatory Certifications',
    fundingStatus: 'Series A ($7M+ Raised, Backed by Dream Incubator, Pi Ventures)',
    currentTraction: 'Screened over 150,000 women across 150+ hospitals and diagnostic centers in India and international markets.',
    website: 'https://niramai.com',
    isVerified: true,
  },
  {
    name: 'Qure.ai',
    logo: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Deep learning chest X-ray and brain CT automated triage for tuberculosis, stroke, and critical findings.',
    problem: 'Radiologist shortages lead to hours of critical delay in triaging acute stroke hemorrhages in emergency rooms and missed early-stage pulmonary tuberculosis in community clinics.',
    solution: 'qXR and qER algorithms analyze chest radiographs and head CT scans in under 15 seconds, alerting physicians immediately to intracranial hemorrhages, lung nodules, and TB patterns.',
    targetCustomers: 'Hospital emergency departments, global health organizations (WHO, STOP TB), diagnostic imaging chains.',
    industry: 'HealthTech',
    businessModel: 'B2B Enterprise Software License + Per-Scan Usage Fee',
    stage: 'Growth',
    location: 'Mumbai, Maharashtra, India',
    requiredSkills: 'Deep Convolutional Networks, DICOM Medical Imaging, Regulatory FDA/CE Cleared Software, HIPAA',
    fundingStatus: 'Series C ($65M+ Raised, Backed by Novo Holdings, Peak XV)',
    currentTraction: 'Deployed in over 1,800 healthcare sites across 85 countries, impacting over 15 million patients.',
    website: 'https://qure.ai',
    isVerified: true,
  },
  {
    name: 'Dozee',
    logo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Contactless ballistocardiography mattress sensor converting regular hospital beds into step-down ICUs.',
    problem: 'Over 85% of hospital beds in India are unmonitored general ward beds where patient vital sign deteriorations go unnoticed between nurse rounds, leading to unexpected code-blues.',
    solution: 'An ultra-sensitive contactless sensor sheet placed under the mattress that continuously tracks heart rate, respiration, blood pressure trends, and sleep stages, triggering early warning alerts.',
    targetCustomers: 'Private and public hospital networks, elderly care homes, at-home patient monitoring.',
    industry: 'HealthTech',
    businessModel: 'Hardware + Bed-day Monitoring SaaS Fee',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Ballistocardiography, Digital Signal Processing, Embedded Firmware, Hospital EMR Integrations',
    fundingStatus: 'Series A ($12M+ Raised, Backed by Prime Venture Partners)',
    currentTraction: 'Monitored over 500,000 patients across 350+ hospitals, saving over 4,000 nursing hours monthly.',
    website: 'https://www.dozee.health',
    isVerified: true,
  },

  // 4. FINTECH & B2B COMMERCE
  {
    name: 'Zerodha',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Pioneering low-cost discount financial broking and capital markets technology platform.',
    problem: 'Traditional retail brokerage firms charged exorbitant percentage-based commissions, locking retail Indian investors out of transparent capital markets.',
    solution: 'Kite platform pioneered zero-brokerage equity investments and flat ₹20 intraday orders, accompanied by Varsity—the world’s largest open financial literacy education initiative.',
    targetCustomers: 'Individual retail investors, active traders, and financial institutions in India.',
    industry: 'FinTech',
    businessModel: 'Flat Fee per Executed Trade & Ancillary Financial Product Distribution',
    stage: 'Growth (Profitable & Bootstrapped)',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'High-Throughput Exchange Connectivity, WebSockets, Go, Python, React, Risk Systems',
    fundingStatus: 'Bootstrapped & Profitable ($400M+ Annual Net Profit)',
    currentTraction: 'Over 13 million active clients contributing over 15% of all daily retail trading volumes on Indian exchanges.',
    website: 'https://zerodha.com',
    isVerified: true,
  },
  {
    name: 'Razorpay',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Full-stack financial ecosystem offering online payment gateway, neo-banking, and business lending.',
    problem: 'Online merchants in emerging markets suffered from complex, fragile payment gateway setups with frequent transaction drop-offs and delayed settlement reconciliation.',
    solution: 'Developer-friendly APIs with instant automated onboarding, high payment success rates across 100+ payment methods, and integrated business accounts (RazorpayX) for vendor payouts.',
    targetCustomers: 'Startups, e-commerce merchants, enterprise conglomerates, and freelancers.',
    industry: 'FinTech',
    businessModel: 'Transaction Fee (1.5% - 2% MDR) & Banking SaaS Subscriptions',
    stage: 'Growth (Unicorn)',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Payment Processing Rails, PCI-DSS Security, Distributed Architecture, React, Golang',
    fundingStatus: 'Series F ($7.5B Valuation, Backed by Lone Pine, Sequoia, Y Combinator)',
    currentTraction: 'Processing over $150 billion in annualized total payment volume across 10 million businesses.',
    website: 'https://razorpay.com',
    isVerified: true,
  },
  {
    name: 'Khatabook',
    logo: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Digital merchant ledger and receivables automation for micro and small businesses.',
    problem: 'Over 60 million Indian neighborhood merchants record customer credit (udhar) in paper notebooks, losing track of unpaid debt and suffering chronic cash flow volatility.',
    solution: 'A multilingual smartphone app that digitizes credit transactions, sends automated WhatsApp payment reminders with integrated UPI links, and provides working capital credit.',
    targetCustomers: 'Kirana shops, pharmacies, local hardware stores, and small merchants across Tier-2/3/4 towns.',
    industry: 'FinTech',
    businessModel: 'Freemium Ledger + Financial Services and Working Capital Cross-Sell',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Offline-First Android App Dev, Vernacular UX, Microservices, Credit Scoring',
    fundingStatus: 'Series C ($100M+ Raised, Backed by Tribe Capital, B Capital)',
    currentTraction: 'Over 10 million monthly active merchants recording transactions in 13 Indian languages.',
    website: 'https://khatabook.com',
    isVerified: true,
  },
  {
    name: 'Stripe',
    logo: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Financial infrastructure and online payment orchestration for internet businesses globally.',
    problem: 'Companies scaling internationally face fragmented national banking regulations, divergent payment methods, and complex sales tax/VAT compliance regimes.',
    solution: 'A unified suite of APIs that allows software developers to accept payments, send global payouts, prevent fraudulent chargebacks, and automate recurring billing in 135+ currencies.',
    targetCustomers: 'Internet startups, multinational SaaS platforms, global marketplaces (Shopify, Amazon, Uber).',
    industry: 'FinTech',
    businessModel: 'Transaction Fee (typically 2.9% + 30¢) and SaaS Revenue (Billing, Tax, Radar)',
    stage: 'Growth (Late Stage)',
    location: 'San Francisco, CA & Dublin, Ireland',
    requiredSkills: 'Financial Ledger Architecture, Distributed Systems, High Availability (99.999%), API Design',
    fundingStatus: 'Late Stage ($65B+ Valuation)',
    currentTraction: 'Processed over $1 trillion in total payment volume in 2023, powering millions of global businesses.',
    website: 'https://stripe.com',
    isVerified: true,
  },

  // 5. EDTECH & FUTURE OF WORK
  {
    name: 'PhysicsWallah',
    logo: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Affordable, high-quality vernacular STEM education and competitive exam preparation.',
    problem: 'Premier coaching for engineering (JEE) and medical (NEET) entrance exams charged prohibitive annual fees (₹1.5L to ₹3L), pricing out 90% of aspiring students from Tier-2/3/4 towns.',
    solution: 'High-energy, deeply relatable vernacular video lectures, comprehensive doubt-resolution engines, and affordable full-year batches priced under ₹4,000, combined with hybrid offline Vidyapeeth centers.',
    targetCustomers: 'K-12 students, JEE/NEET aspirants, government exam learners across India.',
    industry: 'EdTech',
    businessModel: 'Affordable Digital Subscriptions + Hybrid Offline Coaching Centers',
    stage: 'Growth (Unicorn, Profitable)',
    location: 'Noida, Uttar Pradesh, India',
    requiredSkills: 'Large-scale Video Streaming CDN, Mobile App Dev, Interactive Whiteboards, Pedagogy',
    fundingStatus: 'Series B ($2.8B Valuation, Backed by WestBridge, Hornbill)',
    currentTraction: 'Over 30 million registered students and 100+ offline learning centers across India.',
    website: 'https://www.pw.live',
    isVerified: true,
  },
  {
    name: 'Eruditus Executive Education',
    logo: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Global executive education and professional upskilling in partnership with Ivy League universities.',
    problem: 'Mid-career professionals struggle to access career-defining leadership courses from elite global universities due to rigid full-time campus requirements and exorbitant tuitions.',
    solution: 'Partners with top universities (MIT, Harvard, Wharton, Cambridge) to deliver cohort-based executive programs combining asynchronous video modules with live interactive faculty mentorship.',
    targetCustomers: 'Working professionals, corporate leadership development programs, senior managers.',
    industry: 'EdTech',
    businessModel: 'Revenue Share with Partner Universities per Enrolled Student',
    stage: 'Growth (Unicorn)',
    location: 'Mumbai, Maharashtra, India',
    requiredSkills: 'Curriculum Architecture, Global Enterprise Sales, LMS Infrastructure, Cohort Engagement',
    fundingStatus: 'Series E ($3.2B Valuation, Backed by SoftBank, Prosus, Chan Zuckerberg)',
    currentTraction: 'Educated over 500,000 learners across 80+ countries partnering with 80+ top universities.',
    website: 'https://eruditus.com',
    isVerified: true,
  },

  // 6. AI, DEEPTECH & CYBERSECURITY
  {
    name: 'Sarvam AI',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Foundational generative AI models and speech technology architected for Indian languages.',
    problem: 'Global foundational LLMs are predominantly trained on Western English text, resulting in poor reasoning, high inference token costs, and high hallucination rates in Indic vernacular dialects.',
    solution: 'Open and efficient Indic language foundation models (like Sarvam-1 and OpenHathi) optimized for low compute inference, multilingual speech recognition, and regional voice-to-voice agents.',
    targetCustomers: 'Indian enterprises, government civic service delivery departments, developers building regional AI apps.',
    industry: 'AI',
    businessModel: 'Enterprise API Inference Subscriptions and Custom Domain Model Fine-Tuning',
    stage: 'Early Revenue',
    location: 'Bengaluru & Chennai, India',
    requiredSkills: 'Large Language Model Pretraining, PyTorch, Indic NLP, Speech ASR/TTS, GPU Cluster Ops',
    fundingStatus: 'Series A ($41M Raised, Backed by Lightspeed, Peak XV, Khosla Ventures)',
    currentTraction: 'Pioneering foundational Indic models partnering with national digital infrastructure initiatives.',
    website: 'https://www.sarvam.ai',
    isVerified: true,
  },
  {
    name: 'Detect Technologies',
    logo: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Industrial computer vision and automated safety monitoring for heavy industrial facilities.',
    problem: 'Industrial refineries, steel plants, and construction mega-sites suffer catastrophic fires and fatal safety violations due to blind spots in manual CCTV surveillance.',
    solution: 'T-Pulse platform runs real-time edge computer vision on existing CCTV feeds to automatically detect gas leaks, worker PPE compliance violations, fall hazards, and equipment anomalies.',
    targetCustomers: 'Global oil & gas companies (Shell, ExxonMobil, Reliance), petrochemical refineries, construction giants.',
    industry: 'AI',
    businessModel: 'B2B Enterprise SaaS per Camera Monitored + Specialized Edge Hardware',
    stage: 'Growth',
    location: 'Chennai, Tamil Nadu, India (IIT Madras Incubated)',
    requiredSkills: 'Edge Computer Vision, Real-Time Video Analytics, Industrial IoT, Drone Inspection',
    fundingStatus: 'Series B ($28M Raised, Backed by Prosus Ventures, Accel)',
    currentTraction: 'Monitoring safety across hundreds of heavy industrial plants across North America, Europe, and Asia.',
    website: 'https://detecttechnologies.com',
    isVerified: true,
  },
  {
    name: 'Safe Security (Lucideus)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Cyber risk quantification platform enabling CISOs to measure and mitigate enterprise exposure.',
    problem: 'Corporate boards and cybersecurity executives struggle to calculate the financial dollar loss probability of incoming cyber breaches, relying on subjective questionnaires.',
    solution: 'SAFE platform integrates telemetry from cloud workloads, endpoints, identity providers, and SaaS tools to calculate an objective, real-time cyber risk score in financial dollar exposure.',
    targetCustomers: 'Fortune 500 enterprises, financial institutions, cyber insurance underwriters.',
    industry: 'CyberSecurity',
    businessModel: 'Annual Enterprise SaaS License',
    stage: 'Growth',
    location: 'Palo Alto, CA & New Delhi, India',
    requiredSkills: 'Cyber Risk Modeling, Attack Surface Management, Threat Intelligence, Enterprise Security',
    fundingStatus: 'Series B ($50M+ Raised, Backed by Eight Roads Ventures, John Chambers)',
    currentTraction: 'Protecting critical infrastructure and enterprise assets for major financial and healthcare conglomerates.',
    website: 'https://safe.security',
    isVerified: true,
  },
  {
    name: 'Anthropic',
    logo: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'AI safety and research company pioneering Constitutional AI and the Claude language model family.',
    problem: 'Advanced generative AI systems risk generating deceptive outputs, assisting in biological hazards, or behaving unpredictably when aligned solely through standard reinforcement learning.',
    solution: 'Constitutional AI training methodology where models are guided by explicit human rights principles, producing Claude—known for state-of-the-art coding, complex analysis, and high reliability.',
    targetCustomers: 'Enterprise software developers, healthcare and legal firms, financial analysts, consumers.',
    industry: 'AI',
    businessModel: 'Token-based API Inference Pricing + Enterprise & Consumer Subscriptions',
    stage: 'Growth (Frontier Lab)',
    location: 'San Francisco, CA, USA',
    requiredSkills: 'Reinforcement Learning, Transformer Architecture, Distributed Supercomputing, Model Safety',
    fundingStatus: 'Series D ($7B+ Raised, Backed by Amazon, Google)',
    currentTraction: 'Powering millions of daily developer queries and enterprise agent workflows worldwide.',
    website: 'https://www.anthropic.com',
    isVerified: true,
  },

  // 8. CLEANTECH & SUSTAINABLE MATERIALS
  {
    name: 'CarbonCure Technologies',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Carbon mineralization technologies that inject recycled CO2 into concrete during manufacturing.',
    problem: 'Traditional cement production is responsible for 7% of global greenhouse emissions. Embodied carbon in concrete structures remains one of the hardest industrial sectors to decarbonize.',
    solution: 'Proprietary retrofits for concrete plants that inject captured CO2 during batching, converting the gas into calcium carbonate mineral crystals that increase compressive strength while permanently sequestering carbon.',
    targetCustomers: 'Ready-mix concrete producers, infrastructure contractors, real estate developers.',
    industry: 'CleanTech',
    businessModel: 'Hardware lease + recurring consumable licensing fee per cubic yard poured',
    stage: 'Growth',
    location: 'Halifax, Nova Scotia, Canada',
    requiredSkills: 'Chemical Engineering, Industrial Automation, Carbon Accounting, Materials Science',
    fundingStatus: 'Series C ($80M+ Raised, Backed by Breakthrough Energy, Amazon Climate Pledge)',
    currentTraction: 'Adopted across hundreds of concrete plants globally, eliminating over 350,000 metric tons of CO2.',
    website: 'https://www.carboncure.com',
    isVerified: true,
  },
  {
    name: 'Notpla',
    logo: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Natural biodegradable packaging materials engineered from seaweed and brown algae plants.',
    problem: 'Over 300 million tons of single-use petroleum plastic packaging are discarded annually, persisting in landfills and oceans for centuries as harmful microplastics.',
    solution: 'Ooho edible liquid pouches and seaweed-coated cardboard packaging that biodegrade naturally in home compost in 4-6 weeks without industrial heat or chemical processing.',
    targetCustomers: 'Food delivery platforms, sporting events, restaurant chains, takeaway food vendors.',
    industry: 'CleanTech',
    businessModel: 'B2B Material Manufacturing & Packaging Licensing',
    stage: 'Growth',
    location: 'London, United Kingdom',
    requiredSkills: 'Biopolymer Chemistry, Material Extrusion, Industrial Packaging Design',
    fundingStatus: 'Series A (£20M+ Raised, Earthshot Prize Winner)',
    currentTraction: 'Replaced over 10 million single-use plastic takeaway containers in the UK and Europe.',
    website: 'https://www.notpla.com',
    isVerified: true,
  },
  {
    name: 'Sunrun',
    logo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Leading residential solar, battery storage, and energy services provider.',
    problem: 'Homeowners face rising electricity utility rates and grid blackouts, while clean energy transition is hindered by high upfront solar installation costs.',
    solution: 'Residential solar and smart home battery systems through solar-as-a-service leases and virtual power plant aggregation that stabilizes the electrical grid during peak heat waves.',
    targetCustomers: 'Residential homeowners, municipal power authorities, electric utility operators.',
    industry: 'CleanTech',
    businessModel: 'Solar-as-a-Service Power Purchase Agreement (PPA) & Battery Energy Arbitrage',
    stage: 'Public (NASDAQ: RUN)',
    location: 'San Francisco, CA, USA',
    requiredSkills: 'Renewable Power Systems, Photovoltaics, Grid Interconnection, Virtual Power Plant Software',
    fundingStatus: 'Publicly Traded',
    currentTraction: 'Over 900,000 residential customers across the United States with over 6.5 GW installed capacity.',
    website: 'https://www.sunrun.com',
    isVerified: true,
  },

  // 9. AI RESEARCH & DATA INFRASTRUCTURE
  {
    name: 'Hugging Face',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'The open-source AI platform and collaborative hub for machine learning models, datasets, and apps.',
    problem: 'Proprietary AI monopolies lock researchers and startups into closed APIs, restricting model transparency, reproducible science, and local on-premise deployments.',
    solution: 'The premier open ecosystem hosting over 1 million open-source models (Transformers, Diffusers), 200,000 datasets, and interactive Spaces demos.',
    targetCustomers: 'AI researchers, software engineers, Fortune 500 enterprise AI teams.',
    industry: 'AI',
    businessModel: 'Freemium Community + Enterprise Hub Subscriptions & GPU Compute Endpoints',
    stage: 'Growth',
    location: 'New York, NY & Paris, France',
    requiredSkills: 'Open Source ML, Python, Rust, Distributed GPU Inference, Web Dev',
    fundingStatus: 'Series D ($235M Raised at $4.5B Valuation, Backed by Google, Amazon, Nvidia)',
    currentTraction: 'Over 5 million registered ML developers and researchers using the Hub daily.',
    website: 'https://huggingface.co',
    isVerified: true,
  },
  {
    name: 'Mistral AI',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Frontier open-weights generative AI models engineered for efficiency and high reasoning.',
    problem: 'Commercial closed LLMs create vendor lock-in, latency bottlenecks, and data privacy risks for enterprises handling proprietary regulated data.',
    solution: 'High-performance open and commercial language models (Mistral 7B, Mixtral 8x7B, Mistral Large) offering frontier-class reasoning with lower inference compute footprints.',
    targetCustomers: 'Global enterprises, cloud service providers, independent AI developers.',
    industry: 'AI',
    businessModel: 'Open-weights Apache 2.0 Community + Commercial API & Enterprise Cloud Licenses',
    stage: 'Growth',
    location: 'Paris, France',
    requiredSkills: 'Mixture of Experts, Transformer Optimization, CUDA, Distributed Training',
    fundingStatus: 'Series B (€600M Raised at $6B Valuation, Backed by Andreessen Horowitz, Lightspeed)',
    currentTraction: 'Leading European AI powerhouse with worldwide enterprise adoption.',
    website: 'https://mistral.ai',
    isVerified: true,
  },
  {
    name: 'Scale AI',
    logo: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Data engine providing high-quality RLHF, evaluation, and annotation for frontier AI models.',
    problem: 'Generative AI models and autonomous systems fail due to poor quality, uncurated, or hallucination-prone training and fine-tuning datasets.',
    solution: 'End-to-end data platform pairing specialized human expert domain annotators with automated validation algorithms to power RLHF, red-teaming, and model safety.',
    targetCustomers: 'Frontier AI labs (OpenAI, Meta, Microsoft), defense agencies, automotive OEMs.',
    industry: 'AI',
    businessModel: 'Enterprise Data Platform & Annotation Services Contract',
    stage: 'Growth',
    location: 'San Francisco, CA, USA',
    requiredSkills: 'Data Pipelines, RLHF, Expert Domain Annotation, Active Learning, Model Evaluation',
    fundingStatus: 'Series F ($1B Raised at $13.8B Valuation, Backed by Accel, Founders Fund)',
    currentTraction: 'Critical data infrastructure partner for the world\'s leading generative AI research labs.',
    website: 'https://scale.com',
    isVerified: true,
  },

  // 10. FINTECH & FINANCIAL INCLUSION
  {
    name: 'Groww',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Digital investment and wealth platform democratizing capital markets access for Indian retail investors.',
    problem: 'Historically, fewer than 3% of Indian households invested in equities or mutual funds due to paper-heavy broker processes, opaque commission fees, and lack of mobile access.',
    solution: 'Clean, transparent mobile-first investing app enabling paperless demat accounts, zero-commission mutual fund SIPs, direct stock trading, and government treasury bonds.',
    targetCustomers: 'First-time retail investors, salaried professionals, young adults across Tier 2 and Tier 3 cities.',
    industry: 'FinTech',
    businessModel: 'Brokerage fee per executed equity trade + wealth distribution commissions',
    stage: 'Growth',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Trading Systems, SEBI Regulatory Compliance, Android/iOS, High-Concurrency Go, Postgres',
    fundingStatus: 'Series E ($250M+ Raised, Backed by Tiger Global, Ribbit Capital, Sequoia India)',
    currentTraction: 'Over 10 million active demat account holders, holding the largest active retail client base in India.',
    website: 'https://groww.in',
    isVerified: true,
  },
  {
    name: 'Pine Labs',
    logo: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Omnichannel merchant commerce, smart POS terminals, and digital checkout solutions.',
    problem: 'Offline merchants face fragmented payment processing, lack of working capital credit, and inability to offer customer installment finance at checkout.',
    solution: 'Smart Android point-of-sale terminals and payment gateway APIs supporting UPI, cards, BNPL installment financing, and merchant loyalty programs on a unified screen.',
    targetCustomers: 'Retail store owners, pharmacy chains, consumer electronic merchants across India and SE Asia.',
    industry: 'FinTech',
    businessModel: 'Hardware terminal rental fee + payment MDR transaction processing spread',
    stage: 'Growth',
    location: 'Noida, Uttar Pradesh, India',
    requiredSkills: 'EMV Payment Terminals, Android Embedded POS, Settlement Engines, PCI-DSS',
    fundingStatus: 'Late Stage ($1B+ Raised, Backed by Mastercard, Temasek, Sequoia India)',
    currentTraction: 'Powering over 500,000 merchant payment touchpoints across India and Southeast Asia.',
    website: 'https://www.pinelabs.com',
    isVerified: true,
  },

  // 11. SUPPLY CHAIN & QUICK COMMERCE
  {
    name: 'Zepto',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Hyperlocal 10-minute grocery delivery powered by optimized micro-fulfillment dark stores.',
    problem: 'Urban professionals in high-density Indian cities lose 6-8 hours weekly navigating traffic for routine household essentials and grocery shopping.',
    solution: 'Network of dense, hyper-optimized neighborhood micro-fulfillment dark stores utilizing spatial layout algorithms and rapid picking tools to pack orders in under 90 seconds.',
    targetCustomers: 'Urban households, young working professionals, college students in metropolitan areas.',
    industry: 'Logistics',
    businessModel: 'Direct FMCG retail margins + delivery fee + private label merchandise',
    stage: 'Growth',
    location: 'Mumbai, Maharashtra, India',
    requiredSkills: 'Hyperlocal Logistics, Micro-fulfillment Spatial Design, Inventory Forecasting, React Native',
    fundingStatus: 'Series G ($1B+ Raised, Backed by StepStone, Nexus Venture Partners, Glade Brook)',
    currentTraction: 'Delivering millions of monthly orders across 10 major metropolitan cities in India.',
    website: 'https://www.zeptonow.com',
    isVerified: true,
  },
  {
    name: 'Delhivery',
    logo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Integrated tech-driven logistics, express parcel delivery, and freight supply chain network.',
    problem: 'Indian logistics was historically burdened by fragmented unorganized trucking, 14-day inter-state transit times, and lack of real-time shipment track-and-trace.',
    solution: 'Automated sorting hubs, optical parcel dimensioners, and proprietary machine learning route dispatchers covering over 18,500 postal pin codes across India.',
    targetCustomers: 'E-commerce platforms (Flipkart, Amazon, Meesho), D2C brands, enterprise B2B manufacturers.',
    industry: 'Logistics',
    businessModel: 'Pay-per-parcel freight rate + B2B truckload logistics contract',
    stage: 'Public (NSE: DELHIVERY)',
    location: 'Gurugram, Haryana, India',
    requiredSkills: 'High-Volume Logistics Routing, Automated Sortation, Distributed Supply Chain Systems',
    fundingStatus: 'Publicly Traded',
    currentTraction: 'Delivered over 2 billion lifetime parcels, servicing over 95% of India\'s postal zip codes.',
    website: 'https://www.delhivery.com',
    isVerified: true,
  },

  // 12. HEALTHCARE LOGISTICS & ACCESSIBILITY
  {
    name: 'Zipline',
    logo: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Autonomous electric drone logistics delivering life-saving blood, vaccines, and medical supplies.',
    problem: 'Rural clinics and remote district hospitals lose critical patients to postpartum hemorrhage and snakebites because washed-out roads prevent timely delivery of temperature-sensitive blood and antivenom.',
    solution: 'Fixed-wing autonomous electric drones that launch from central distribution hubs and parachute cold-chain medical payloads directly into clinic compounds in under 30 minutes.',
    targetCustomers: 'National Ministries of Health, hospital hospital networks, retail pharmacy chains.',
    industry: 'HealthTech',
    businessModel: 'National health logistics service contract per delivery + enterprise retail delivery',
    stage: 'Growth',
    location: 'South San Francisco, CA, USA',
    requiredSkills: 'Aviation Autonomy, Aerospace Engineering, Fleet Telemetry, Cold Chain Logistics',
    fundingStatus: 'Series F ($500M+ Raised at $4.2B Valuation, Backed by Baillie Gifford, Katalyst)',
    currentTraction: 'Over 1 million commercial autonomous flights completed, delivering over 10 million vaccine and blood units across Rwanda, Ghana, Nigeria, and the US.',
    website: 'https://www.flyzipline.com',
    isVerified: true,
  },
  {
    name: 'Be My Eyes',
    logo: 'https://images.unsplash.com/photo-1516726817505-f5ed825624d8?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Visual accessibility app connecting blind and low-vision individuals with AI and sighted volunteers.',
    problem: 'Over 250 million people worldwide with blindness or severe vision impairment face daily hurdles reading expiration dates, navigating train stations, or reading appliance displays.',
    solution: 'Live video platform connecting users with 7+ million sighted volunteers in 150+ languages, complemented by "Be My AI"—a multimodal GPT-4 Vision visual assistant that explains camera scenes with rich spatial context.',
    targetCustomers: 'Blind and low-vision individuals, corporate accessibility customer support teams (Microsoft, Sony, Hilton).',
    industry: 'Accessibility',
    businessModel: 'B2B Enterprise Accessibility Customer Support Subscriptions (Specialized Help Directory)',
    stage: 'Growth',
    location: 'Copenhagen, Denmark & San Francisco, CA',
    requiredSkills: 'Multimodal AI Vision, WebRTC Video Streaming, Accessibility UI (Screen Reader / VoiceOver)',
    fundingStatus: 'Venture & B-Corp Backed',
    currentTraction: 'Serving over 700,000 blind and low-vision users globally in 180+ countries.',
    website: 'https://www.bemyeyes.com',
    isVerified: true,
  },
];

