export const additionalSeedUsers = [
  // CO-FOUNDERS / DEVELOPERS / DESIGNERS / MARKETERS
  {
    email: 'julian.vance@aihealth.co',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Julian Vance',
      headline: 'Bioinformatics & ML Engineer | Python, PyTorch, Genomics',
      location: 'Boston, MA, USA',
      bio: 'Applying transformers to single-cell RNA sequencing and variant annotation. Looking to team up with bio founders.',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      education: 'MIT (BS Biological Engineering & CS)',
      skills: 'Python, PyTorch, Bioinformatics, Nextflow, Cloud Computing, Docker',
      startupInterests: 'BioTech, HealthTech, Genomics, AI Medicine',
      industries: 'Health & Disease, Technology & Innovation',
      preferredRole: 'Founding ML Engineer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 80,
    },
  },
  {
    email: 'meera.nair@uxcraft.design',
    role: 'DESIGNER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Meera Nair',
      headline: 'Lead UX Researcher & Product Designer | Fintech & Climate Design',
      location: 'Hyderabad, Telangana, India',
      bio: 'Conducted 200+ field interviews across rural cooperatives and tier-2 towns. Specializing in designing for next-billion users.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      education: 'IIT Guwahati (B.Des)',
      skills: 'User Research, Ethnography, Figma, Rapid Prototyping, Accessibility',
      startupInterests: 'FinTech, AgriTech, EdTech, ClimateTech',
      industries: 'FinTech, Design Tools',
      preferredRole: 'Head of Product Design',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 85,
    },
  },
  {
    email: 'alex.becker@devops.de',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Alex Becker',
      headline: 'Platform & Security Engineer | Rust, Go, Kubernetes, Zero-Trust',
      location: 'Berlin, Germany',
      bio: 'Obsessed with high-availability systems, eBPF telemetry, and hardening containerized workloads.',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
      education: 'TU Munich (BSc Informatics)',
      skills: 'Rust, Go, Kubernetes, eBPF, Terraform, CyberSecurity, CI/CD',
      startupInterests: 'CyberSecurity, Cloud, DevTools, Infrastructure',
      industries: 'Technology & Innovation, Business & Commerce',
      preferredRole: 'Lead Security Engineer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 75,
    },
  },
  {
    email: 'jinwoo.park@seoultech.kr',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Jin Woo Park',
      headline: 'Full-Stack & WebRTC Engineer | React, Node.js, Real-Time Audio/Video',
      location: 'Seoul, South Korea',
      bio: 'Built video meeting infra supporting 10K concurrent streams. Eager to co-found real-time collaboration ventures.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      education: 'KAIST (BS Computer Science)',
      skills: 'WebRTC, React, Node.js, WebSockets, TypeScript, C++',
      startupInterests: 'Collaboration, EdTech, Remote Work, Video Tech',
      industries: 'Technology & Innovation, Education & Skills',
      preferredRole: 'Technical Co-Founder',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 85,
    },
  },
  {
    email: 'carlos.gomez@finlatam.co',
    role: 'MARKETER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Carlos Gomez',
      headline: 'Fintech Growth Strategist | User Acquisition & LatAm Market Expansion',
      location: 'Bogotá, Colombia',
      bio: 'Scaled consumer neobank in Colombia and Mexico from 0 to 800,000 active accounts via influencer and referral loops.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      education: 'Universidad de los Andes (BS Business Administration)',
      skills: 'Growth Marketing, Performance Ad Buying, Viral Referral Loops, LatAm Expansion',
      startupInterests: 'FinTech, Consumer Tech, Marketplaces, Mobile Money',
      industries: 'Economy & Inequality, Business & Commerce',
      preferredRole: 'Head of Growth / Marketing Co-Founder',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 80,
    },
  },
  {
    email: 'sunita.sen@agrobiotech.in',
    role: 'COFOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Sunita Sen',
      headline: 'Agricultural Microbiologist & Bio-Inoculant Researcher',
      location: 'Bengaluru, Karnataka, India',
      bio: 'Researching mycorrhizal fungi and biochar inoculants to restore organic carbon in degraded soils. Ready to build an AgriTech venture.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      education: 'University of Agricultural Sciences Bangalore (PhD Microbiology)',
      skills: 'Microbiology, Bio-fertilizers, Soil Chemistry, Field Trials, IP Patents',
      startupInterests: 'AgriTech, Soil Health, Regenerative Farming, BioTech',
      industries: 'Agriculture & Farming, Food & Water',
      preferredRole: 'Chief Science Officer / Co-Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      profileCompletion: 85,
    },
  },
  {
    email: 'clara.oswald@edtech.uk',
    role: 'DESIGNER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Clara Oswald',
      headline: 'Gamification & Learning Experience Designer | EdTech & Kids Apps',
      location: 'Edinburgh, UK',
      bio: 'Designing gamified learning loops and interactive storytelling that keep learners engaged. 5 years in early childhood tech.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'University of Edinburgh (MA Design & Digital Media)',
      skills: 'Gamification, Instructional Design, Figma, Animation, Lottie, User Testing',
      startupInterests: 'EdTech, Gaming, Social Impact, Literacy',
      industries: 'Education & Skills, Technology & Innovation',
      preferredRole: 'Lead Learning Experience Designer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 80,
    },
  },
  {
    email: 'leila.haddad@solartech.lb',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Leila Haddad',
      headline: 'Embedded IoT & Edge Firmware Developer | ESP32, MQTT, C++',
      location: 'Beirut, Lebanon',
      bio: 'Creating ultra-low power solar telemetry and pump controllers that transmit over LoRaWAN and 2G networks in off-grid environments.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      education: 'American University of Beirut (BS Computer & Communications Engineering)',
      skills: 'Embedded C, ESP32, LoRaWAN, MQTT, PCB Design, Low-Power Firmware',
      startupInterests: 'IoT, Clean Energy, Smart Agriculture, Water Systems',
      industries: 'Energy & Infrastructure, Agriculture & Farming',
      preferredRole: 'Founding IoT Engineer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 80,
    },
  },
  {
    email: 'oliver.wright@smecredit.uk',
    role: 'COFOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Oliver Wright',
      headline: 'Fintech Credit Risk & Financial Modeling Lead',
      location: 'Manchester, UK',
      bio: 'Former senior underwriter at Barclays Business Banking. Specialized in building dynamic cash flow underwriting engines for retail MSMEs.',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
      education: 'University of Manchester (BSc Mathematics & Statistics)',
      skills: 'Credit Risk, Financial Modeling, Python, SQL, Banking Partnerships, Underwriting',
      startupInterests: 'FinTech, B2B SaaS, MSME Lending, Working Capital',
      industries: 'Business & Commerce, Economy & Inequality',
      preferredRole: 'Co-Founder & Chief Risk Officer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 85,
    },
  },
  {
    email: 'tanya.deshmukh@supplychain.in',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Tanya Deshmukh',
      headline: 'Backend Systems & API Architect | Go, PostgreSQL, Kafka, Event-Driven Architecture',
      location: 'Pune, Maharashtra, India',
      bio: 'High-throughput backend specialist who engineered warehousing event systems handling 250,000 real-time package updates per hour.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      education: 'VJTI Mumbai (B.Tech Computer Engineering)',
      skills: 'Go, PostgreSQL, Apache Kafka, Redis, Docker, Event-Driven Systems, REST APIs',
      startupInterests: 'Logistics, Supply Chain, B2B SaaS, Infrastructure',
      industries: 'Supply Chain & Logistics, Business & Commerce',
      preferredRole: 'Lead Backend Engineer / Founding Engineer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      profileCompletion: 80,
    },
  },

  // STUDENTS & EARLY-STAGE ENTREPRENEURS
  {
    email: 'rohit.student@iith.ac.in',
    role: 'DEVELOPER',
    isVerified: false,
    profile: {
      fullName: 'Rohit Kulkarni',
      headline: 'Computer Science Undergrad @ IIT Hyderabad | Hackathon Winner & AI Enthusiast',
      location: 'Hyderabad, Telangana, India',
      bio: 'Passionate student builder who created an open-source WhatsApp bot for local vegetable market price discovery. Looking to join an early-stage AgriTech or AI team.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      education: 'IIT Hyderabad (BTech Computer Science, Class of 2026)',
      skills: 'Python, React, FastAPIs, LangChain, Tailwind CSS, Git',
      startupInterests: 'AgriTech, AI, Open Source, Social Impact',
      industries: 'Agriculture & Farming, Technology & Innovation',
      preferredRole: 'Founding Engineer / Engineering Intern',
      availability: 'Part-time',
      startupExperience: 'First-time Founder',
      profileCompletion: 70,
    },
  },
  {
    email: 'aaliyah.student@unilag.edu.ng',
    role: 'DEVELOPER',
    isVerified: false,
    profile: {
      fullName: 'Aaliyah Balogun',
      headline: 'Software Engineering Senior @ University of Lagos | Mobile Developer',
      location: 'Lagos, Nigeria',
      bio: 'Building offline-first mobile tools for small merchants across Lagos markets. Active in She Code Africa community.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      education: 'University of Lagos (BSc Computer Science, 2025)',
      skills: 'Flutter, Dart, Firebase, Node.js, REST APIs, Git',
      startupInterests: 'FinTech, Mobile Money, Women Empowerment',
      industries: 'Women & Social, Economy & Inequality',
      preferredRole: 'Mobile Engineer / Junior Developer',
      availability: 'Part-time',
      startupExperience: 'First-time Founder',
      profileCompletion: 65,
    },
  },
  {
    email: 'mateo.student@berkeley.edu',
    role: 'FOUNDER',
    isVerified: false,
    profile: {
      fullName: 'Mateo Rossi',
      headline: 'CS & Economics Major @ UC Berkeley | Building Micro-Carbon Offsets for E-Commerce',
      location: 'San Francisco, CA, USA',
      bio: 'Exploring consumer climate checkout integrations. Seeking a technical co-founder passionate about climate fintech.',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
      education: 'UC Berkeley (BA Economics & Computer Science, 2026)',
      skills: 'Financial Modeling, TypeScript, Product Design, Pitching, Customer Discovery',
      startupInterests: 'ClimateTech, FinTech, E-Commerce, Carbon Offsets',
      industries: 'Environment/Climate, Business & Commerce',
      preferredRole: 'Student Co-Founder',
      availability: 'Part-time',
      startupExperience: 'First-time Founder',
      profileCompletion: 60,
    },
  },
  {
    email: 'diya.student@bits.ac.in',
    role: 'DESIGNER',
    isVerified: false,
    profile: {
      fullName: 'Diya Sen',
      headline: 'Design & Human-Computer Interaction Student @ BITS Pilani',
      location: 'Goa, India',
      bio: 'Passionate about accessible UI and clean web design. Redesigned campus student portal with 12K monthly active users.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      education: 'BITS Pilani (B.E. Computer Science, 2025)',
      skills: 'Figma, UI Design, Wireframing, User Testing, Tailwind CSS',
      startupInterests: 'EdTech, HealthTech, Design Tools',
      industries: 'Education & Skills, Design Tools',
      preferredRole: 'Design Intern / Co-Founder',
      availability: 'Part-time',
      startupExperience: 'First-time Founder',
      profileCompletion: 65,
    },
  },

  // MORE MENTORS & INVESTORS
  {
    email: 'hannes.mentor@berlinscale.de',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Hannes Voigt',
      headline: 'Co-Founder & Former CTO @ FinLeap | European Banking API & Security Mentor',
      location: 'Berlin, Germany',
      bio: 'Co-founded 3 European fintech ventures. Advising technical founders on PSD2/PSD3 compliance, banking APIs, and SOC2 certifications.',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
      education: 'Humboldt University Berlin (PhD Computer Science)',
      skills: 'Fintech Regulation, Banking APIs, Information Security, SOC2, Distributed Systems',
      startupInterests: 'FinTech, B2B SaaS, CyberSecurity, Banking Infrastructure',
      industries: 'Business & Commerce, Technology & Innovation',
      preferredRole: 'Technical Strategy Advisor',
      availability: 'Advisory',
      startupExperience: 'Serial Founder',
      profileCompletion: 90,
    },
  },
  {
    email: 'farhan.mentor@agriscale.org',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Farhan Akhtar',
      headline: 'Former Director of Agriculture @ Tata Trusts | Rural Distribution & Smallholder GTM Mentor',
      location: 'New Delhi, India',
      bio: '25+ years leading public-private agricultural development partnerships across 18 Indian states. Helping AgriTech founders build viable unit economics in rural supply chains.',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
      education: 'IARI New Delhi (MSc Agronomy), Cornell University (Fellow)',
      skills: 'Agronomy, Farmer Producer Organizations (FPOs), Rural GTM, Agri Supply Chain, Policy',
      startupInterests: 'AgriTech, Food Security, Soil Health, Rural Livelihoods',
      industries: 'Agriculture & Farming, Food & Water',
      preferredRole: 'Agriculture Advisory Board',
      availability: 'Advisory',
      startupExperience: 'Serial Founder',
      profileCompletion: 90,
    },
  },
  {
    email: 'rajesh.investor@delhivc.in',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Rajesh Chhabra',
      headline: 'Partner @ India Ascent Capital (Demo VC) | Seed & Pre-Series A in B2B SaaS & AgriTech',
      location: 'New Delhi, India',
      bio: 'Investing $250K to $1M into Indian founders building deep-tech and market infrastructure ventures with global ambition.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      education: 'IIT Delhi (BTech), IIM Calcutta (MBA)',
      skills: 'Venture Capital, Seed Investing, SaaS Economics, Term Sheet Negotiation, Board Directorship',
      startupInterests: 'B2B SaaS, AgriTech, FinTech, Manufacturing Tech',
      industries: 'Business & Commerce, Agriculture & Farming, Technology & Innovation',
      preferredRole: 'Lead Institutional Investor',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      profileCompletion: 90,
    },
  },
  {
    email: 'sarah.jenkins@climatefund.org',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Sarah Jenkins',
      headline: 'Principal @ Terra Green Ventures (Demo Fund) | Early-Stage Decarbonization & Clean Energy',
      location: 'Boston, MA, USA',
      bio: 'Backing world-changing climate startups in grid modernization, carbon utilization, and sustainable agriculture.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'Harvard University (BA Chemistry), MIT Sloan (MBA)',
      skills: 'Climate Investing, Energy Transition, Due Diligence, Techno-Economic Analysis',
      startupInterests: 'ClimateTech, Clean Energy, Carbon Removal, BioTech',
      industries: 'Environment/Climate, Energy & Infrastructure, Agriculture & Farming',
      preferredRole: 'Seed / Series A Investor',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      profileCompletion: 90,
    },
  },
];
