export const seedFailedStartups = [
  {
    name: 'FarmDirect Mobile',
    industry: 'AgriTech & Logistics',
    peakFunding: '$2.8M (Series A)',
    yearsActive: '2021 – 2024',
    logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=80',
    summary: 'Direct-from-farm produce delivery app attempting to cut out middlemen and deliver organic vegetables to urban households within 6 hours.',
    whyItFailed: 'Uncontrollable post-harvest spoilage rates of 28%, high customer acquisition cost ($42 CAC vs $18 LTV), and cold chain logistics costs exceeding customer willingness to pay for delivery.',
    unsolvedProblem: 'Smallholder farmers still struggle with post-harvest produce degradation and volatile local wholesale mandi pricing.',
    lessonsLearned: '1) Avoid owning physical perishable inventory in consumer delivery; 2) B2B aggregation with existing mandi traders is far more capital-efficient than direct-to-consumer delivery; 3) Cold storage at farmgate must be decentralized and solar-powered.',
    solutions: [
      {
        authorEmail: 'sarah.chen@aiagri.io',
        title: 'B2B Farmgate Micro-Cold Storage & Collective Pre-Orders',
        description: 'Rather than running consumer vans, install modular solar-powered evaporative cold storage at village collection points and aggregate pre-orders from institutional restaurant buyers.',
        targetAudience: 'Farming cooperatives and restaurant wholesale procurement groups',
        differentiation: 'Zero retail inventory risk, 100% pre-committed sales before harvest picking, solar-powered decentralized storage.',
        upvotesCount: 24,
      },
      {
        authorEmail: 'arjun.mehta@agritech.in',
        title: 'Sensor-based Dynamic Pricing for Wholesale Mandi Lots',
        description: 'Provide low-cost handheld optical quality scanners to certify freshness at farmgate, enabling farmers to auction certified lots to food processors nationwide.',
        targetAudience: 'Food processing companies and agricultural aggregators',
        differentiation: 'Transparency on shelf-life prevents bulk rejection disputes.',
        upvotesCount: 16,
      },
    ],
  },
  {
    name: 'MediDeliver 15',
    industry: 'HealthTech & Quick Commerce',
    peakFunding: '$5.5M (Seed & Series A)',
    yearsActive: '2022 – 2024',
    logo: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&auto=format&fit=crop&q=80',
    summary: 'Ultra-fast 15-minute prescription and OTC medicine delivery using micro-fulfillment dark stores in metropolitan cities.',
    whyItFailed: 'Prescription verification bottlenecks caused delivery delays, unit economics were negative (-$3.20 per order after rider costs), and dark store rental overhead burned through capital.',
    unsolvedProblem: 'Patients with urgent medication needs still face friction obtaining prescriptions and reliable delivery during night hours.',
    lessonsLearned: '1) Medicine purchases are largely scheduled, not emergency 15-minute impulses; 2) Hyperlocal dark stores have unsustainable real estate overhead compared to partnering with existing neighborhood pharmacies.',
    solutions: [
      {
        authorEmail: 'ananya.rao@medivault.health',
        title: 'SaaS Dispatch Layer for Existing 24/7 Hospital Pharmacies',
        description: 'Instead of renting dark stores, plug into existing 24/7 hospital pharmacies with an automated courier dispatch and electronic prescription routing API.',
        targetAudience: 'Independent pharmacies, hospital systems, and chronic patients',
        differentiation: 'Zero real estate and inventory overhead, instant compliance with registered pharmacist dispensing laws.',
        upvotesCount: 29,
      },
    ],
  },
  {
    name: 'TutorStream VR',
    industry: 'EdTech & Hardware',
    peakFunding: '$4.2M (Venture)',
    yearsActive: '2020 – 2023',
    logo: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=200&auto=format&fit=crop&q=80',
    summary: 'Virtual reality classroom platform offering immersive 3D science labs and history simulations for K-12 students.',
    whyItFailed: 'High hardware headset costs ($399+ per student), headset fatigue and nausea among children, and poor internet bandwidth in schools prevented adoption beyond wealthy private pilots.',
    unsolvedProblem: 'Students need interactive, conceptual STEM visualizations without requiring expensive hardware headsets.',
    lessonsLearned: '1) Hardware-dependent education models fail in mass markets; 2) Browser-based 3D (WebGL) and conversational voice tutors achieve 90% of the pedagogical engagement at 1% of the deployment cost.',
    solutions: [
      {
        authorEmail: 'aisha.rahman@edugenie.org',
        title: 'Browser-based Socratic Voice Diagnostics (EduGenie Model)',
        description: 'Deliver conversational STEM mastery through lightweight mobile browser audio interfaces that run on $60 smartphones without headsets.',
        targetAudience: 'K-12 students in public and budget private schools',
        differentiation: 'Runs on any low-end smartphone with zero hardware expenditure.',
        upvotesCount: 38,
      },
    ],
  },
  {
    name: 'SolarChain Tokens',
    industry: 'CleanTech & Web3',
    peakFunding: '$3.1M (ICO & Seed)',
    yearsActive: '2021 – 2023',
    logo: 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=200&auto=format&fit=crop&q=80',
    summary: 'Decentralized tokenized carbon offsets and crypto rewards for residential rooftop solar power generation.',
    whyItFailed: 'High gas fees, token speculation overshadowing utility, and failure to integrate with regulated utility interconnection tariffs or compliance carbon markets.',
    unsolvedProblem: 'Distributed solar owners still lack automated mechanisms to monetize surplus clean energy and avoid peak demand charges.',
    lessonsLearned: '1) Avoid introducing speculative crypto tokens into regulated energy markets; 2) Solve direct utility tariff arbitrage with fiat currency savings before financial engineering.',
    solutions: [
      {
        authorEmail: 'ethan.brooks@voltmesh.energy',
        title: 'Commercial Virtual Power Plant Energy Arbitrage (VoltMesh Model)',
        description: 'Orchestrate commercial battery dispatch directly with regional utility operators to shave peak demand charges and earn direct cash tariff reductions.',
        targetAudience: 'Commercial industrial parks and university campuses',
        differentiation: 'Regulated utility compliance, measurable fiat dollar savings, zero speculative tokens.',
        upvotesCount: 31,
      },
    ],
  },
  {
    name: 'CleanDrop Reverse Logistics',
    industry: 'Circular Economy & E-Commerce',
    peakFunding: '$1.8M (Pre-Seed)',
    yearsActive: '2022 – 2024',
    logo: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=200&auto=format&fit=crop&q=80',
    summary: 'Consumer doorstep packaging collection service offering cashback for returned cardboard shipping boxes.',
    whyItFailed: 'Doorstep pickup logistics costs ($2.80 per box collected) vastly exceeded the recycled pulp value ($0.08 per box), and consumer participation dropped once initial cashback incentives subsided.',
    unsolvedProblem: 'E-commerce single-use packaging waste continues to inundate municipal landfills.',
    lessonsLearned: '1) Doorstep collection of low-density packaging cannot be economically justified; 2) The solution lies in biodegradable materials that can be safely composted at home, eliminating reverse logistics entirely.',
    solutions: [
      {
        authorEmail: 'samantha.hayes@biomaterials.io',
        title: 'Home-Compostable Marine-Degradable Seaweed Packaging (EcoWrap)',
        description: 'Replace plastic and cardboard protective packaging with kelp-based biomaterials that dissolve harmlessly in soil or water, eliminating the need for return logistics.',
        targetAudience: 'E-commerce shippers, electronics brands, and fulfillment centers',
        differentiation: 'No return logistics required, zero microplastics, decomposes in 45 days.',
        upvotesCount: 42,
      },
    ],
  },
  {
    name: 'OptiFleet Trucking',
    industry: 'Logistics',
    peakFunding: '$3.5M (Seed)',
    yearsActive: '2020 – 2023',
    logo: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=200&auto=format&fit=crop&q=80',
    summary: 'Spot-market freight brokerage app attempting to displace traditional freight brokers through open algorithmic auctions.',
    whyItFailed: 'Disintermediated brokers fought back with predatory credit terms (net-90 payment terms that the startup could not float), leading to severe cash-flow crunches and driver churn.',
    unsolvedProblem: 'Truckload carriers still suffer from 22% empty trailer miles on return journeys.',
    lessonsLearned: '1) Freight is deeply credit-dependent; fintech working capital is mandatory; 2) Do not attempt to replace brokers wholesale; empower existing brokers with 3D capacity optimization software.',
    solutions: [
      {
        authorEmail: 'chen.wei@optilog.tech',
        title: 'Capacity Packing SaaS for Existing 3PL Freight Brokers (OptiLog)',
        description: 'Provide algorithmic 3D container consolidation and route optimization as an API to existing freight forwarders, rather than competing against them.',
        targetAudience: 'Third-party logistics providers and fleet dispatchers',
        differentiation: 'Non-disruptive SaaS model, zero credit risk, pure software margin.',
        upvotesCount: 27,
      },
    ],
  },
];
