export const seedInvestors = [
  {
    email: 'elena.investor@apexventures.vc',
    organization: 'Apex Ventures (Demo VC)',
    investorType: 'Venture Capital',
    industries: 'AgriTech, AI/ML, ClimateTech, B2B SaaS',
    preferredStages: 'Seed, Pre-Seed',
    minCheckSize: '$250,000',
    maxCheckSize: '$1,500,000',
    location: 'San Francisco, CA, USA',
    website: 'https://apexventures.demo.vc',
    portfolio: 'AgroPulse, VoltMesh Energy, CyberMesh (Demo Portfolio)',
    about: 'Investing in high-conviction technical founders building software and intelligent systems that solve planetary-scale bottlenecks in food, energy, and intelligence.',
    isVerified: true,
  },
  {
    email: 'kavita.goel@angelnetwork.in',
    organization: 'Catalyst India Partners (Demo VC)',
    investorType: 'Venture Capital',
    industries: 'FinTech, B2B Commerce, AgriTech, Logistics',
    preferredStages: 'Pre-Seed, Seed',
    minCheckSize: '$150,000',
    maxCheckSize: '$750,000',
    location: 'Bengaluru, Karnataka, India',
    website: 'https://catalystvc.demo.in',
    portfolio: 'FinSync Global, KrishiGyan AI, PathFinder Edu',
    about: 'Early-stage venture fund backing mission-driven founders transforming the next 500 million consumers and SME supply chains across Bharat.',
    isVerified: true,
  },
  {
    email: 'simon.vanderbilt@bluelight.vc',
    organization: 'Euronext Capital (Demo VC)',
    investorType: 'Venture Capital',
    industries: 'DeepTech, ClimateTech, Robotics, Quantum/AI',
    preferredStages: 'Seed, Series A',
    minCheckSize: '€500,000',
    maxCheckSize: '€3,000,000',
    location: 'Amsterdam, Netherlands',
    website: 'https://euronextcap.demo.eu',
    portfolio: 'ReverseLoop, NanoFilter Water, ZenithAI Studio',
    about: 'Leading pan-European DeepTech fund partnering with visionary scientists and engineers transforming fundamental physical industries.',
    isVerified: true,
  },
  {
    email: 'evelyn.reed@biomentor.org',
    organization: 'ImpactFirst Foundation (Demo Fund)',
    investorType: 'Impact Fund / Blended Finance',
    industries: 'Water & Sanitation, Agriculture, Healthcare, EdTech',
    preferredStages: 'Pre-Seed, Seed, Grants',
    minCheckSize: '$50,000',
    maxCheckSize: '$400,000',
    location: 'London, UK',
    website: 'https://impactfirst.demo.org',
    portfolio: 'AquaPure Solar, SaharaFlow, FemiSave Health, MindHaven Health',
    about: 'Deploying catalytic patient capital and non-dilutive innovation grants to ventures addressing UN Sustainable Development Goals in emerging markets.',
    isVerified: true,
  },
  {
    email: 'marcus.thorne@deeptech.vc',
    organization: 'Novus Climate Capital (Demo VC)',
    investorType: 'Venture Capital',
    industries: 'ClimateTech, CleanTech, Circular Economy, Carbon Removal',
    preferredStages: 'Seed, Series A',
    minCheckSize: '£400,000',
    maxCheckSize: '£2,000,000',
    location: 'London, UK',
    website: 'https://novuscap.demo.co.uk',
    portfolio: 'TraceCraft, EcoWrap Packaging, VoltMesh Energy',
    about: 'Investing in technological breakthroughs that eliminate gigatons of greenhouse gas emissions across industry, agriculture, and power grids.',
    isVerified: true,
  },
  {
    email: 'courtney.vance@angelpulse.com',
    organization: 'Aura Angels Syndicate (Demo)',
    investorType: 'Angel Syndicate',
    industries: 'Developer Tools, AI Infrastructure, Cloud, Open Source',
    preferredStages: 'Pre-Seed, Seed',
    minCheckSize: '$50,000',
    maxCheckSize: '$250,000',
    location: 'San Francisco, CA, USA',
    website: 'https://angelpulse.demo.com',
    portfolio: 'CyberMesh, CodeFlow Studio, ZenithAI Studio',
    about: 'Syndicate of 120+ senior tech executives writing rapid angel checks into developer infrastructure and open-source commercialization.',
    isVerified: true,
  },
  {
    email: 'rajesh.investor@delhivc.in',
    organization: 'India Ascent Capital (Demo VC)',
    investorType: 'Venture Capital',
    industries: 'B2B SaaS, AgriTech, FinTech, Manufacturing Tech',
    preferredStages: 'Seed, Pre-Series A',
    minCheckSize: '$250,000',
    maxCheckSize: '$1,000,000',
    location: 'New Delhi, India',
    website: 'https://delhivc.demo.in',
    portfolio: 'AgroPulse, FinSync Global, KrishiGyan AI',
    about: 'Backing Indian founders building deep-tech and market infrastructure ventures with global market ambition.',
    isVerified: true,
  },
  {
    email: 'sarah.jenkins@climatefund.org',
    organization: 'Terra Green Ventures (Demo Fund)',
    investorType: 'Venture Capital',
    industries: 'ClimateTech, Clean Energy, Carbon Removal, BioTech',
    preferredStages: 'Seed, Series A',
    minCheckSize: '$500,000',
    maxCheckSize: '$2,500,000',
    location: 'Boston, MA, USA',
    website: 'https://climatefund.demo.org',
    portfolio: 'VoltMesh Energy, BioShield Therapeutics, ReverseLoop',
    about: 'Dedicated to accelerating the transition to a net-zero global economy by funding breakthroughs in clean power and industrial decarbonization.',
    isVerified: true,
  },
  {
    email: 'alex.chen@scaleup.vc',
    organization: 'ScaleUp Labs Ventures (Demo)',
    investorType: 'Micro VC',
    industries: 'B2B SaaS, FinTech, DevTools, AI Applications',
    preferredStages: 'Pre-Seed, Seed',
    minCheckSize: '$100,000',
    maxCheckSize: '$500,000',
    location: 'San Francisco, CA, USA',
    website: 'https://scaleup.demo.vc',
    portfolio: 'CyberMesh, OptiLog AI, FinSync Global',
    about: 'Founder-first micro fund backing product-obsessed teams with fast decision-making and hands-on GTM support.',
    isVerified: true,
  },
  {
    email: 'david.kim@growthscale.co',
    organization: 'GrowthScale Angel Fund (Demo)',
    investorType: 'Angel',
    industries: 'Consumer Tech, HealthTech, Marketplaces, EdTech',
    preferredStages: 'Pre-Seed',
    minCheckSize: '$25,000',
    maxCheckSize: '$100,000',
    location: 'Austin, TX, USA',
    website: 'https://growthscale.demo.co',
    portfolio: 'EduGenie, MindHaven Health',
    about: 'Active angel investor helping founders structure initial user acquisition funnels and product-led growth experiments.',
    isVerified: true,
  },
  {
    email: 'marcus.dev@codeflow.dev',
    organization: 'Brody Tech Capital (Demo Angel)',
    investorType: 'Angel',
    industries: 'Technology & Innovation, B2B SaaS, Infrastructure',
    preferredStages: 'Pre-Seed',
    minCheckSize: '$25,000',
    maxCheckSize: '$150,000',
    location: 'Seattle, WA, USA',
    website: 'https://angelpulse.demo.io',
    portfolio: 'CyberMesh, ZenithAI Studio',
    about: 'Angel investor backing technical founders solving hard problems in distributed infrastructure and cloud systems.',
    isVerified: true,
  },
  {
    email: 'sanjay.mentor@fintechpulse.in',
    organization: 'Singhania Family Office (Demo)',
    investorType: 'Family Office',
    industries: 'Logistics, AgriTech, Clean Energy, Real Estate Tech',
    preferredStages: 'Seed, Growth',
    minCheckSize: '$500,000',
    maxCheckSize: '$3,000,000',
    location: 'Mumbai, India',
    website: 'https://b2bscale.demo.com',
    portfolio: 'HydroSense Technologies, OptiLog AI, SolarGrid Micro',
    about: 'Patient multi-generational family office capital supporting sustainable industrial technologies and real economy infrastructure.',
    isVerified: true,
  },
];
