export const seedMentors = [
  {
    email: 'alex.chen@scaleup.vc',
    expertise: 'Early-stage Fundraising, B2B SaaS GTM, Product-Market Fit',
    industries: 'B2B SaaS, Enterprise Software, Developer Tools, FinTech',
    yearsExperience: 14,
    availableHours: '3-5 hrs/month',
    mentoringTopics: 'Zero-to-one traction, Pricing strategy, Seed pitch decks, Hiring first 10 engineers',
    about: 'Former 2x founder (acq by Salesforce). Partner at ScaleUp Labs. Guided 40+ founders through seed and Series A milestones.',
    isVerified: true,
    requests: [
      {
        founderEmail: 'sarah.chen@aiagri.io',
        topic: 'Structuring seed round milestones for AgTech hardware + SaaS',
        message: 'Hi Alex, we are scaling AgroPulse from MVP to 50 farm clusters and looking for advice on balancing hardware inventory debt with venture equity.',
        status: 'ACCEPTED',
      },
      {
        founderEmail: 'rohan.kapoor@finsync.io',
        topic: 'Navigating cross-border regulatory licensing in emerging markets',
        message: 'Would love your perspective on partner bank compliance versus obtaining direct central bank payments licenses.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    email: 'sneha.kulkarni@safewater.org',
    expertise: 'Product Management, User Research, Agile Execution, Growth Loops',
    industries: 'EdTech, Consumer Apps, B2B SaaS, HealthTech',
    yearsExperience: 11,
    availableHours: '2-4 hrs/month',
    mentoringTopics: 'Customer discovery interviews, Product roadmapping, Prioritization frameworks, User retention',
    about: 'Ex-VP Product at EdTech unicorns. Passionate about helping technical founders build deep empathy for end users.',
    isVerified: true,
    requests: [
      {
        founderEmail: 'aisha.rahman@edugenie.org',
        topic: 'Refining parent-teacher feedback loops for AI tutoring',
        message: 'Hi Sneha, we are seeing great student engagement but want to optimize how we present learning diagnostics to parents.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    email: 'haruto.tanaka@robotics.jp',
    expertise: 'DeepTech Commercialization, Robotics, Hardware Supply Chain',
    industries: 'Robotics, IoT, Clean Energy, Industrial Automation',
    yearsExperience: 18,
    availableHours: '2-3 hrs/month',
    mentoringTopics: 'Design for Manufacturing (DFM), Asian supply chain negotiation, Hardware cap tables, IP strategy',
    about: 'Built and scaled industrial automation robotics in Tokyo and Shenzhen. Mentored 25+ hardware spinouts from academic labs.',
    isVerified: true,
    requests: [
      {
        founderEmail: 'sofia.martinez@hydrosense.ai',
        topic: 'Transitioning acoustic sensors from 3D printed prototypes to injection tooling',
        message: 'Looking for advice on low-volume DFM and ultrasonic transducer sourcing in East Asia.',
        status: 'PENDING',
      },
    ],
  },
  {
    email: 'pooja.singhania@greenpack.in',
    expertise: 'Startup Corporate Law, Cross-Border IP, Co-founder Agreements',
    industries: 'FinTech, SaaS, Healthcare, DeepTech',
    yearsExperience: 12,
    availableHours: '2-4 hrs/month',
    mentoringTopics: 'Co-founder equity vesting, ESOP pool creation, IP assignment, Term sheet pitfalls',
    about: 'Managing partner advising early-stage founders on legal hygiene, cap table setup, and cross-border holding company structuring.',
    isVerified: true,
    requests: [
      {
        founderEmail: 'marcus.dev@codeflow.dev',
        topic: 'Structuring founder reverse vesting clauses with incoming technical co-founder',
        message: 'Seeking guidance on typical vesting acceleration and IP assignment templates.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    email: 'arthur.pendelton@gtm.org',
    expertise: 'Impact Measurement, Climate Policy, Development Finance (DFI)',
    industries: 'ClimateTech, CleanTech, Agriculture & Food, Water & Sanitation',
    yearsExperience: 20,
    availableHours: '2 hrs/month',
    mentoringTopics: 'Blended finance models, Carbon credit verifications (Verra/Gold Standard), Grant writing',
    about: 'Senior advisor to international development organizations and climate accelerators across Europe and Africa.',
    isVerified: true,
    requests: [
      {
        founderEmail: 'gabriel.santos@agrisat.io',
        topic: 'Grant funding avenues for atmospheric water generation in North Africa',
        message: 'Would love to discuss navigating Horizon Europe and UN climate adaptation innovation grants.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    email: 'astrid.lindholm@nordiccapital.se',
    expertise: 'Circular Economy, ESG Compliance, EU Taxonomy, Sustainable Supply Chains',
    industries: 'CleanTech, Sustainable Materials, Waste Management, Packaging',
    yearsExperience: 15,
    availableHours: '3-4 hrs/month',
    mentoringTopics: 'Life Cycle Assessment (LCA), Navigating EU CSRD mandates, Sustainable packaging certifications',
    about: 'Pioneered Nordic circular packaging standards. Advisor to zero-waste startups across Scandinavia and Germany.',
    isVerified: true,
    requests: [
      {
        founderEmail: 'samantha.hayes@biomaterials.io',
        topic: 'Marine biodegradability certification testing protocols in Europe',
        message: 'Looking to understand the timeline and lab costs for ASTM D6691 and EN 13432 certification.',
        status: 'PENDING',
      },
    ],
  },
  {
    email: 'marcus.dev@codeflow.dev',
    expertise: 'Full-Stack Architecture, Distributed Systems, Cloud Cost Optimization',
    industries: 'Technology & Innovation, B2B SaaS, Developer Tools',
    yearsExperience: 13,
    availableHours: '3-5 hrs/month',
    mentoringTopics: 'System architecture reviews, Preventing cloud bill explosions, High-throughput caching, Microservices vs Monoliths',
    about: 'Principal cloud architect who has scaled backend infrastructures to millions of daily active users.',
    isVerified: true,
    requests: [],
  },
  {
    email: 'sanjay.mentor@fintechpulse.in',
    expertise: 'B2B Enterprise Sales, Outbound Lead Generation, Channel Partnerships',
    industries: 'B2B SaaS, Supply Chain, Logistics, FinTech',
    yearsExperience: 16,
    availableHours: '2-4 hrs/month',
    mentoringTopics: 'Cold outbound that works, Enterprise sales cycles, Closing 6-figure ACV deals, Sales compensation plans',
    about: 'Built enterprise sales teams generating $50M+ ARR across US and European markets.',
    isVerified: true,
    requests: [],
  },
  {
    email: 'david.kim@growthscale.co',
    expertise: 'Performance Marketing, Viral Referral Loops, Paid Acquisition, CRO',
    industries: 'Consumer Tech, Marketplaces, B2B SaaS, HealthTech',
    yearsExperience: 9,
    availableHours: '4 hrs/month',
    mentoringTopics: 'Zero-budget organic growth, Landing page conversion optimization, Paid social funnels, CAC:LTV optimization',
    about: 'Scaled acquisition for three venture-backed consumer startups from 0 to 1M users.',
    isVerified: true,
    requests: [],
  },
  {
    email: 'radhika.swami@mentorship.org',
    expertise: 'Public Health Systems, Clinical Trials in Low-Resource Settings, WHO Guidelines',
    industries: 'HealthTech, Rural Healthcare, Medical Diagnostics',
    yearsExperience: 17,
    availableHours: '2-4 hrs/month',
    mentoringTopics: 'Designing community clinical trials, Engaging local health ministries, Low-cost point-of-care diagnostics',
    about: 'Dedicated to bringing medical diagnostics and quality healthcare to underserved rural communities.',
    isVerified: true,
    requests: [],
  },
  {
    email: 'kenji.takahashi@seedangels.jp',
    expertise: 'Consumer Electronics, Embedded Systems, IoT Connectivity, SMT Assembly',
    industries: 'Hardware, IoT, Robotics, Automotive',
    yearsExperience: 22,
    availableHours: '2-3 hrs/month',
    mentoringTopics: 'PCB layout reviews, SMT factory selection, Firmware resilience, EMC/FCC compliance testing',
    about: 'Shipped millions of commercial IoT and connected consumer devices worldwide.',
    isVerified: true,
    requests: [],
  },
  {
    email: 'priya.design@pixelcraft.studio',
    expertise: 'Design Systems, Human-Centered Research, Mobile Accessibility, Brand Identity',
    industries: 'Design, Mobile Apps, SaaS, EdTech',
    yearsExperience: 8,
    availableHours: '3-4 hrs/month',
    mentoringTopics: 'Building component libraries, User interview synthesis, Usability testing on mobile, Design critiques',
    about: 'Design lead passionate about crafting intuitive digital experiences for diverse global audiences.',
    isVerified: true,
    requests: [],
  },
];
