export const seedOpportunities = [
  {
    startupName: 'AgroPulse',
    role: 'Technical Co-Founder / Lead AI Engineer',
    requiredSkills: 'Python, PyTorch, Edge Computer Vision, IoT, React Native',
    commitment: 'Full-time',
    compensation: 'Equity (15-25%) + Seed Salary',
    location: 'Austin, TX or Remote',
    workplaceType: 'Remote',
    description: 'We are seeking an experienced technical co-founder to lead machine learning and edge pipeline architecture for our crop advisory platform. You will build computer vision disease detection and coordinate satellite multispectral ingestion.',
    status: 'OPEN',
    applications: [
      {
        applicantEmail: 'marcus.dev@codeflow.dev',
        coverLetter: 'I have 7+ years building production ML systems and distributed data pipelines. Passionate about applying AI to tangible climate and agricultural problems.',
        status: 'ACCEPTED',
      },
      {
        applicantEmail: 'fatima.zahra@solarirrigation.ma',
        coverLetter: 'Strong background in computer vision and satellite GIS data processing. Would love to bring edge intelligence to smallholder agriculture.',
        status: 'PENDING',
      },
    ],
  },
  {
    startupName: 'AgroPulse',
    role: 'Founding Product Designer',
    requiredSkills: 'Figma, UX Research, Design Systems, Mobile Interaction Design',
    commitment: 'Full-time',
    compensation: 'Paid + Equity (2-4%)',
    location: 'Remote (US / Global)',
    workplaceType: 'Remote',
    description: 'Looking for a human-centered designer who can design simple, intuitive interfaces for non-technical rural users and agricultural field coordinators.',
    status: 'OPEN',
    applications: [
      {
        applicantEmail: 'priya.design@pixelcraft.studio',
        coverLetter: 'Obsessed with designing high-utility, low-friction interfaces for the next billion users. Have designed award-winning AgTech applications.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    startupName: 'FinSync Global',
    role: 'Lead Payments & Security Architect',
    requiredSkills: 'Golang, PostgreSQL, PCI-DSS, Banking APIs, Distributed Ledger',
    commitment: 'Full-time',
    compensation: 'Competitive Salary ($110K-$140K) + Equity',
    location: 'Mumbai, India / Hybrid',
    workplaceType: 'Hybrid',
    description: 'Lead our core transaction processing engine, managing automated FX hedging corridors and maintaining sub-second settlement uptime across bilateral cross-border payment rails.',
    status: 'OPEN',
    applications: [
      {
        applicantEmail: 'alex.becker@devops.de',
        coverLetter: 'Built resilient payment switches and financial settlement engines handling millions of daily microtransactions with strict zero-trust principles.',
        status: 'PENDING',
      },
    ],
  },
  {
    startupName: 'FinSync Global',
    role: 'Growth Marketing & Channel Partnerships Lead',
    requiredSkills: 'B2B GTM, Fintech Sales, Partner Management, Cross-border Trade',
    commitment: 'Full-time',
    compensation: 'Salary + Performance Commission + Equity',
    location: 'Dubai / Mumbai',
    workplaceType: 'Hybrid',
    description: 'Drive merchant acquisition across export-import hubs in East Africa and South Asia. Build strategic referral ties with freight forwarders and chambers of commerce.',
    status: 'OPEN',
    applications: [
      {
        applicantEmail: 'kavya.nair@talentloom.ai',
        coverLetter: 'Experienced in scaling emerging market fintech distribution channels from 0 to 1,000+ business accounts.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    startupName: 'MediVault AI',
    role: 'Founding Privacy & Cryptography Engineer',
    requiredSkills: 'Differential Privacy, Zero-Knowledge Proofs, Python, C++, HIPAA Compliance',
    commitment: 'Full-time',
    compensation: 'Salary ($120K-$150K) + Equity (3-6%)',
    location: 'Boston, MA / Remote',
    workplaceType: 'Hybrid',
    description: 'Architect mathematical privacy bounds and verifiable computation mechanisms allowing distributed research hospitals to securely compute multi-party biomarker neural networks.',
    status: 'OPEN',
    applications: [
      {
        applicantEmail: 'julian.vance@aihealth.co',
        coverLetter: 'Deep background in privacy-preserving machine learning and federated oncology genomics at MIT.',
        status: 'ACCEPTED',
      },
    ],
  },
  {
    startupName: 'HydroSense Technologies',
    role: 'Embedded Firmware & Signal Processing Engineer',
    requiredSkills: 'Embedded C/C++, DSP, ARM Cortex-M, Acoustic Wave Processing, LoRaWAN',
    commitment: 'Full-time',
    compensation: 'Equity (5-10%) + Stipend (Post-Seed Salary)',
    location: 'Hyderabad, India',
    workplaceType: 'On-site',
    description: 'Design ultra-low-power firmware for acoustic leak-detection hardware clamp units. Optimize on-device FFT and wavelet transforms to operate on micro-batteries for 5+ years.',
    status: 'OPEN',
    applications: [
      {
        applicantEmail: 'rohit.verma@finops.ai',
        coverLetter: 'Passionate about smart city water infrastructure and edge signal processing firmware.',
        status: 'ACCEPTED',
      },
      {
        applicantEmail: 'kenji.takahashi@seedangels.jp',
        coverLetter: 'Over 10 years of experience with industrial IoT sensor nodes and firmware optimization.',
        status: 'PENDING',
      },
    ],
  },
  {
    startupName: 'VoltMesh Energy',
    role: 'Grid Integration & Energy Markets Strategist',
    requiredSkills: 'FERC Regulations, Virtual Power Plants, OpenADR, Python, Energy Arbitrage',
    commitment: 'Full-time',
    compensation: 'Salary ($130K-$160K) + 2% Equity',
    location: 'Denver, CO / Remote',
    workplaceType: 'Remote',
    description: 'Navigate regional utility interconnection rules, structure automated commercial battery dispatch protocols, and participate in ERCOT and CAISO capacity bidding programs.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'VoltMesh Energy',
    role: 'Senior Distributed Systems Engineer (Rust)',
    requiredSkills: 'Rust, Tokio, WebSockets, Kafka, Time-series Databases (TimescaleDB)',
    commitment: 'Full-time',
    compensation: 'Salary ($140K-$170K) + 1.5% Equity',
    location: 'Remote',
    workplaceType: 'Remote',
    description: 'Scale our real-time telemetry pipeline receiving millions of sensor readings per second from solar arrays and commercial battery storage banks.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'EduGenie',
    role: 'Senior Prompt & Cognitive Architecture Specialist',
    requiredSkills: 'LLM Fine-Tuning, Socratic Method, Education Pedagogy, Python, LangChain/LlamaIndex',
    commitment: 'Full-time',
    compensation: 'Competitive Salary + Equity',
    location: 'Bengaluru / Remote',
    workplaceType: 'Remote',
    description: 'Design educational prompting frameworks that evaluate student misconception trajectories and guide learners to self-discovery rather than simply answering homework problems.',
    status: 'OPEN',
    applications: [
      {
        applicantEmail: 'fatima.zahra@solarirrigation.ma',
        coverLetter: 'Master’s in Education Technology and cognitive science, excited to build genuinely pedagogical AI tutors.',
        status: 'PENDING',
      },
    ],
  },
  {
    startupName: 'EduGenie',
    role: 'Frontend Experience Engineer (React & Animation)',
    requiredSkills: 'React, TypeScript, Tailwind CSS, Framer Motion, Web Audio API',
    commitment: 'Full-time',
    compensation: 'Salary (₹18L - ₹26L) + Equity',
    location: 'Bengaluru, India',
    workplaceType: 'Hybrid',
    description: 'Create whimsical, snappy, responsive interactive web interfaces for young students. Implement interactive whiteboard and gamified milestone rewards.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'TraceCraft',
    role: 'Enterprise Carbon Accounting Analyst',
    requiredSkills: 'GHG Protocol, LCA (Life Cycle Assessment), SimaPro, Supply Chain Auditing',
    commitment: 'Full-time',
    compensation: '€55K - €70K + Equity',
    location: 'Madrid / Remote',
    workplaceType: 'Hybrid',
    description: 'Work with multinational enterprise clients to translate raw BOMs (Bill of Materials) and procurement spreadsheets into verified Scope 3 emission footprints.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'CyberMesh',
    role: 'Lead AI Red-Teamer & Security Researcher',
    requiredSkills: 'Prompt Injection, Adversarial Machine Learning, Jailbreaking, Python, CTF Experience',
    commitment: 'Full-time',
    compensation: '$150K - $185K + Significant Equity',
    location: 'San Francisco, CA',
    workplaceType: 'Hybrid',
    description: 'Dissect the newest foundational models, discover zero-day multi-modal jailbreaks, and develop automated synthetic exploit benchmarks for our enterprise defense engine.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'OptiLog AI',
    role: 'Operations Research & Optimization Scientist',
    requiredSkills: 'Combinatorial Optimization, Gurobi / OR-Tools, Vehicle Routing Problems (VRP), Python',
    commitment: 'Full-time',
    compensation: '£65K - £85K + Equity',
    location: 'London, UK / Remote',
    workplaceType: 'Remote',
    description: 'Develop mixed-integer linear programming models that optimize dynamic 3D cargo packing and multi-stop freight route allocation across European freight corridors.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'FemiSave Health',
    role: 'Biomedical Optics & Image Classification Lead',
    requiredSkills: 'Optical Imaging, Edge Computer Vision, Python, PyTorch, Medical Device Regulations',
    commitment: 'Full-time',
    compensation: '₹16L - ₹24L + Equity',
    location: 'Chennai, India',
    workplaceType: 'On-site',
    description: 'Calibrate portable multispectral camera sensors and train high-specificity cervical lesion classification models designed to run locally on low-cost Android tablets.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'MindHaven Health',
    role: 'Head of Clinical Programs & Community Safety',
    requiredSkills: 'Clinical Psychology (PhD / PsyD), CBT, Crisis Intervention, Group Therapy',
    commitment: 'Part-time',
    compensation: 'Stipend + Equity Advisory',
    location: 'Lagos / Nairobi / Remote',
    workplaceType: 'Remote',
    description: 'Guide mental health protocol development, oversee peer-support moderator training, and establish robust clinical escalation pathways for severe emotional distress.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'ZenithAI Studio',
    role: 'Senior 3D Graphics Engine Programmer (Unreal / C++)',
    requiredSkills: 'Unreal Engine 5, C++, HLSL Shaders, Geometry Processing, Mesh Retopology',
    commitment: 'Full-time',
    compensation: 'Competitive Tech Package ($120K-$160K) + Equity',
    location: 'Singapore / Remote',
    workplaceType: 'Remote',
    description: 'Bridge neural 3D asset generation directly into Unreal Engine 5 via custom editor plugins, supporting automated skeletal rigging and Nanite mesh optimization.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'ReverseLoop',
    role: 'Automation & Pneumatic Systems Engineer',
    requiredSkills: 'PLC Programming (Siemens/Beckhoff), Pneumatics, High-speed Sorting, Industrial Vision',
    commitment: 'Full-time',
    compensation: '€60K - €80K + Equity',
    location: 'Munich, Germany',
    workplaceType: 'On-site',
    description: 'Design the physical mechanical sorting gantry and pneumatic valve manifolds operating at millisecond speeds to eject designated plastic flakes from recycling belts.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'AquaPure Solar',
    role: 'Field Deployment & Rural Community Operations Lead',
    requiredSkills: 'Community Engagement, Rural Project Management, Marathi/Hindi Fluency, Water Quality Testing',
    commitment: 'Full-time',
    compensation: 'Salary + Field Living Allowance',
    location: 'Pune / Gujarat Field Locations',
    workplaceType: 'On-site',
    description: 'Work directly with village panchayats to commission community solar water distillation stations, train local women water caretakers, and monitor daily purity output.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'EcoWrap Packaging',
    role: 'Polymer Chemist & Biomaterial Formulator',
    requiredSkills: 'Biopolymer Chemistry, Mycelium Cultivation, Rheology, Biodegradability Testing',
    commitment: 'Full-time',
    compensation: '$90K - $115K + Equity',
    location: 'Seattle, WA',
    workplaceType: 'On-site',
    description: 'Formulate proprietary seaweed polysaccharide and mycelium blends to achieve target compressive strength, water resistance, and marine degradation within 45 days.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'FleetZero Mobility',
    role: 'Battery Management Systems (BMS) Firmware Architect',
    requiredSkills: 'Embedded C, CAN Bus, BMS Architecture, Lithium Iron Phosphate (LFP) Balancing',
    commitment: 'Full-time',
    compensation: '¥8M - ¥11M + Stock Options',
    location: 'Tokyo, Japan',
    workplaceType: 'On-site',
    description: 'Design mission-critical firmware for our smart swappable battery packs. Implement state-of-charge (SoC) and state-of-health (SoH) algorithms resilient to extreme ambient heat.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'SolarGrid Micro',
    role: 'Smart Metering & USSD Billing Developer',
    requiredSkills: 'GSM/GPRS Modules, Embedded Linux, Mobile Money APIs (M-Pesa, Paystack), Node.js',
    commitment: 'Full-time',
    compensation: 'Competitive Package in NGN / USD + Equity',
    location: 'Lagos / Ibadan, Nigeria',
    workplaceType: 'Hybrid',
    description: 'Build robust telemetry firmware for off-grid meters communicating over 2G cellular bands to activate power relays when customers purchase prepaid credits via USSD.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'SafeHealth Diagnostic',
    role: 'Regulatory Affairs & Medical Device Certification Specialist',
    requiredSkills: 'ISO 13485, CDSCO Medical Device Rules, IVD Clinical Validation, Audit Management',
    commitment: 'Part-time',
    compensation: 'Retainer + Equity Advisory',
    location: 'Bengaluru / Remote',
    workplaceType: 'Remote',
    description: 'Guide our paper microfluidic test strips and smartphone app through regulatory approval pathways for in-vitro diagnostic medical devices in India and Southeast Asia.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'BioShield Therapeutics',
    role: 'Computational Structural Biologist (Protein Folding)',
    requiredSkills: 'AlphaFold2, Rosetta, Molecular Dynamics (GROMACS), Python, HPC Slurm',
    commitment: 'Full-time',
    compensation: '$130K - $160K + Equity',
    location: 'Boston, MA',
    workplaceType: 'Hybrid',
    description: 'Screen billions of synthetic antimicrobial peptide conformations in silico, predicting binding affinity and membrane disruption mechanisms against antibiotic-resistant bacteria.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'VoltSync Hub',
    role: 'Building Management Systems (BMS) Protocol Integrator',
    requiredSkills: 'BACnet IP, Modbus RTU/TCP, HVAC Controls, Niagara Framework, Python',
    commitment: 'Full-time',
    compensation: 'AED 24,000 - 32,000 / month + Equity',
    location: 'Dubai, UAE',
    workplaceType: 'On-site',
    description: 'Deploy our edge gateways into commercial high-rise mechanical rooms, interfacing directly with Johnson Controls, Honeywell, and Siemens building automation systems.',
    status: 'OPEN',
    applications: [],
  },
  {
    startupName: 'KrishiGyan AI',
    role: 'Vernacular Audio & Speech Model Engineer',
    requiredSkills: 'Automatic Speech Recognition (ASR), Whisper fine-tuning, Indic Languages, PyTorch',
    commitment: 'Full-time',
    compensation: '₹14L - ₹22L + Equity',
    location: 'Ahmedabad / Remote',
    workplaceType: 'Remote',
    description: 'Fine-tune acoustic models on accented agricultural dialects across Hindi, Gujarati, Marathi, and Telugu, enabling seamless voice queries in noisy outdoor field conditions.',
    status: 'OPEN',
    applications: [],
  },
];
