export const seedProblems = [
  {
    title: 'Post-Harvest Crop Losses in Sub-Saharan Africa & South Asia',
    description: 'According to the UN Food and Agriculture Organization (FAO), approximately 30-40% of total food produced in developing regions is lost between harvest and consumption due to poor storage, lack of cold chains, and inadequate pest management.',
    sourceUrl: 'https://www.fao.org/food-loss-and-food-waste/en/',
    impactLevel: 9,
    categories: ['Agriculture & Food', 'Poverty & Inequality'],
    regions: ['Africa', 'South Asia', 'Global'],
    tags: ['Food Security', 'Supply Chain', 'Cold Chain', 'Post-Harvest Loss'],
  },
  {
    title: 'Groundwater Depletion & Over-Extraction in Arid Agricultural Basins',
    description: 'The World Bank reports that 82% of rural drinking water and 60% of agricultural irrigation in South Asia and the Middle East relies on rapidly depleting aquifers, with water tables dropping over 1 meter annually in critical food-producing regions.',
    sourceUrl: 'https://www.worldbank.org/en/topic/water',
    impactLevel: 10,
    categories: ['Water & Sanitation', 'Climate & Environment', 'Agriculture & Food'],
    regions: ['South Asia', 'Middle East', 'Global'],
    tags: ['Groundwater', 'Aquifer Depletion', 'Precision Irrigation', 'Water Scarcity'],
  },
  {
    title: 'Lack of Specialized Oncology Screening in Rural Primary Health Clinics',
    description: 'The World Health Organization (WHO) identifies that 70% of global cancer deaths occur in low- and middle-income countries, primarily because patients are diagnosed at advanced metastatic stages due to absent screening infrastructure in rural clinics.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/cancer',
    impactLevel: 9,
    categories: ['Healthcare'],
    regions: ['South Asia', 'Africa', 'Latin America'],
    tags: ['Cancer Screening', 'Rural Healthcare', 'Diagnostics', 'Preventive Health'],
  },
  {
    title: 'Foundational STEM Literacy Gaps in Emerging Market K-12 Classrooms',
    description: 'UNESCO estimates that over 600 million children worldwide fail to achieve minimum proficiency levels in reading and mathematics, with one-size-fits-all classroom pacing leaving students behind foundational conceptual milestones.',
    sourceUrl: 'https://www.unesco.org/en/education',
    impactLevel: 8,
    categories: ['Education'],
    regions: ['Global', 'South Asia', 'Africa'],
    tags: ['Foundational Learning', 'STEM Education', 'Pedagogy', 'Personalized Learning'],
  },
  {
    title: 'Industrial Scope 3 Carbon Reporting Friction for Tier-2/3 Suppliers',
    description: 'Under EU CSRD and global sustainability reporting standards, multinational corporations must disclose Scope 3 emissions; however, UNEP reports that over 85% of small and medium suppliers lack automated tools to calculate product-level carbon footprints.',
    sourceUrl: 'https://www.unep.org/explore-topics/climate-action',
    impactLevel: 8,
    categories: ['Climate & Environment', 'Waste Management'],
    regions: ['Europe', 'North America', 'Global'],
    tags: ['Carbon Accounting', 'Scope 3', 'Supply Chain', 'ESG Reporting'],
  },
  {
    title: 'Adversarial Prompt Injection & Data Leakage in Enterprise Generative AI',
    description: 'The OWASP Top 10 for LLMs ranks Prompt Injection as the #1 critical vulnerability in enterprise AI deployments, allowing untrusted external inputs to alter model behavior, bypass guardrails, and exfiltrate proprietary corporate data.',
    sourceUrl: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
    impactLevel: 8,
    categories: ['AI & Technology', 'Cybersecurity'],
    regions: ['North America', 'Europe', 'Global'],
    tags: ['AI Security', 'Prompt Injection', 'LLM Guardrails', 'Enterprise Safety'],
  },
  {
    title: 'PFAS "Forever Chemical" Bioaccumulation in Municipal Water Networks',
    description: 'The US EPA and European Environment Agency document that Per- and Polyfluoroalkyl Substances (PFAS) contaminate tap water systems serving over 100 million people, resisting natural decomposition and conventional municipal filtration.',
    sourceUrl: 'https://www.epa.gov/pfas',
    impactLevel: 9,
    categories: ['Water & Sanitation', 'Climate & Environment'],
    regions: ['North America', 'Europe'],
    tags: ['PFAS', 'Water Treatment', 'Nanofiltration', 'Public Health'],
  },
  {
    title: 'Electrical Grid Bottlenecks for Intermittent Renewable Integration',
    description: 'The International Energy Agency (IEA) highlights that over 1,500 gigawatts of wind and solar projects worldwide sit waiting in grid interconnection queues due to transmission capacity deficits and lack of sub-second battery dispatch software.',
    sourceUrl: 'https://www.iea.org/reports/electricity-grids-and-secure-energy-transitions',
    impactLevel: 9,
    categories: ['Energy', 'Climate & Environment'],
    regions: ['North America', 'Europe', 'East Asia'],
    tags: ['Grid Congestion', 'Renewable Energy', 'Virtual Power Plants', 'Battery Storage'],
  },
  {
    title: 'Antimicrobial Resistance (AMR) Outpacing Novel Drug Discovery',
    description: 'The WHO and Lancet studies confirm that drug-resistant bacterial pathogens directly cause 1.27 million deaths annually, with traditional small-molecule antibiotic development pipelines proving too slow and economically unviable.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance',
    impactLevel: 10,
    categories: ['Healthcare', 'AI & Technology'],
    regions: ['Global'],
    tags: ['AMR', 'Superbugs', 'Computational Biology', 'Peptide Design'],
  },
  {
    title: 'Cross-Border B2B Settlement Latency & FX Friction for African & Asian SMEs',
    description: 'The World Bank and WTO estimate that emerging market SMEs lose over $50 billion annually in correspondent banking fees, delayed liquidity, and predatory currency conversion spreads during cross-border trade.',
    sourceUrl: 'https://www.worldbank.org/en/topic/financialinclusion',
    impactLevel: 8,
    categories: ['Poverty & Inequality', 'Digital Access'],
    regions: ['Africa', 'South Asia', 'Southeast Asia'],
    tags: ['Cross-Border Payments', 'SME Trade', 'FX Hedging', 'Financial Inclusion'],
  },
  {
    title: 'Municipal Plastic Recycling Flake Sorting & Polymer Cross-Contamination',
    description: 'The UN Environment Programme (UNEP) reports that less than 9% of global plastic waste is successfully recycled, largely because mechanical sorting facilities cannot separate blended polymers like PET, PP, and HDPE at industrial conveyor speeds.',
    sourceUrl: 'https://www.unep.org/interactives/beat-plastic-pollution/',
    impactLevel: 9,
    categories: ['Waste Management', 'Climate & Environment'],
    regions: ['Global', 'Europe', 'North America'],
    tags: ['Plastic Recycling', 'Circular Economy', 'Hyperspectral Sorting', 'Polymers'],
  },
  {
    title: 'Severe Mental Health Specialist Shortages Across Sub-Saharan Africa',
    description: 'The WHO Mental Health Atlas documents that parts of Sub-Saharan Africa have fewer than 1 licensed psychiatrist per 1 million inhabitants, creating a massive treatment gap for youth experiencing severe emotional trauma and depression.',
    sourceUrl: 'https://www.who.int/publications/i/item/9789240036703',
    impactLevel: 8,
    categories: ['Healthcare', 'Poverty & Inequality'],
    regions: ['Africa'],
    tags: ['Mental Health', 'Telehealth', 'Community Care', 'CBT Support'],
  },
  {
    title: 'Empty Miles and Inefficient Multimodal Freight Capacity Utilization',
    description: 'The International Transport Forum (ITF) reveals that commercial road freight vehicles travel empty or underloaded approximately 20-25% of all journey kilometers, generating millions of tons of avoidable carbon emissions and freight congestion.',
    sourceUrl: 'https://www.itf-oecd.org/freight-transport',
    impactLevel: 7,
    categories: ['Transportation', 'Climate & Environment'],
    regions: ['Europe', 'North America', 'South Asia'],
    tags: ['Freight Efficiency', 'Logistics', 'Route Optimization', 'Empty Miles'],
  },
  {
    title: 'Expanded Polystyrene (Styrofoam) Packaging Microplastic Degradation',
    description: 'The Ocean Conservancy notes that single-use expanded polystyrene takes up to 500 years to decompose, fragmenting into toxic airborne and oceanic microplastics that penetrate marine wildlife and human food supplies.',
    sourceUrl: 'https://oceanconservancy.org/trash-free-seas/',
    impactLevel: 8,
    categories: ['Climate & Environment', 'Waste Management'],
    regions: ['Global'],
    tags: ['Microplastics', 'Single-Use Packaging', 'Biomaterials', 'Marine Conservation'],
  },
  {
    title: 'High-Priced Commercial Battery Swapping and EV Fleet Downtime',
    description: 'The International Council on Clean Transportation (ICCT) reports that commercial electric two- and three-wheelers in high-density Asian cities lose 25-35% of daily operating time when bound to conventional plug-in charging networks.',
    sourceUrl: 'https://theicct.org/sector/electric-vehicles/',
    impactLevel: 7,
    categories: ['Transportation', 'Energy', 'Climate & Environment'],
    regions: ['East Asia', 'South Asia', 'Southeast Asia'],
    tags: ['EV Fleets', 'Battery Swapping', 'Urban Mobility', 'Clean Transport'],
  },
  {
    title: 'Rural Unelectrified Agro-Processing Hubs Dependent on Diesel Generators',
    description: 'The International Renewable Energy Agency (IRENA) finds that over 600 million people in Sub-Saharan Africa live without reliable electrical grid access, forcing local grain milling and cold storage onto expensive, polluting diesel fuels.',
    sourceUrl: 'https://www.irena.org/Energy-Transition/Technology/Off-grid-renewables',
    impactLevel: 9,
    categories: ['Energy', 'Rural Development', 'Agriculture & Food'],
    regions: ['Africa', 'South Asia'],
    tags: ['Mini-Grids', 'Rural Electrification', 'Solar Energy', 'Agro-Processing'],
  },
  {
    title: 'Delayed Detection of Plant Pathogens in Resource-Constrained Smallholder Farming',
    description: 'The International Rice Research Institute (IRRI) documents that fungal and bacterial blights wipe out up to $30 billion in staple crop value annually when smallholder farmers lack immediate diagnostic tools in field environments.',
    sourceUrl: 'https://www.irri.org/crop-protection',
    impactLevel: 8,
    categories: ['Agriculture & Food', 'Rural Development'],
    regions: ['South Asia', 'Southeast Asia', 'Africa'],
    tags: ['Crop Disease', 'Plant Pathology', 'Computer Vision', 'Smallholders'],
  },
  {
    title: 'Indoor Air Quality Degradation and Commercial HVAC Energy Waste',
    description: 'The International Energy Agency notes that commercial heating, ventilation, and air conditioning (HVAC) accounts for roughly 40% of commercial building energy consumption, with static schedules failing to adapt to dynamic occupancy.',
    sourceUrl: 'https://www.iea.org/energy-system/buildings',
    impactLevel: 7,
    categories: ['Energy', 'Climate & Environment'],
    regions: ['Middle East', 'North America', 'East Asia'],
    tags: ['Building Efficiency', 'HVAC Optimization', 'Smart Buildings', 'Decarbonization'],
  },
  {
    title: 'Urban Water Distribution Losses Through Subsurface Pipe Leaks',
    description: 'The International Water Association (IWA) calculates that globally over 346 billion liters of treated drinking water are lost every day through aged, leaking municipal distribution networks before ever reaching consumer taps.',
    sourceUrl: 'https://iwa-network.org/programs/non-revenue-water/',
    impactLevel: 8,
    categories: ['Water & Sanitation', 'Rural Development'],
    regions: ['Global', 'South Asia', 'Latin America'],
    tags: ['Non-Revenue Water', 'Pipe Leak Detection', 'Acoustic Telemetry', 'Municipal Utilities'],
  },
  {
    title: 'Lack of Point-of-Care Metabolic Biomarker Testing in Primary Rural Health Centers',
    description: 'The Lancet Global Health highlights that basic metabolic and liver panel tests require centralized centrifuges and cold-stored reagents absent from 80% of rural sub-district clinics, leading to undetected chronic kidney disease.',
    sourceUrl: 'https://www.thelancet.com/journals/langlo/home',
    impactLevel: 8,
    categories: ['Healthcare', 'Rural Development'],
    regions: ['South Asia', 'Africa'],
    tags: ['Point-of-Care Diagnostics', 'Microfluidics', 'Chronic Disease', 'Primary Care'],
  },
  {
    title: 'Antibiotic Contamination & Drug Residue Runoff in Commercial Aquaculture',
    description: 'The FAO and UNEP warn that intensive fish and shrimp farming discharges thousands of metric tons of untreated antibiotic residues into coastal rivers, accelerating multi-drug microbial resistance in estuarine biomes.',
    sourceUrl: 'https://www.fao.org/aquaculture/en/',
    impactLevel: 9,
    categories: ['Agriculture & Food', 'Water & Sanitation'],
    regions: ['Southeast Asia', 'South Asia', 'Latin America'],
    tags: ['Aquaculture', 'Antibiotic Residues', 'Water Quality', 'Food Safety'],
  },
  {
    title: 'Ocean Acidification & Coral Reef Degradation Threatening Coastal Economies',
    description: 'UNESCO Intergovernmental Oceanographic Commission reports that atmospheric carbon absorption has dropped ocean pH by 0.1 units, degrading 50% of coral reefs and endangering seafood protein security for 500 million people.',
    sourceUrl: 'https://ioc.unesco.org/',
    impactLevel: 10,
    categories: ['Climate & Environment'],
    regions: ['Global', 'Asia-Pacific', 'Latin America'],
    tags: ['Ocean Acidification', 'Coral Reefs', 'Marine Biology', 'Blue Economy'],
  },
  {
    title: 'Extreme Urban Heat Island (UHI) Vulnerability in Dense Megacities',
    description: 'UN-Habitat documents that metropolitan centers in the Global South experience ambient temperatures up to 8°C higher than surrounding rural zones due to dense concrete cover and lack of urban canopy shading, triggering severe heat mortality.',
    sourceUrl: 'https://unhabitat.org/topic/climate-change-and-urban-environment',
    impactLevel: 8,
    categories: ['Climate & Environment', 'Energy'],
    regions: ['South Asia', 'Middle East', 'Latin America'],
    tags: ['Urban Heat', 'Cool Roofs', 'Climate Resilience', 'Urban Planning'],
  },
  {
    title: 'Toxic Heavy Metal Contamination from Informal E-Waste Dismantling',
    description: 'The International Telecommunication Union (ITU) Global E-Waste Monitor reports that less than 22% of 62 million tons of e-waste is formally collected, leaving informal backyard smelting in Ghana, Nigeria, and India to poison workers with lead, mercury, and cadmium.',
    sourceUrl: 'https://www.itu.int/hub/publication/d-gen-e_waste-01-2024/',
    impactLevel: 9,
    categories: ['Waste Management', 'Healthcare'],
    regions: ['Africa', 'South Asia'],
    tags: ['E-Waste', 'Circular Electronics', 'Hazardous Materials', 'Worker Health'],
  },
  {
    title: 'Inaccessible Agricultural Cold Chain Financing for Smallholder Farmer Producer Groups',
    description: 'The International Finance Corporation (IFC) estimates a $120 billion financing gap for decentralized agricultural cold storage and solar dryers, locking farmer groups into distress spot sales during harvest gluts.',
    sourceUrl: 'https://www.ifc.org/en/what-we-do/sector-expertise/agribusiness',
    impactLevel: 8,
    categories: ['Agriculture & Food', 'Poverty & Inequality'],
    regions: ['South Asia', 'Africa'],
    tags: ['Cold Storage', 'Agrifinance', 'Equipment Leasing', 'Harvest Gluts'],
  },
  {
    title: 'Methane Leaks & Subsurface Fires from Open Municipal Solid Waste Dumps',
    description: 'The Global Methane Initiative calculates that open municipal waste dumps in emerging markets emit over 1.6 gigatons of CO2-equivalent methane annually, frequently suffering uncontrollable subsurface landfill fires.',
    sourceUrl: 'https://www.globalmethane.org/sectors/waste.aspx',
    impactLevel: 9,
    categories: ['Waste Management', 'Climate & Environment'],
    regions: ['Latin America', 'South Asia', 'Africa'],
    tags: ['Landfill Methane', 'Biogas Recovery', 'Waste-to-Energy', 'Air Quality'],
  },
  {
    title: 'High-Youth Unemployment and Vocational Technical Skills Deficit',
    description: 'The International Labour Organization (ILO) notes that 1 in 5 young people globally are Not in Employment, Education, or Training (NEET), with educational curricula disconnected from modern industrial and digital skill requirements.',
    sourceUrl: 'https://www.ilo.org/global/topics/youth-employment/lang--en/index.htm',
    impactLevel: 8,
    categories: ['Education', 'Poverty & Inequality'],
    regions: ['Global', 'Africa', 'South Asia'],
    tags: ['Youth Employment', 'Vocational Skills', 'Future of Work', 'Apprenticeships'],
  },
  {
    title: 'Preventable Maternal Mortality in Remote Sub-District Clinics',
    description: 'The World Health Organization (WHO) and UNFPA estimate that roughly 800 women die every day from preventable complications related to pregnancy and childbirth, with 95% of these deaths occurring in low and lower-middle-income countries.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/maternal-mortality',
    impactLevel: 9,
    categories: ['Healthcare', 'Rural Development'],
    regions: ['Africa', 'South Asia'],
    tags: ['Maternal Health', 'Obstetric Care', 'Telemedicine', 'Rural Health'],
  },
  {
    title: 'Household Air Pollution Exposure from Solid Fuel Cooking Stoves',
    description: 'The WHO attributes over 3.2 million premature deaths each year to household air pollution caused by cooking with polluting open fires and simple biomass or kerosene stoves, disproportionately affecting women and young children.',
    sourceUrl: 'https://www.who.int/news-room/fact-sheets/detail/household-air-pollution-and-health',
    impactLevel: 9,
    categories: ['Energy', 'Healthcare'],
    regions: ['Sub-Saharan Africa', 'South Asia'],
    tags: ['Clean Cooking', 'Indoor Air Pollution', 'Biomass Stoves', 'Women Health'],
  },
  {
    title: 'Early Warning Disconnects for Cyclone and Flash Flood Vulnerable Coastal Deltas',
    description: 'The UN Disaster Risk Reduction (UNDRR) Early Warnings for All initiative reports that 1 in 3 people globally are still not covered by multi-hazard early warning systems, resulting in catastrophic life loss during sudden extreme weather events.',
    sourceUrl: 'https://www.undrr.org/early-warnings-for-all',
    impactLevel: 9,
    categories: ['Climate & Environment', 'Digital Access'],
    regions: ['South Asia', 'Southeast Asia', 'Africa'],
    tags: ['Early Warning Systems', 'Disaster Resilience', 'Cyclone Tracking', 'Flood Prediction'],
  },
  {
    title: 'Double-Counting and Quality Deficits in Voluntary Carbon Offsets',
    description: 'The World Bank State and Trends of Carbon Pricing report finds that voluntary carbon markets suffer from opaque additionality metrics, registry fragmentation, and high brokerage markups that prevent climate capital from reaching real projects.',
    sourceUrl: 'https://openknowledge.worldbank.org/handle/10986/39792',
    impactLevel: 8,
    categories: ['Climate & Environment', 'AI & Technology'],
    regions: ['Global'],
    tags: ['Carbon Markets', 'MRV Verification', 'Satellite Monitoring', 'Additionality'],
  },
  {
    title: 'Agricultural Soil Salinization Threatening Breadbasket Deltas',
    description: 'The FAO Global Soil Partnership reports that over 1 billion hectares of agricultural land are affected by soil salinization due to poor irrigation drainage and sea level intrusion, causing up to 50% yield drops in staple crops.',
    sourceUrl: 'https://www.fao.org/global-soil-partnership/intergovernmental-technical-panel-soils/gsas-map/en/',
    impactLevel: 9,
    categories: ['Agriculture & Food', 'Water & Sanitation'],
    regions: ['South Asia', 'Middle East', 'North Africa'],
    tags: ['Soil Salinity', 'Desalination', 'Halophyte Crops', 'Drainage Management'],
  },
  {
    title: 'Predatory High-Interest Digital Micro-Lending in Developing Markets',
    description: 'The Consultative Group to Assist the Poor (CGAP) documents widespread predatory digital lending apps charging upwards of 300% annualized interest rates and engaging in aggressive debtor harassment, exacerbating rural insolvency.',
    sourceUrl: 'https://www.cgap.org/research/publication/digital-credit-market-monitoring',
    impactLevel: 8,
    categories: ['Poverty & Inequality', 'Digital Access'],
    regions: ['South Asia', 'Africa'],
    tags: ['Digital Lending', 'Consumer Protection', 'Financial Inclusion', 'Ethical Credit'],
  },
  {
    title: 'Cybersecurity Vulnerabilities in Aging Municipal Water and Power SCADA Networks',
    description: 'The US Cybersecurity and Infrastructure Security Agency (CISA) and WEF alert that critical water treatment plants and energy substations rely on legacy industrial control systems (ICS) lacking multi-factor authentication or network isolation.',
    sourceUrl: 'https://www.cisa.gov/topics/industrial-control-systems',
    impactLevel: 9,
    categories: ['Cybersecurity', 'Energy'],
    regions: ['North America', 'Europe', 'Global'],
    tags: ['SCADA Security', 'Critical Infrastructure', 'Zero Trust', 'Industrial IoT'],
  },
  {
    title: 'Severe Assistive Technology Access Deficit for Persons with Disabilities',
    description: 'The WHO and UNICEF Global Report on Assistive Technology estimates that over 2.5 billion people need assistive products (hearing aids, prosthetics, screen readers), but less than 10% in developing countries have access due to prohibitive costs.',
    sourceUrl: 'https://www.who.int/publications/i/item/9789240049451',
    impactLevel: 8,
    categories: ['Healthcare', 'Education'],
    regions: ['Global', 'South Asia', 'Africa'],
    tags: ['Assistive Technology', 'Accessibility', 'Inclusion', 'Affordable Prosthetics'],
  },
];

