export const seedStartups = [
  {
    founderEmail: 'sarah.chen@aiagri.io',
    name: 'AgroPulse',
    logo: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'AI-driven agronomic intelligence and localized weather advisory for smallholder farmers.',
    problem: 'Smallholder farmers in climate-vulnerable zones lose 30-40% of crop yields annually due to unpredictable microclimates, delayed pest outbreaks, and lack of localized agronomic guidance.',
    solution: 'Hyper-localized precision advisory combining satellite multispectral imagery, hyper-local IoT moisture probes, and LLM-powered multilingual voice guidance delivered via WhatsApp and SMS.',
    targetCustomers: 'Cooperative farming unions, agricultural input distributors, and smallholder farmers across South Asia and East Africa.',
    industry: 'AgriTech',
    businessModel: 'B2B2C Subscription & Cooperative Licensing',
    stage: 'MVP',
    location: 'Austin, TX, USA',
    requiredSkills: 'Full-Stack Engineering, Computer Vision, Embedded IoT, Agronomy, Multilingual NLP',
    fundingStatus: 'Bootstrapped',
    fundingRequired: '$350,000 for field pilot deployment and edge-sensor manufacturing',
    currentTraction: 'Piloted with 1,200 farmers in Telangana & Maharashtra with 22% yield improvement in season 1.',
    website: 'https://agropulse.demo.startupz.com',
    demoLink: 'https://demo.agropulse.io',
    pitchDeckUrl: 'https://docsend.com/view/agropulse-deck-demo',
    images: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&auto=format&fit=crop&q=80,https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=800&auto=format&fit=crop&q=80',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 38,
    viewsCount: 420,
    followersCount: 52,
    members: [
      { email: 'marcus.dev@codeflow.dev', role: 'Technical Co-Founder' },
      { email: 'priya.design@pixelcraft.studio', role: 'Head of Product Design' },
    ],
  },
  {
    founderEmail: 'rohan.kapoor@finsync.io',
    name: 'FinSync Global',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Automated treasury operations and liquidity orchestration for cross-border African and Asian SMEs.',
    problem: 'Emerging market cross-border merchants lose 4-7% on currency spreads and endure 3-5 day settlement latencies when conducting bilateral trade.',
    solution: 'Multi-currency virtual escrow, automated FX hedging, and instant local settlement corridors powered by open banking APIs and unified ledgers.',
    targetCustomers: 'Export-import firms, regional e-commerce merchants, and B2B wholesale distributors in India, UAE, and Kenya.',
    industry: 'FinTech',
    businessModel: 'Transaction Fee (0.25% - 0.45% per settled trade volume)',
    stage: 'Early Revenue',
    location: 'Mumbai, Maharashtra, India',
    requiredSkills: 'Banking API Integrations, Payment Security, Compliance & AML, React Native, Golang',
    fundingStatus: 'Pre-Seed',
    fundingRequired: '$500,000 for banking corridors and regulatory licensing',
    currentTraction: '$1.4M monthly settled volume across 85 active B2B merchants with zero fraud chargebacks.',
    website: 'https://finsync.demo.startupz.com',
    demoLink: 'https://app.finsync.demo',
    pitchDeckUrl: 'https://docsend.com/view/finsync-pitch',
    images: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 45,
    viewsCount: 512,
    followersCount: 68,
    members: [
      { email: 'kavya.nair@talentloom.ai', role: 'VP of Growth & Partnerships' },
    ],
  },
  {
    founderEmail: 'ananya.rao@medivault.health',
    name: 'MediVault AI',
    logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Zero-knowledge federated learning platform for distributed clinical trial biomarker discovery.',
    problem: 'Hospitals cannot collaborate on rare disease oncology cohorts because HIPAA, GDPR, and data sovereignity laws prevent patient electronic records from leaving hospital premises.',
    solution: 'Federated machine learning algorithms train inside local hospital firewalls and aggregate mathematical weights centrally using cryptographic differential privacy.',
    targetCustomers: 'Research hospitals, oncology academic medical centers, and biopharma therapeutic developers.',
    industry: 'HealthTech',
    businessModel: 'Annual Enterprise SaaS + Revenue Share on Discovered Therapeutic Patents',
    stage: 'Validation',
    location: 'Boston, MA, USA',
    requiredSkills: 'Differential Privacy, Federated Learning, PyTorch, HIPAA Security, Medical Imaging',
    fundingStatus: 'Pre-Seed',
    fundingRequired: '$750,000 for FDA software validation and multicenter deployment',
    currentTraction: '3 institutional IRB approvals secured across tier-1 university oncology networks.',
    website: 'https://medivault.demo.startupz.com',
    pitchDeckUrl: 'https://docsend.com/view/medivault-demo',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 29,
    viewsCount: 340,
    followersCount: 41,
    members: [
      { email: 'julian.vance@aihealth.co', role: 'Founding ML Engineer' },
    ],
  },
  {
    founderEmail: 'sofia.martinez@hydrosense.ai',
    name: 'HydroSense Technologies',
    logo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Industrial acoustic ultrasonic sensing and AI anomaly detection for municipal freshwater networks.',
    problem: 'Municipal utilities lose up to 35% of treated drinking water through subsurface pipeline leaks before water reaches end consumers.',
    solution: 'Non-invasive acoustic clamp-on telemetry nodes that listen to pipe vibrations and pinpoint subsurface leaks within 0.5 meters using wave-equation neural networks.',
    targetCustomers: 'Municipal water authorities, smart city operators, and industrial cooling loop facilities.',
    industry: 'CleanTech',
    businessModel: 'Hardware-enabled SaaS (Annual utility subscription per kilometer monitored)',
    stage: 'Prototype',
    location: 'Hyderabad, Telangana, India',
    requiredSkills: 'Acoustic Signal Processing, Embedded C++, LoRaWAN, Digital Signal Microcontrollers',
    fundingStatus: 'Bootstrapped',
    fundingRequired: '$300,000 for casing tooling and initial 500-node sensor manufacturing run',
    currentTraction: 'Pilot installation on 12km municipal pipeline with 94% leak localization accuracy.',
    website: 'https://hydrosense.demo.startupz.com',
    pitchDeckUrl: 'https://docsend.com/view/hydrosense-demo',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 33,
    viewsCount: 290,
    followersCount: 37,
    members: [
      { email: 'alex.becker@devops.de', role: 'Platform Architect' },
    ],
  },
  {
    founderEmail: 'ethan.brooks@voltmesh.energy',
    name: 'VoltMesh Energy',
    logo: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Decentralized peer-to-peer microgrid arbitrage and virtual power plant aggregation.',
    problem: 'Intermittent commercial rooftop solar and battery assets sit idle during grid curtailments while neighboring facilities pay peak grid demand charges.',
    solution: 'Autonomous software coordinating sub-second energy dispatch, battery discharge scheduling, and automated smart-contract compensation across local industrial clusters.',
    targetCustomers: 'Industrial parks, university campuses, and commercial real estate portfolio operators.',
    industry: 'CleanTech',
    businessModel: 'Software cut (15% of net avoided electricity tariff savings)',
    stage: 'MVP',
    location: 'Denver, CO, USA',
    requiredSkills: 'Smart Grid Standards (IEEE 2030.5), Rust, Time-series Forecasting, SCADA Protocols',
    fundingStatus: 'Seed',
    fundingRequired: '$1,200,000 for utility interconnection compliance and commercial sales team',
    currentTraction: '4.2 MW capacity under automated software orchestration across 6 commercial business parks.',
    website: 'https://voltmesh.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 41,
    viewsCount: 460,
    followersCount: 58,
    members: [
      { email: 'chloe.dubois@trialmatch.bio', role: 'VP Grid Engineering' },
    ],
  },
  {
    founderEmail: 'aisha.rahman@edugenie.org',
    name: 'EduGenie',
    logo: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Cognitive diagnostic AI tutor adapting in real-time to K-12 student misconception pathways.',
    problem: 'Traditional classroom instruction moves at a single pace, leaving 65% of students with fundamental gaps in foundational STEM comprehension.',
    solution: 'Voice-interactive Socratic tutor that constructs dynamic knowledge graphs for every learner, detecting precise mathematical misconceptions and generating custom analogical explanations.',
    targetCustomers: 'Affordable private schools, tutoring networks, and state educational boards.',
    industry: 'EdTech',
    businessModel: 'Freemium consumer tier ($9/mo) and institutional school licensing ($4/student/year)',
    stage: 'MVP',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Conversational LLMs, Socratic Prompt Engineering, Next.js, Child Psychology, Gamification',
    fundingStatus: 'Bootstrapped',
    fundingRequired: '$250,000 for expanding multilingual regional language audio models',
    currentTraction: '14,000 monthly active student learners with 3.4x higher concept retention scores.',
    website: 'https://edugenie.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 52,
    viewsCount: 580,
    followersCount: 74,
    members: [
      { email: 'meera.nair@uxcraft.design', role: 'Head of Learning Experience Design' },
    ],
  },
  {
    founderEmail: 'daniel.carter@tracecraft.supply',
    name: 'TraceCraft',
    logo: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Automated Scope 3 supply chain carbon accounting and supplier primary emission auditing.',
    problem: 'Enterprise compliance deadlines (CSRD, SEC Climate Rules) require verified supplier emission tracking, but 90% of suppliers cannot provide primary activity-based carbon audits.',
    solution: 'API-first supplier portal using automated ERP invoice ingestion and lifecycle assessment emission engines to calculate true carbon footprints per SKU without manual consultant audits.',
    targetCustomers: 'Mid-to-large European and US apparel, food, and manufacturing conglomerates.',
    industry: 'ClimateTech',
    businessModel: 'Annual SaaS subscription based on supply chain SKU count ($25K–$120K/yr)',
    stage: 'Early Revenue',
    location: 'Madrid, Spain',
    requiredSkills: 'ERP Integrations (SAP, NetSuite), GHG Protocol Auditing, Python, React, Data Pipelines',
    fundingStatus: 'Seed',
    fundingRequired: '$1,500,000 to accelerate European enterprise sales and US market launch',
    currentTraction: '€340K ARR across 14 enterprise logos auditing over 8,000 upstream tier-1 suppliers.',
    website: 'https://tracecraft.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 36,
    viewsCount: 390,
    followersCount: 49,
    members: [],
  },
  {
    founderEmail: 'tariq.mansoor@cybermesh.io',
    name: 'CyberMesh',
    logo: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Automated adversarial AI red-teaming and prompt-injection firewall for enterprise LLMs.',
    problem: 'Enterprises deploying generative AI agents risk customer data exfiltration, system prompt extraction, and unauthorized API tool abuse via indirect prompt injection.',
    solution: 'Continuous synthetic penetration testing and ultra-low-latency (<8ms) inline neural proxy that neutralizes adversarial jailbreaks and prevents unauthorized tool calls.',
    targetCustomers: 'FinTech, healthcare, and enterprise software companies deploying customer-facing AI agents.',
    industry: 'CyberSecurity',
    businessModel: 'Usage-based API pricing ($0.0004 per inspected inference token) + Enterprise SLA',
    stage: 'Early Revenue',
    location: 'San Francisco, CA, USA',
    requiredSkills: 'LLM Security, Adversarial Red-Teaming, Rust, eBPF, Low-Latency Networking',
    fundingStatus: 'Pre-Seed',
    fundingRequired: '$850,000 for expanding threat research lab and enterprise sales expansion',
    currentTraction: 'Protecting 45M daily inference requests across 22 production AI agent architectures.',
    website: 'https://cybermesh.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 48,
    viewsCount: 620,
    followersCount: 81,
    members: [
      { email: 'alex.becker@devops.de', role: 'Staff Security Engineer' },
    ],
  },
  {
    founderEmail: 'chen.wei@optilog.tech',
    name: 'OptiLog AI',
    logo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Predictive multimodal route and cargo bin packing optimization for intermodal freight.',
    problem: 'Truckload carriers operate at 22% empty trailer capacity due to mismatched freight schedules, driving up fuel waste and transport costs.',
    solution: 'Real-time 3D algorithmic cargo consolidation, cross-carrier freight pool matching, and predictive route assignment using combinatorial optimization.',
    targetCustomers: '3PL logistics operators, freight forwarders, and private fleet operators.',
    industry: 'Logistics',
    businessModel: 'SaaS Platform fee + Shared savings percentage on fuel efficiency gains',
    stage: 'Validation',
    location: 'London, UK',
    requiredSkills: 'Operations Research, 3D Packing Algorithms, GIS Spatial Routing, Python, WebGL',
    fundingStatus: 'Pre-Seed',
    fundingRequired: '$400,000 for live fleet telematics integrations',
    currentTraction: 'Simulation trials with 4 logistics providers demonstrated 18% fuel cost reductions.',
    website: 'https://optilog.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: false,
    likesCount: 24,
    viewsCount: 270,
    followersCount: 30,
    members: [],
  },
  {
    founderEmail: 'amara.okafor@femisave.africa',
    name: 'FemiSave Health',
    logo: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Affordable point-of-care cervical cancer and maternal wellness screening for tier-2/3 regions.',
    problem: 'Over 70,000 women in rural India and Africa succumb to cervical cancer annually due to lack of accessible early diagnostic oncologists in rural primary health clinics.',
    solution: 'Portable optical imaging hardware paired with offline edge AI classification that identifies pre-cancerous lesions in under 3 minutes for less than $3 per test.',
    targetCustomers: 'Rural primary healthcare clinics, state health missions, and non-profit health foundations.',
    industry: 'HealthTech',
    businessModel: 'Pay-per-scan medical hardware lease with consumable testing kits',
    stage: 'Prototype',
    location: 'Chennai, Tamil Nadu, India',
    requiredSkills: 'Biomedical Optics, Edge ML (TensorFlow Lite), Flutter, Clinical Trial Coordination',
    fundingStatus: 'Grant Funded',
    fundingRequired: '$450,000 for CDSCO medical device clinical certification',
    currentTraction: 'Completed 3,200 screenings in public hospital clinical study with 96.2% sensitivity.',
    website: 'https://femisave.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 56,
    viewsCount: 710,
    followersCount: 88,
    members: [
      { email: 'radhika.swami@mentorship.org', role: 'Clinical Strategy Advisor' },
    ],
  },
  {
    founderEmail: 'lucas.meyer@mindhaven.care',
    name: 'MindHaven Health',
    logo: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Culturally attuned digital mental health and peer counseling network for young African professionals.',
    problem: 'Mental health stigma and a severe deficit of licensed therapists (1 psychiatrist per 1M people in parts of Sub-Saharan Africa) leave youth without emotional support.',
    solution: 'Anonymous peer-support pods, evidence-based CBT micro-modules, and localized telemedicine matching with African diaspora clinical psychologists.',
    targetCustomers: 'Tech workers, university students, and enterprise employer wellbeing programs across Lagos, Nairobi, and Accra.',
    industry: 'HealthTech',
    businessModel: 'B2B Enterprise Wellbeing Subscriptions & Affordable Consumer Micro-sessions',
    stage: 'MVP',
    location: 'Lagos, Nigeria',
    requiredSkills: 'Clinical CBT, Telehealth Protocols, React Native, Community Moderation, HIPAA Compliance',
    fundingStatus: 'Bootstrapped',
    fundingRequired: '$200,000 for therapist network expansion and localized audio language support',
    currentTraction: '6,400 monthly active users across Nigeria and Kenya with 88% satisfaction rate.',
    website: 'https://mindhaven.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 39,
    viewsCount: 410,
    followersCount: 53,
    members: [],
  },
  {
    founderEmail: 'vikram.malhotra@zenithai.dev',
    name: 'ZenithAI Studio',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Controllable generative video and physics-consistent 3D environment synthesis for game studios.',
    problem: 'Indie game studios spend up to 60% of their production budget manually rigging, texturing, and animating secondary 3D assets and dynamic cinematics.',
    solution: 'Diffusion-based 3D neural asset pipeline that transforms 2D concept art into fully rigged, physics-consistent 3D assets ready for Unreal Engine 5 and Unity.',
    targetCustomers: 'Mid-sized game developers, virtual production studios, and metaverse world builders.',
    industry: 'DeepTech',
    businessModel: 'Tiered Studio SaaS Subscription ($499/mo - $2,500/mo) + GPU compute credits',
    stage: 'MVP',
    location: 'Singapore',
    requiredSkills: 'NeRF, Gaussian Splatting, PyTorch, C++, Unreal Engine 5 Plugins, WebGL',
    fundingStatus: 'Seed',
    fundingRequired: '$1,800,000 for GPU cluster scaling and proprietary geometry model training',
    currentTraction: '18 game studio beta partners with 75,000 3D assets generated in closed alpha.',
    website: 'https://zenithai.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 62,
    viewsCount: 890,
    followersCount: 110,
    members: [
      { email: 'marcus.dev@codeflow.dev', role: 'Graphics & Engine Integration Advisor' },
    ],
  },
  {
    founderEmail: 'aisha.bello@reverseloop.co',
    name: 'ReverseLoop',
    logo: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Automated optical sorting and spectral polymer identification for circular plastics recycling.',
    problem: 'Mechanical recycling facilities reject up to 50% of incoming plastic waste because mixed polymers (PET, HDPE, PP, multilayer films) cannot be separated at conveyor speeds.',
    solution: 'High-speed near-infrared (NIR) hyperspectral vision system coupled with air-jet pneumatic ejectors that sorts 8 distinct plastic polymers at 14 tons per hour.',
    targetCustomers: 'Municipal material recovery facilities (MRFs), plastic recyclers, and consumer goods packaging manufacturers.',
    industry: 'ClimateTech',
    businessModel: 'Hardware sales with annual predictive maintenance software contract',
    stage: 'Prototype',
    location: 'Munich, Germany',
    requiredSkills: 'Hyperspectral Imaging, Industrial Automation, PLC Programming, High-Speed Edge Compute',
    fundingStatus: 'Pre-Seed',
    fundingRequired: '$900,000 for commercial demonstration sorting line construction',
    currentTraction: 'Validated 98.4% polymer separation purity in bench-scale industrial test trials.',
    website: 'https://reverseloop.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 31,
    viewsCount: 320,
    followersCount: 42,
    members: [],
  },
  {
    founderEmail: 'rohit.verma@finops.ai',
    name: 'AquaPure Solar',
    logo: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Zero-electricity solar-thermal desalination and purification units for coastal rural communities.',
    problem: 'Over 2 billion people worldwide drink water contaminated with salinity, arsenic, or pathogens, and reverse osmosis plants require expensive grid electricity and membranes.',
    solution: 'Multi-stage solar vacuum distillation units manufactured from locally repairable components, purifying 500 liters of saline/brackish water per day without external electricity.',
    targetCustomers: 'Gram panchayats, coastal farming cooperatives, and international humanitarian relief NGOs.',
    industry: 'CleanTech',
    businessModel: 'Community Micro-Utility model (0.01 USD/liter) & Direct NGO procurement',
    stage: 'MVP',
    location: 'Pune, Maharashtra, India',
    requiredSkills: 'Solar Thermal Engineering, Fluid Dynamics, Distributed Field Operations, Rural Governance',
    fundingStatus: 'Bootstrapped',
    fundingRequired: '$200,000 for village pilot deployment across 15 coastal villages in Gujarat',
    currentTraction: 'Operating 3 pilot units providing continuous safe drinking water to 950 villagers.',
    website: 'https://aquapure.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: false,
    likesCount: 27,
    viewsCount: 280,
    followersCount: 33,
    members: [],
  },
  {
    founderEmail: 'samantha.hayes@biomaterials.io',
    name: 'EcoWrap Packaging',
    logo: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Marine-biodegradable mycelium and seaweed protective packaging replacing expanded polystyrene.',
    problem: 'Single-use Styrofoam takes 500+ years to degrade and fragments into toxic microplastics that poison marine ecosystems and enter human food chains.',
    solution: 'Home-compostable packaging made from farmed kelp extracts and agricultural hemp byproduct, offering identical thermal and impact resistance at price parity with EPS.',
    targetCustomers: 'Electronics brands, luxury wine distributors, and cold-chain pharmaceutical shipping.',
    industry: 'CleanTech',
    businessModel: 'Wholesale B2B manufacturing supply contracts per cubic meter',
    stage: 'MVP',
    location: 'Seattle, WA, USA',
    requiredSkills: 'Biomaterials Science, Mycelium Cultivation, Thermoforming, Supply Chain Logistics',
    fundingStatus: 'Pre-Seed',
    fundingRequired: '$650,000 for automated bio-molding production pilot facility',
    currentTraction: 'LOIs signed with 2 consumer electronics brands for 250,000 packaging units.',
    website: 'https://ecowrap.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 44,
    viewsCount: 470,
    followersCount: 60,
    members: [],
  },
  {
    founderEmail: 'gabriel.santos@agrisat.io',
    name: 'SaharaFlow',
    logo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Atmospheric water generation powered by thermal solar collectors for arid desert agriculture.',
    problem: 'Deserts and semi-arid zones suffer acute water scarcity, making high-value horticulture impossible despite abundant solar irradiance.',
    solution: 'Metal-Organic Framework (MOF) thermal adsorption panels that extract drinking and irrigation water directly from low-humidity desert air using natural diurnal temperature swings.',
    targetCustomers: 'High-value date and greenhouse crop producers in North Africa, Middle East, and Arizona.',
    industry: 'AgriTech',
    businessModel: 'Water-as-a-Service (guaranteed cubic meters of water delivered daily)',
    stage: 'Validation',
    location: 'Lisbon, Portugal',
    requiredSkills: 'Materials Science, MOFs, Thermodynamics, Renewable Energy Systems',
    fundingStatus: 'Seed',
    fundingRequired: '$1,100,000 for field prototype scale-up in Morocco and southern Spain',
    currentTraction: 'Achieved 4.8 liters of water per kilogram of adsorbent in controlled arid chamber testing.',
    website: 'https://saharaflow.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 35,
    viewsCount: 380,
    followersCount: 46,
    members: [],
  },
  {
    founderEmail: 'fatima.zahra@solarirrigation.ma',
    name: 'AgriRobotix',
    logo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Low-cost autonomous solar weeding and laser pest control rovers for cassava and maize fields.',
    problem: 'Herbicide resistance and manual hand-weeding require 200+ hours of backbreaking labor per hectare, while chemical runoff degrades soil biology.',
    solution: 'Autonomous 4-wheel rover powered by dual 400W solar canopies, using lightweight edge neural networks to detect weeds and mechanically uproot them without herbicides.',
    targetCustomers: 'Smallholder farmer cooperatives and contract farming aggregators.',
    industry: 'AgriTech',
    businessModel: 'Robotics-as-a-Service (per-hectare seasonal weeding service fee)',
    stage: 'Prototype',
    location: 'Abuja, Nigeria',
    requiredSkills: 'Robotics, Autonomous Navigation (ROS2), Computer Vision, Field Mechanics',
    fundingStatus: 'Grant Funded',
    fundingRequired: '$300,000 for manufacturing 20 rover fleet units for commercial deployment',
    currentTraction: 'Successfully weeded 45 hectares in trial plots with 92% weed eradication efficiency.',
    website: 'https://agrirobotix.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: false,
    likesCount: 28,
    viewsCount: 310,
    followersCount: 34,
    members: [],
  },
  {
    founderEmail: 'kavya.nair@talentloom.ai',
    name: 'PathFinder Edu',
    logo: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'AI apprenticeship marketplace connecting vocational students with real-world engineering gigs.',
    problem: 'Engineering and polytechnic college graduates lack verifiable project experience, while fast-growing startups struggle to hire affordable technical talent.',
    solution: 'Cohort-based apprenticeship matching where students build real-world open-source features under vetted tech leads, earning verifiable skill credentials and stipends.',
    targetCustomers: 'Tier-2/3 engineering colleges, tech startups, and mid-sized software agencies.',
    industry: 'EdTech',
    businessModel: 'Hiring placement fee (10% of first-year salary) + University partnership subscriptions',
    stage: 'Early Revenue',
    location: 'Delhi, India',
    requiredSkills: 'Platform Engineering, React, Node.js, Educational Assessment, Community Ops',
    fundingStatus: 'Bootstrapped',
    fundingRequired: '$400,000 to expand company hiring network across India and Southeast Asia',
    currentTraction: 'Placed 420 apprentices across 65 startups with an average hiring conversion of 68%.',
    website: 'https://pathfinder.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 42,
    viewsCount: 490,
    followersCount: 65,
    members: [],
  },
  {
    founderEmail: 'chloe.dubois@trialmatch.bio',
    name: 'NanoFilter Water',
    logo: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Graphene-oxide membrane filtration eliminating PFAS forever chemicals from municipal tap water.',
    problem: 'PFAS and microplastic contaminants permeate 45% of US and European public water systems, resisting conventional charcoal and chlorine treatment.',
    solution: 'Tunable nanoporous graphene oxide membrane cartridges that reject 99.8% of long and short-chain PFAS molecules with 4x less backpressure than reverse osmosis.',
    targetCustomers: 'Municipal water treatment plants, beverage manufacturers, and residential filter brands.',
    industry: 'CleanTech',
    businessModel: 'Direct Membrane Cartridge Supply & Licensing to OEM Filter Manufacturers',
    stage: 'Validation',
    location: 'Paris, France',
    requiredSkills: 'Nanomaterials, Chemical Engineering, Membrane Science, Industrial Filtration',
    fundingStatus: 'Seed',
    fundingRequired: '$2,000,000 for roll-to-roll membrane manufacturing line setup',
    currentTraction: 'Certified third-party lab testing confirming 99.8% PFAS removal at 10 bar pressure.',
    website: 'https://nanofilter.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 49,
    viewsCount: 540,
    followersCount: 72,
    members: [],
  },
  {
    founderEmail: 'kenji.sato@gridlogic.jp',
    name: 'FleetZero Mobility',
    logo: 'https://images.unsplash.com/photo-1558441719-8b459c86f6c0?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Modular battery swap networks and telemetry for commercial electric two and three-wheelers.',
    problem: 'Last-mile delivery riders lose 3 hours of peak daily delivery time waiting at slow EV charging stations, reducing their earning potential by 30%.',
    solution: 'Automated 45-second battery swapping kiosks with intelligent state-of-health battery balancing algorithms and pay-as-you-go subscription app.',
    targetCustomers: 'Gig delivery drivers, e-commerce fleet operators (Amazon, Foodpanda, Zomato).',
    industry: 'CleanTech',
    businessModel: 'Energy-as-a-service subscription ($40/month for unlimited swap cycles)',
    stage: 'Early Revenue',
    location: 'Tokyo, Japan',
    requiredSkills: 'Battery Management Systems (BMS), IoT Telematics, Embedded Firmware, Android App Dev',
    fundingStatus: 'Seed',
    fundingRequired: '$1,500,000 for expanding kiosk footprint in Jakarta and Bangkok',
    currentTraction: '38 swap stations deployed, 1,400 active commercial riders, 85,000 swaps completed to date.',
    website: 'https://fleetzero.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 55,
    viewsCount: 680,
    followersCount: 95,
    members: [],
  },
  {
    founderEmail: 'tunde.adeleke@remitrail.africa',
    name: 'SolarGrid Micro',
    logo: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Pay-as-you-go containerized solar mini-grids for unelectrified agro-processing rural hubs.',
    problem: 'Over 85 million Nigerians lack access to the electrical grid, forcing rural grain mills and cold storage to rely on expensive, polluting diesel generators.',
    solution: 'Rapid-deploy containerized 50kW solar + lithium energy storage stations with smart mobile-money meters powering rural grain mills and communal refrigeration.',
    targetCustomers: 'Rural market associations, farming cooperatives, and local micro-enterprises.',
    industry: 'CleanTech',
    businessModel: 'Pay-as-you-go tariff via USSD/Mobile Money ($0.22 per kWh generated)',
    stage: 'Early Revenue',
    location: 'Ibadan, Nigeria',
    requiredSkills: 'High-Voltage Inverters, Microgrid SCADA, GSM Smart Metering, Community Engagement',
    fundingStatus: 'Seed',
    fundingRequired: '$800,000 for manufacturing 10 additional mini-grid hubs',
    currentTraction: '6 mini-grids in full operation powering 480 small businesses with 99.2% uptime.',
    website: 'https://solargrid.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 37,
    viewsCount: 430,
    followersCount: 54,
    members: [],
  },
  {
    founderEmail: 'radhika.swami@mentorship.org',
    name: 'SafeHealth Diagnostic',
    logo: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Paper-based microfluidic lateral flow strips with smartphone diagnostic optical quantification.',
    problem: 'Routine blood panel biochemistry tests (kidney, liver, electrolyte biomarkers) require expensive centralized laboratory centrifuges absent in primary rural health centers.',
    solution: 'Multiplexed microfluidic paper test strips that evaluate 6 key metabolic biomarkers from a single blood fingerprick in 5 minutes, quantified by smartphone camera optical analysis.',
    targetCustomers: 'Primary healthcare centers (PHCs), mobile medical vans, and community health workers (ASHAs).',
    industry: 'HealthTech',
    businessModel: 'Sale of single-use test strips ($0.75 each) + Free clinic diagnostic companion app',
    stage: 'MVP',
    location: 'Bengaluru, Karnataka, India',
    requiredSkills: 'Microfluidics, Computer Vision Calibration, Smartphone App Dev, Regulatory IVD Pathways',
    fundingStatus: 'Grant Funded',
    fundingRequired: '$500,000 for high-volume automated strip manufacturing equipment',
    currentTraction: 'Evaluated in 2,500 patient field tests with 95% correlation to standard hospital venous blood analyzers.',
    website: 'https://safehealth.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 50,
    viewsCount: 590,
    followersCount: 78,
    members: [],
  },
  {
    founderEmail: 'julian.vance@aihealth.co',
    name: 'BioShield Therapeutics',
    logo: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Generative protein design models for rapid peptide therapeutic neutralization of antimicrobial pathogens.',
    problem: 'Multi-drug resistant superbugs cause over 1.2 million deaths annually, and developing traditional small-molecule antibiotics takes over a decade.',
    solution: 'Diffusion-guided de novo antimicrobial peptide generation predicting tertiary folded structures and bacterial membrane pore formation in seconds.',
    targetCustomers: 'Biopharma drug discovery divisions, academic infectious disease labs, and defense agencies.',
    industry: 'HealthTech',
    businessModel: 'Co-development milestones + Royalties on clinical stage therapeutic candidates',
    stage: 'Validation',
    location: 'Boston, MA, USA',
    requiredSkills: 'Computational Biology, Protein Folding (ESMFold/AlphaFold), Molecular Dynamics, Cloud HPC',
    fundingStatus: 'Pre-Seed',
    fundingRequired: '$1,000,000 for wet-lab synthesis and in vitro validation assays',
    currentTraction: 'Synthesized 12 peptide candidates; 4 demonstrated complete in vitro inhibition against MRSA.',
    website: 'https://bioshield.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 43,
    viewsCount: 480,
    followersCount: 59,
    members: [],
  },
  {
    founderEmail: 'devansh.joshi@agridata.in',
    name: 'VoltSync Hub',
    logo: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'AI building automation and digital twin energy management for commercial high-rises.',
    problem: 'Commercial office towers waste 30% of their HVAC and lighting energy due to static building management schedules that ignore real-time occupancy and thermal dynamics.',
    solution: 'Plug-and-play IoT sensor mesh and reinforcement-learning HVAC control that continuously optimizes chiller setpoints based on weather forecasts, indoor air quality, and occupancy.',
    targetCustomers: 'Commercial real estate REITS, corporate campus facility directors, and hotel chains.',
    industry: 'B2B SaaS',
    businessModel: 'SaaS + Shared energy cost savings (typically 20-35% utility bill reduction)',
    stage: 'Early Revenue',
    location: 'Dubai, UAE',
    requiredSkills: 'BACnet / Modbus Protocols, Reinforcement Learning, Time-Series Modeling, IoT Hardware',
    fundingStatus: 'Seed',
    fundingRequired: '$1,200,000 for regional expansion across GCC and Southeast Asia',
    currentTraction: 'Deployed across 1.8M sq ft of Class-A commercial office space in Dubai and Abu Dhabi.',
    website: 'https://voltsync.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 39,
    viewsCount: 420,
    followersCount: 51,
    members: [],
  },
  {
    founderEmail: 'arjun.mehta@agritech.in',
    name: 'KrishiGyan AI',
    logo: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=200&auto=format&fit=crop&q=80',
    oneLineDescription: 'Multilingual vernacular voice assistant for crop disease diagnosis via phone camera scans.',
    problem: 'Farmers unable to read technical agronomic manuals fail to identify early fungal blights, resulting in irreversible crop destruction within 48 hours.',
    solution: 'Instant phone camera leaf scan providing immediate spoken voice diagnosis in 12 regional languages (Hindi, Telugu, Marathi, Tamil, Kannada) with organic remedy advice.',
    targetCustomers: 'Smallholder farming families and village agricultural extension agents.',
    industry: 'AgriTech',
    businessModel: 'Freemium consumer app + Sponsored recommendations from certified bio-fertilizer suppliers',
    stage: 'MVP',
    location: 'Ahmedabad, Gujarat, India',
    requiredSkills: 'Edge Computer Vision, Multilingual ASR/TTS, Flutter, Offline SQLite Sync',
    fundingStatus: 'Bootstrapped',
    fundingRequired: '$150,000 for expanding regional speech corpora and offline model compression',
    currentTraction: '28,000 registered farmers with over 110,000 crop disease diagnoses conducted.',
    website: 'https://krishigyan.demo.startupz.com',
    visibility: 'PUBLIC',
    isConfidential: false,
    isVerified: true,
    likesCount: 47,
    viewsCount: 530,
    followersCount: 66,
    members: [],
  },
];
