export const seedUsers = [
  // 1. PRIMARY ADMIN
  {
    email: 'admin@startupz.com',
    role: 'ADMIN',
    isAdmin: true,
    isVerified: true,
    verificationBadge: 'Platform Admin',
    profile: {
      fullName: 'Alex Vance',
      headline: 'StartupZ Ecosystem Lead | Community Architect',
      location: 'San Francisco, CA, USA',
      bio: 'Passionate about connecting early-stage founders with world-class builders, operators, and capital. Managing the StartupZ ecosystem and governance.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      education: 'Stanford University (BS CS), Harvard Business School (MBA)',
      skills: 'Ecosystem Building, Startup Strategy, Venture Capital, Product Architecture, Governance',
      startupInterests: 'AI, B2B SaaS, FinTech, DeepTech, ClimateTech',
      industries: 'Artificial Intelligence, B2B SaaS, FinTech',
      preferredRole: 'Platform Administrator / Advisor',
      availability: 'Full-time',
      startupExperience: 'Serial Founder',
      achievements: 'Scaled 2 enterprise SaaS companies from 0 to Series B. Built 10,000+ member founder communities.',
      openTo: 'Collaboration,Mentorship,Investment',
      profileCompletion: 100,
    },
  },

  // 2. PRIMARY DEMO FOUNDER
  {
    email: 'sarah.chen@aiagri.io',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Sarah Chen',
      headline: 'Founder @ AgroPulse | AgTech & AI Precision Systems | Looking for Technical Co-Founder',
      location: 'Austin, TX, USA',
      bio: 'Building AI systems to empower smallholder and commercial farmers with real-time agronomic insights. Previously senior product manager at an AgriTech unicorn.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      education: 'UC Berkeley (BS Agricultural Bioengineering)',
      skills: 'Product Management, AgTech, Go-To-Market, Customer Discovery, Fundraising, Precision Agriculture',
      startupInterests: 'AgTech, ClimateTech, AI, Sustainability, IoT',
      industries: 'AgriTech, Artificial Intelligence, ClimateTech',
      preferredRole: 'CEO / Business Co-Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Secured $100K state climate grant, partnered with 15 pilot farms across the Central Valley.',
      openTo: 'Co-Founder,Startup Team,Investment,Mentorship',
      profileCompletion: 95,
    },
  },

  // 3. PRIMARY DEMO DEVELOPER
  {
    email: 'marcus.dev@codeflow.dev',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Marcus Brody',
      headline: 'Staff Full-Stack Engineer | React + Node + Rust | Looking to join Early-Stage Team',
      location: 'Seattle, WA, USA',
      bio: '7+ years architecting scalable cloud services and developer tooling. Built systems processing 50M+ requests/day. Hungry to build zero-to-one ventures in AI and developer productivity.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      education: 'University of Washington (BS Computer Science)',
      skills: 'React, Node.js, TypeScript, Rust, PostgreSQL, GraphQL, Docker, AWS, System Architecture',
      startupInterests: 'Developer Tools, AI Infrastructure, Cloud, B2B SaaS',
      industries: 'Developer Tools, Artificial Intelligence, B2B SaaS',
      preferredRole: 'Technical Co-Founder / Founding CTO',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      achievements: 'Ex-Senior Engineer @ Datadog; created open-source CLI with 12K+ GitHub stars.',
      openTo: 'Co-Founder,Startup Team,Mentorship',
      profileCompletion: 90,
    },
  },

  // 4. PRIMARY DEMO DESIGNER
  {
    email: 'priya.design@pixelcraft.studio',
    role: 'DESIGNER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Priya Sharma',
      headline: 'Principal Product Designer & Design Systems Lead | Crafting B2B SaaS & Consumer Apps',
      location: 'Bengaluru, Karnataka, India',
      bio: 'Obsessed with micro-interactions, accessibility, and high-conversion UX. Led product design from seed to Series A at two fintech startups.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      education: 'National Institute of Design (B.Des Product Design)',
      skills: 'UI/UX Design, Figma, Design Systems, User Research, Prototyping, Wireframing, Webflow',
      startupInterests: 'FinTech, HealthTech, B2B SaaS, EdTech',
      industries: 'FinTech, Design Tools, HealthTech',
      preferredRole: 'Founding Designer / Head of Product Design',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      achievements: 'Redesigned core mobile checkout boosting conversion by 28%. Red Dot Design Award 2024.',
      openTo: 'Co-Founder,Startup Team,Mentorship',
      profileCompletion: 90,
    },
  },

  // 5. PRIMARY DEMO MARKETER
  {
    email: 'david.kim@growthscale.co',
    role: 'MARKETER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'David Kim',
      headline: 'Growth Marketing & GTM Lead | $0 to $1M ARR Playbooks | B2B Demand Gen & PLG',
      location: 'New York, NY, USA',
      bio: 'Data-driven growth operator specializing in product-led acquisition, SEO moats, cold outbound automation, and developer marketing.',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      education: 'Columbia University (BA Economics & Statistics)',
      skills: 'Growth Marketing, Performance Marketing, SEO, Content Strategy, B2B Sales, Product-Led Growth, Hubspot',
      startupInterests: 'B2B SaaS, Developer Tools, FinTech, E-Commerce',
      industries: 'B2B SaaS, Developer Tools, Marketing Tech',
      preferredRole: 'Head of Growth / Co-Founder (GTM)',
      availability: 'Full-time',
      startupExperience: 'Serial Founder',
      achievements: 'Scaled early-stage B2B SaaS pipeline to $2.4M ARR in 14 months via organic content and outbound.',
      openTo: 'Co-Founder,Startup Team,Mentorship',
      profileCompletion: 85,
    },
  },

  // 6. PRIMARY DEMO INVESTOR
  {
    email: 'elena.investor@apexventures.vc',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Elena Rostova',
      headline: 'Partner @ Apex Ventures (Demo VC) | Investing in Pre-Seed & Seed AI, SaaS & ClimateTech',
      location: 'London, UK',
      bio: 'Venture investor backing mission-driven founders rewriting global infrastructure. Ex-operator in cloud software with 10+ years investing experience.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'London School of Economics (MSc Finance), Oxford University (BA PPE)',
      skills: 'Venture Capital, Term Sheet Negotiation, Board Governance, Cap Table Structuring, Syndicate Syndication',
      startupInterests: 'AI, ClimateTech, B2B SaaS, CyberSecurity, AgriTech',
      industries: 'Artificial Intelligence, ClimateTech, B2B SaaS',
      preferredRole: 'Lead Seed Investor / Board Observer',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      achievements: 'Backed 18 seed-stage ventures; 3 exits to public tech acquirers.',
      openTo: 'Investment,Mentorship',
      profileCompletion: 95,
    },
  },

  // 7. PRIMARY DEMO MENTOR
  {
    email: 'alex.chen@scaleup.vc',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Alex Vance Chen',
      headline: 'Operating Partner & Executive Coach | Scaling B2B Startups from Seed to Series B',
      location: 'San Francisco, CA, USA',
      bio: 'Mentored over 40 founder teams across Y Combinator, Techstars, and StartupZ. Specialized in enterprise customer discovery, pricing strategy, and leadership team hiring.',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
      education: 'MIT (BS Electrical Engineering & CS), INSEAD (MBA)',
      skills: 'Product Strategy, Enterprise Sales, Executive Coaching, Go-to-Market, Fundraising Pitch Prep',
      startupInterests: 'Enterprise SaaS, Developer Tools, DeepTech, AI',
      industries: 'B2B SaaS, Developer Tools, DeepTech',
      preferredRole: 'Strategic Advisor / Mentor',
      availability: 'Advisory',
      startupExperience: 'Serial Founder',
      achievements: 'Built and sold SaaS venture to Salesforce; advised 5 unicorn leadership teams.',
      openTo: 'Mentorship,Collaboration',
      profileCompletion: 95,
    },
  },

  // FOUNDERS (India, USA, Europe, Asia, Africa)
  {
    email: 'arjun.mehta@agritech.in',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Arjun Mehta',
      headline: 'Co-Founder & CEO @ KrishiGyan | Building Decentralized Micro-Cold Storage for Smallholders',
      location: 'Hyderabad, Telangana, India',
      bio: 'Pioneering solar-powered village cold storage lockers to slash post-harvest tomato and chili spoilage across rural Telangana and Andhra Pradesh.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      education: 'IIT Hyderabad (BTech Mechanical Engineering)',
      skills: 'Clean Energy, Cold Chain, AgriTech, Hardware Prototyping, Rural Distribution, Operations',
      startupInterests: 'AgriTech, ClimateTech, Renewable Energy, Rural Development',
      industries: 'AgriTech, Energy & CleanTech, Supply Chain & Logistics',
      preferredRole: 'CEO / Operations Co-Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Deployed 8 pilot cold storage units preserving 40 tons of produce with zero grid dependency.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'ananya.rao@medivault.health',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Ananya Rao',
      headline: 'Founder @ MediVault | Zero-Knowledge Electronic Health Records for Ayushman Bharat Ecosystem',
      location: 'Hyderabad, Telangana, India',
      bio: 'Former healthcare consulting manager at McKinsey. Building patient-controlled, cryptographically secured clinical health records for tiered hospitals and clinics.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      education: 'BITS Pilani (B.Pharm), ISB Hyderabad (MBA)',
      skills: 'Health Informatics, Cryptography, ABHA APIs, Regulatory Compliance, Product Strategy, Hospital GTM',
      startupInterests: 'HealthTech, FinTech, Data Privacy, Digital Public Goods',
      industries: 'HealthTech, Technology & Innovation',
      preferredRole: 'CEO / Business Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Integrated with 14 multi-specialty hospitals; onboarded 45,000 verified patients.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 95,
    },
  },
  {
    email: 'rohan.kapoor@finsync.io',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Rohan Kapoor',
      headline: 'Founder @ FinSync | Real-Time Cash Flow Factoring & Working Capital Rails for MSMEs',
      location: 'Mumbai, Maharashtra, India',
      bio: 'Ex-Goldman Sachs credit analyst solving the $300B informal MSME credit gap in India through automated GST invoice factoring and escrow settlements.',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
      education: 'St. Xavier\'s College Mumbai (B.Com), Chartered Accountant (ICAI)',
      skills: 'Fintech, Credit Risk Modeling, Underwriting, GSTN APIs, Banking Partnerships, Treasury Management',
      startupInterests: 'FinTech, B2B SaaS, MSME Lending, Embedded Finance',
      industries: 'FinTech, Business & Commerce, Economy & Inequality',
      preferredRole: 'CEO / Finance Co-Founder',
      availability: 'Full-time',
      startupExperience: 'Second-time Founder',
      achievements: 'Disbursed INR 12 Crore in working capital with less than 0.8% default rate.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 95,
    },
  },
  {
    email: 'sofia.martinez@hydrosense.ai',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Sofia Martinez',
      headline: 'Founder @ HydroSense | Satellite & IoT Leak Detection for Municipal Water Infrastructure',
      location: 'Barcelona, Spain',
      bio: 'Civil engineer turned climate tech founder. Preventing potable water wastage in drought-affected Mediterranean municipalities using smart acoustic sensors and radar imagery.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'Polytechnic University of Catalonia (MSc Hydraulic Engineering)',
      skills: 'Water Infrastructure, IoT Telemetry, Satellite Radar, Municipal Procurement, Climate Adaptation',
      startupInterests: 'ClimateTech, Clean Water, Smart Cities, IoT',
      industries: 'Environment/Climate, Food & Water, Energy & Infrastructure',
      preferredRole: 'CEO / Technical Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Detected over 200 underground pipeline leaks saving 1.2M cubic meters of water in 2025.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'ethan.brooks@voltmesh.energy',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Ethan Brooks',
      headline: 'Founder @ VoltMesh | Peer-to-Peer Virtual Power Plants & Microgrid Energy Trading',
      location: 'Berlin, Germany',
      bio: 'Electrical systems engineer passionate about grid resilience. Connecting residential solar and battery storage into virtual power plants to balance renewable grid volatility.',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
      education: 'Technical University of Berlin (MSc Power Systems)',
      skills: 'Smart Grid, DERMS, Battery Storage, Energy Trading, B2B SaaS, IoT',
      startupInterests: 'Clean Energy, Smart Grids, ClimateTech, Virtual Power Plants',
      industries: 'Energy & Infrastructure, Environment/Climate',
      preferredRole: 'Founder & Head of Systems',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      achievements: 'Orchestrated 4.5 MW of distributed battery capacity for frequency stabilization pilot.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 85,
    },
  },
  {
    email: 'aisha.rahman@edugenie.org',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Aisha Rahman',
      headline: 'Founder @ EduGenie | Offline-First Multilingual AI Tutoring for Rural Classrooms',
      location: 'Nairobi, Kenya',
      bio: 'Educator and software builder democratizing foundational literacy and math across East Africa using edge-running AI on ultra-low-cost solar tablets.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      education: 'University of Nairobi (B.Ed), Stanford GSE Fellow',
      skills: 'EdTech, Pedagogy, Offline-First Software, Localized AI, African Markets, Grant Funding',
      startupInterests: 'EdTech, Social Impact, Digital Divide, Multilingual AI',
      industries: 'Education & Skills, Technology & Innovation',
      preferredRole: 'CEO / Education Lead',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Used by 25,000 students in 80 rural schools across Kenya and Uganda with 42% literacy gains.',
      openTo: 'Co-Founder,Startup Team,Investment,Mentorship',
      profileCompletion: 90,
    },
  },
  {
    email: 'daniel.carter@tracecraft.supply',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Daniel Carter',
      headline: 'Founder @ TraceCraft | Scope 3 Supply Chain Carbon Accounting & Auditing Engine',
      location: 'London, UK',
      bio: 'Pioneering verified primary supplier carbon telemetry to help mid-market manufacturing and retail companies comply with EU CSRD without manual spreadsheets.',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
      education: 'Cambridge University (MPhil Sustainable Development)',
      skills: 'Carbon Accounting, Scope 3 Telemetry, ESG Disclosure, Supply Chain Auditing, B2B SaaS',
      startupInterests: 'ClimateTech, Supply Chain, ESG Compliance, Enterprise SaaS',
      industries: 'Business & Commerce, Environment/Climate, Supply Chain & Logistics',
      preferredRole: 'CEO / Product Strategy',
      availability: 'Full-time',
      startupExperience: 'Second-time Founder',
      achievements: 'Signed 12 European tier-1 manufacturing suppliers; integrated with SAP & NetSuite.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'kavya.nair@talentloom.ai',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Kavya Nair',
      headline: 'Founder @ TalentLoom | Automated Compliance & Global Contractor Payroll for Tech Startups',
      location: 'Bengaluru, Karnataka, India',
      bio: 'Simplifying cross-border contractor classification, statutory benefits, and multi-currency payroll for fast-growing startups hiring global talent.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      education: 'NLSIU Bengaluru (BA LLB Hons)',
      skills: 'LegalTech, Cross-Border Labor Law, Global Payroll, Tax Compliance, B2B SaaS, FinTech',
      startupInterests: 'Future of Work, HR Tech, FinTech, LegalTech',
      industries: 'Business & Commerce, Governance & Peace',
      preferredRole: 'CEO / Legal Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Processed $4.5M in global contractor payouts across 18 countries with 100% compliance record.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 95,
    },
  },
  {
    email: 'tariq.mansoor@cybermesh.io',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Tariq Al-Mansoor',
      headline: 'Founder @ CyberMesh | Autonomous Zero-Trust Identity Defense for Mid-Market Enterprises',
      location: 'Dubai, UAE',
      bio: 'Former cybersecurity lead at Emirates Group. Defending enterprise networks from polymorphic ransomware and synthetic identity attacks using autonomous agentic security mesh.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      education: 'Khalifa University (BS Computer Engineering), Carnegie Mellon (MS Cyber Security)',
      skills: 'Cybersecurity, Zero-Trust, Ransomware Remediation, Identity Security, Cloud Security, SIEM',
      startupInterests: 'Cybersecurity, Enterprise SaaS, AI Defense, DeepTech',
      industries: 'Technology & Innovation, Business & Commerce',
      preferredRole: 'Founder & Chief Security Architect',
      availability: 'Full-time',
      startupExperience: 'Second-time Founder',
      achievements: 'Secured 30 mid-market enterprises; thwarted over 1,400 credential stuffing attempts.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'chen.wei@optilog.tech',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Chen Wei',
      headline: 'Founder @ OptiLog | Multi-Modal Maritime Freight & Port Container Triangulation',
      location: 'Singapore',
      bio: 'Optimizing container logistics and eliminating empty backhauls across Southeast Asian ports using predictive arrival scheduling and digital freight matching.',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      education: 'National University of Singapore (B.Eng Industrial & Systems Engineering)',
      skills: 'Maritime Logistics, Freight Optimization, Port Operations, Algorithmic Routing, B2B Marketplace',
      startupInterests: 'Logistics, Supply Chain, Ocean Freight, B2B SaaS',
      industries: 'Supply Chain & Logistics, Business & Commerce',
      preferredRole: 'CEO / Operations Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Reduced empty container dwell time by 34% across 5 port terminals in Singapore & Malaysia.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 85,
    },
  },
  {
    email: 'amara.okafor@femisave.africa',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Amara Okafor',
      headline: 'Founder @ FemiSave | Collateral-Free Micro-Credit & Digital Savings for Women Entrepreneurs',
      location: 'Lagos, Nigeria',
      bio: 'Empowering informal female market traders across West Africa with rotating digital savings circles (Esusu/Ajo) and automated working capital micro-loans.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      education: 'University of Lagos (BSc Banking & Finance)',
      skills: 'Financial Inclusion, Micro-Credit, Mobile Money, USSD Technology, Women Empowerment, FinTech',
      startupInterests: 'FinTech, Women Empowerment, Financial Inclusion, Micro-Credit',
      industries: 'Women & Social, Economy & Inequality, FinTech',
      preferredRole: 'CEO / Social Impact Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Empowered 12,000 women micro-merchants with $1.8M in rotating credit; 98.4% repayment rate.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'lucas.meyer@mindhaven.care',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Lucas Meyer',
      headline: 'Founder @ MindHaven | Evidence-Based Digital Behavioral Coaching & Anonymous Peer Support',
      location: 'Amsterdam, Netherlands',
      bio: 'Clinical psychologist building culturally adaptable digital therapeutics and empathetic AI check-ins to make mental health support accessible to university students and young professionals.',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
      education: 'University of Amsterdam (MSc Clinical Psychology)',
      skills: 'Digital Therapeutics, Behavioral Health, CBT Frameworks, Product Management, Healthcare Compliance',
      startupInterests: 'Mental Health, Digital Health, AI Therapy, Healthcare Access',
      industries: 'Health & Disease, Women & Social',
      preferredRole: 'CEO / Clinical Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Published clinical study showing 35% reduction in moderate depression symptoms after 6 weeks.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'rohit.verma@finops.ai',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Rohit Verma',
      headline: 'Lead Cloud Architect & FinOps Specialist | Kubernetes, AWS & GPU Virtualization',
      location: 'Pune, Maharashtra, India',
      bio: 'Helping high-growth AI startups cut cloud compute bills by 40% through spot instance automation and dynamic vGPU allocation.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      education: 'Pune Institute of Computer Technology (BE Computer Engineering)',
      skills: 'Kubernetes, AWS, Terraform, FinOps, Go, Python, GPU Virtualization, CI/CD',
      startupInterests: 'Cloud Infrastructure, FinOps, AI Infrastructure, DevOps',
      industries: 'Business & Commerce, Technology & Innovation',
      preferredRole: 'Founding Infrastructure Engineer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      achievements: 'Saved $600K/year in AWS infrastructure bills for high-scale fintech client.',
      openTo: 'Co-Founder,Startup Team',
      profileCompletion: 80,
    },
  },
  {
    email: 'samantha.hayes@biomaterials.io',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Samantha Hayes',
      headline: 'Founder @ BioShield | Edible Plant-Based Coatings to Double Fruit & Vegetable Shelf-Life',
      location: 'San Francisco, CA, USA',
      bio: 'Biochemist developing organic, invisible, and odorless plant-lipid coatings that cut post-harvest produce respiration, preventing supermarket food waste.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      education: 'Stanford University (PhD Bio-organic Chemistry)',
      skills: 'Biotechnology, Food Science, IP Patents, FDA Regulatory Filing, Agriculture Supply Chains',
      startupInterests: 'AgriTech, Food Waste, Circular Economy, BioTech',
      industries: 'Food & Water, Environment/Climate, Agriculture & Farming',
      preferredRole: 'CEO / Chief Scientist',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Granted 2 provisional patents; extended avocado and berry shelf-life by 14 days in trials.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 95,
    },
  },
  {
    email: 'gabriel.santos@agrisat.io',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Gabriel Santos',
      headline: 'Computer Vision & Geospatial ML Engineer | PyTorch, Sentinel-2 & Edge-AI',
      location: 'São Paulo, Brazil',
      bio: 'Building deep learning models on multispectral satellite imagery to detect crop moisture deficits and pest outbreaks at 3-meter resolution.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      education: 'University of São Paulo (MSc Artificial Intelligence)',
      skills: 'Computer Vision, PyTorch, Satellite Remote Sensing, NDVI, Python, OpenCV, GIS',
      startupInterests: 'AgriTech, Climate Intelligence, AI, Satellite Tech',
      industries: 'Agriculture & Farming, Technology & Innovation',
      preferredRole: 'Founding ML Engineer / Co-Founder',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      achievements: 'Created weed classification model with 94.6% accuracy on edge-embedded cameras.',
      openTo: 'Co-Founder,Startup Team',
      profileCompletion: 85,
    },
  },
  {
    email: 'aisha.bello@reverseloop.co',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Aisha Bello',
      headline: 'Founder @ ReverseLoop | AI-Powered Retail Return Consolidation & Circular Liquidation',
      location: 'London, UK',
      bio: 'Transforming the $800B retail return headache into circular revenue through automated diagnostic return hubs, dynamic re-commerce, and refurbishment routing.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      education: 'Imperial College London (MSc Logistics & Supply Chain Management)',
      skills: 'Reverse Logistics, Circular Economy, E-Commerce, Retail Operations, Warehouse Automation',
      startupInterests: 'E-Commerce, Circular Economy, Retail Tech, Logistics',
      industries: 'Business & Commerce, Environment/Climate, Supply Chain & Logistics',
      preferredRole: 'CEO / Operations Lead',
      availability: 'Full-time',
      startupExperience: 'Second-time Founder',
      achievements: 'Diverted 800,000 returned apparel items from landfills; recovered 68% retail value.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'vikram.malhotra@zenithai.dev',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Vikram Malhotra',
      headline: 'Founder @ ZenithAI | Autonomous Multi-Agent Workflows for Enterprise Document Processing',
      location: 'Hyderabad, Telangana, India',
      bio: 'Enabling Fortune 500 banks and insurers to automate multi-lingual mortgage and insurance claims processing using specialized LLM agents and human-in-the-loop verification.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      education: 'IIT Madras (BTech CS), Carnegie Mellon (MS AI)',
      skills: 'LLM Agents, Document AI, LangChain, Python, Enterprise Security, B2B SaaS Sales',
      startupInterests: 'Enterprise AI, FinTech, LegalTech, Automation',
      industries: 'Technology & Innovation, Business & Commerce',
      preferredRole: 'CEO / Technical Founder',
      availability: 'Full-time',
      startupExperience: 'Serial Founder',
      achievements: 'Processed over 2.5 million financial documents with 99.4% precision; $850K ARR.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 95,
    },
  },
  {
    email: 'chloe.dubois@trialmatch.bio',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Chloe Dubois',
      headline: 'Founder @ TrialMatch | Precision Clinical Trial Patient Cohort Matching via EHR Integration',
      location: 'Paris, France',
      bio: 'Solving the #1 bottleneck in pharmaceutical drug development by matching oncological and rare disease patients with life-saving clinical trials in minutes.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'Sorbonne University (MD, MSc Bioinformatics)',
      skills: 'Clinical Trials, Oncology, EHR Interoperability, BioTech, Regulatory Affairs, Medical Data',
      startupInterests: 'HealthTech, BioTech, Clinical Trials, AI Medicine',
      industries: 'Health & Disease, Business & Commerce, Technology & Innovation',
      preferredRole: 'CEO / Medical Director',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Partnered with 24 European oncology centers; shortened trial recruitment by 4.2 months.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'kenji.sato@gridlogic.jp',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Kenji Sato',
      headline: 'Founder @ GridLogic | AI-Powered Predictive Battery Energy Storage Optimization',
      location: 'Tokyo, Japan',
      bio: 'Building machine learning dispatch optimization software for commercial battery energy storage systems (BESS) participating in day-ahead wholesale electricity markets.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      education: 'University of Tokyo (PhD Electrical Engineering)',
      skills: 'Battery Storage, Energy Markets, Time-Series Forecasting, Reinforcement Learning, Industrial IoT',
      startupInterests: 'Clean Energy, Battery Storage, Energy Trading, ClimateTech',
      industries: 'Energy & Infrastructure, Environment/Climate, Technology & Innovation',
      preferredRole: 'CEO / Energy Systems Architect',
      availability: 'Full-time',
      startupExperience: 'Second-time Founder',
      achievements: 'Optimizing 120 MWh of battery assets in Japan and Australia; +22% higher revenue yield.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'tunde.adeleke@remitrail.africa',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Tunde Adeleke',
      headline: 'Managing Director @ Sahara Horizon Ventures (Demo VC) | Pan-African Fintech & Climate Seed Fund',
      location: 'Lagos, Nigeria',
      bio: 'Investing $50K–$300K initial checks into visionary African founders building scalable digital financial infrastructure, logistics, and climate resilience.',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
      education: 'Howard University (BS Finance), Wharton (MBA)',
      skills: 'Venture Capital, Africa GTM, Financial Regulations, Angel Syndicates, Growth Advisory',
      startupInterests: 'FinTech, AgriTech, Logistics, Renewable Energy',
      industries: 'Economy & Inequality, Business & Commerce, Food & Water',
      preferredRole: 'Seed Investor / Lead Syndicate',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      achievements: 'Backed 22 startups across Nigeria, Kenya, Egypt, and Ghana.',
      openTo: 'Investment,Mentorship',
      profileCompletion: 90,
    },
  },
  {
    email: 'radhika.swami@mentorship.org',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Dr. Radhika Swaminathan',
      headline: 'Former VP of Engineering @ Swiggy & Flipkart | Technical Strategy & Team Scaling Mentor',
      location: 'Bengaluru, Karnataka, India',
      bio: 'Passionate about helping early-stage engineering leaders avoid architectural debt, design fault-tolerant microservices, and build high-performance engineering cultures.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      education: 'IISc Bangalore (PhD Distributed Systems)',
      skills: 'Distributed Systems, Engineering Leadership, Microservices, Cloud Architecture, Hiring & Retention',
      startupInterests: 'B2B SaaS, Developer Tools, AI, High-Scale Consumer Platforms',
      industries: 'Technology & Innovation, Developer Tools, B2B SaaS',
      preferredRole: 'Technical Advisor / Mentor',
      availability: 'Advisory',
      startupExperience: 'Serial Founder',
      achievements: 'Scaled engineering teams from 10 to 450+ engineers; author of 2 cloud systems patents.',
      openTo: 'Mentorship,Collaboration',
      profileCompletion: 95,
    },
  },
  {
    email: 'kavita.goel@angelnetwork.in',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Kavita Goel',
      headline: 'Angel Investor @ Mumbai Angels (Demo) | Backing B2B SaaS, HealthTech & Women-Led Startups',
      location: 'Mumbai, Maharashtra, India',
      bio: 'Ex-McKinsey Partner & Active Angel Investor. Writing $25K to $100K checks into passionate early-stage founders with strong unit economics and clear distribution advantage.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      education: 'IIM Ahmedabad (MBA), Lady Shri Ram College (BA Economics)',
      skills: 'Angel Investing, Due Diligence, Financial Modeling, Governance, GTM Strategy',
      startupInterests: 'Women Founders, HealthTech, B2B SaaS, D2C Tech',
      industries: 'Women & Social, Business & Commerce, Health & Disease',
      preferredRole: 'Angel Investor',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      achievements: 'Portfolio of 16 seed investments; 2 acquisitions by Indian tech conglomerates.',
      openTo: 'Investment,Mentorship',
      profileCompletion: 90,
    },
  },
  {
    email: 'sanjay.mentor@fintechpulse.in',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Sanjay Singhania',
      headline: 'Senior Partner @ FinTech Pulse Advisory | Former Chief Risk Officer | Banking & RBI Regulations',
      location: 'Mumbai, Maharashtra, India',
      bio: '30+ years in commercial banking, credit underwriting, and fintech regulatory compliance. Advising startups on NBFC partnerships, digital lending guidelines, and risk governance.',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
      education: 'Delhi School of Economics (MA Economics)',
      skills: 'Fintech Regulation, RBI Guidelines, NBFC Structuring, Credit Underwriting, Risk Management',
      startupInterests: 'FinTech, MSME Lending, Neo-Banking, InsurTech',
      industries: 'FinTech, Business & Commerce, Economy & Inequality',
      preferredRole: 'Regulatory & Risk Advisor',
      availability: 'Advisory',
      startupExperience: 'Serial Founder',
      achievements: 'Guided 8 fintech startups through successful RBI licensing and digital lending regulatory audits.',
      openTo: 'Mentorship,Collaboration',
      profileCompletion: 90,
    },
  },
  {
    email: 'simon.vanderbilt@bluelight.vc',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Simon Van Der Bilt',
      headline: 'Partner @ BlueShift Horizon Capital (Demo VC) | European ClimateTech & Energy Transition Seed Fund',
      location: 'Amsterdam, Netherlands',
      bio: 'Investing €250K–€1M in pioneering European and global climate ventures solving grid flexibility, industrial heat decarbonization, and bio-circularity.',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80',
      education: 'Delft University of Technology (MSc Sustainable Energy), INSEAD (MBA)',
      skills: 'Clean Energy Investing, Climate Tech, Project Finance, Circular Economy, Carbon Markets',
      startupInterests: 'ClimateTech, Clean Energy, Circular Economy, Agritech',
      industries: 'Environment/Climate, Energy & Infrastructure, Food & Water',
      preferredRole: 'Lead Seed Investor',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      achievements: 'Deployed €40M across 28 European climate startups.',
      openTo: 'Investment,Mentorship',
      profileCompletion: 90,
    },
  },
  {
    email: 'evelyn.reed@biomentor.org',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Dr. Evelyn Reed',
      headline: 'Former Head of R&D @ Novartis Oncology | Life Sciences Commercialization & Clinical Strategy',
      location: 'Boston, MA, USA',
      bio: 'Mentoring biotech and healthtech founders navigating pre-clinical translational research, FDA IND filings, and biopharma licensing partnerships.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'Harvard Medical School (MD), MIT (PhD Molecular Biology)',
      skills: 'Clinical Development, FDA Filings, BioTech Licensing, Pharma Partnerships, Translational Medicine',
      startupInterests: 'HealthTech, BioTech, Precision Oncology, Digital Therapeutics',
      industries: 'Health & Disease, Technology & Innovation',
      preferredRole: 'Scientific Advisory Board Member',
      availability: 'Advisory',
      startupExperience: 'Serial Founder',
      achievements: 'Co-inventor of 2 FDA-approved targeted cancer therapies.',
      openTo: 'Mentorship,Collaboration',
      profileCompletion: 95,
    },
  },
  {
    email: 'marcus.thorne@deeptech.vc',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Marcus Thorne',
      headline: 'General Partner @ DeepTech Horizon Syndicate (Demo Fund) | AI, SpaceTech & Robotics Seed Checks',
      location: 'New York, NY, USA',
      bio: 'Writing $100K–$500K checks into technical founders building foundational models, spatial computing hardware, and autonomous robotics.',
      avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
      education: 'Cornell University (BS Computer Science & Physics)',
      skills: 'DeepTech, Seed Investing, Syndicate Management, Hardware Tech, AI Acceleration',
      startupInterests: 'AI, Robotics, SpaceTech, Quantum, Developer Infrastructure',
      industries: 'Technology & Innovation, Other (Future Tech)',
      preferredRole: 'Lead Seed Investor',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      achievements: 'Invested in 30+ deeptech companies with 4 unicorn valuations.',
      openTo: 'Investment,Mentorship',
      profileCompletion: 90,
    },
  },
  {
    email: 'sneha.kulkarni@safewater.org',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Sneha Kulkarni',
      headline: 'Founder @ AquaPure | Low-Cost Graphene-Oxide Water Nanofiltration for Fluoride-Hit Villages',
      location: 'Pune, Maharashtra, India',
      bio: 'Developing gravity-powered, chemical-free nanofiltration membranes that remove excess arsenic and fluoride from rural borewell drinking water without electricity.',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop&q=80',
      education: 'COEP Pune (B.Tech Chemical Engineering), IIT Bombay (M.Tech Nanotechnology)',
      skills: 'Water Purification, Nanotechnology, Membrane Filtration, Rural Health, Social Enterprise',
      startupInterests: 'Clean Water, Rural Health, ClimateTech, Social Impact',
      industries: 'Food & Water, Health & Disease, Environment/Climate',
      preferredRole: 'CEO / Chief Scientist',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Providing clean drinking water to 42 villages across Maharashtra and Rajasthan; awarded Jal Shakti Prize.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'haruto.tanaka@robotics.jp',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Haruto Tanaka',
      headline: 'Robotics & Embedded Firmware Lead | ROS2, C++, Precision Agricultural Automation',
      location: 'Tokyo, Japan',
      bio: 'Designing autonomous weeding and harvesting micro-rovers for vertical farms and open orchards with sub-centimeter RTK-GPS precision.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      education: 'Tokyo Institute of Technology (MSc Robotics)',
      skills: 'ROS2, C++, Embedded Systems, RTK-GPS, Sensor Fusion, Autonomous Navigation, Hardware Prototyping',
      startupInterests: 'AgriTech, Robotics, Automation, Smart Hardware',
      industries: 'Agriculture & Farming, Technology & Innovation',
      preferredRole: 'Co-Founder / Hardware Lead',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      achievements: 'Built autonomous micro-robot with 99.2% mechanical reliability in field tests.',
      openTo: 'Co-Founder,Startup Team',
      profileCompletion: 85,
    },
  },
  {
    email: 'pooja.singhania@greenpack.in',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Pooja Singhania',
      headline: 'Founder @ EcoWrap | Biodegradable Agricultural Waste Packaging Replacing Single-Use Plastics',
      location: 'Delhi, India',
      bio: 'Transforming rice stubble (parali) that is normally burned into molded packaging cushions for e-commerce, tackling North Indian air smog and plastic pollution simultaneously.',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      education: 'Delhi Technological University (BTech Environmental Engineering)',
      skills: 'Biomaterials, Packaging Tech, Clean Air, Supply Chain, Circular Economy, Carbon Credits',
      startupInterests: 'ClimateTech, Circular Economy, Clean Air, Agri-Waste',
      industries: 'Environment/Climate, Business & Commerce, Agriculture & Farming',
      preferredRole: 'CEO / Sustainable Operations Lead',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Processed 500 tons of stubble biomass, preventing 750 tons of CO2 equivalent smog emissions.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'arthur.pendelton@gtm.org',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Arthur Pendelton',
      headline: 'Former VP of Worldwide Sales @ Twilio & Box | Enterprise SaaS Go-To-Market Mentor',
      location: 'New York, NY, USA',
      bio: 'Advising early-stage B2B founders on enterprise sales compensation plans, customer qualification frameworks (MEDDIC), and closing six-figure pilots.',
      avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80',
      education: 'University of Pennsylvania (Wharton BS Economics)',
      skills: 'Enterprise Sales, B2B Go-To-Market, Sales Pipeline, MEDDIC Framework, Outbound Execution',
      startupInterests: 'B2B SaaS, Developer Tools, Enterprise AI, CyberSecurity',
      industries: 'Business & Commerce, Technology & Innovation',
      preferredRole: 'Sales & GTM Advisor',
      availability: 'Advisory',
      startupExperience: 'Serial Founder',
      achievements: 'Closed $80M+ in cumulative enterprise software contracts; mentored 15 Techstars cohorts.',
      openTo: 'Mentorship,Collaboration',
      profileCompletion: 90,
    },
  },
  {
    email: 'astrid.lindholm@nordiccapital.se',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Astrid Lindholm',
      headline: 'Investment Director @ Nordic CleanTech Ventures (Demo Fund) | Backing Circular Economy & Bio-Materials',
      location: 'Stockholm, Sweden',
      bio: 'Writing €100K–€500K checks into Nordic and European early-stage teams transforming industrial by-products into high-value green alternatives.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'Stockholm School of Economics (MSc Finance)',
      skills: 'Seed Venture Capital, Circular Bio-economy, Environmental Life-Cycle Assessment, Term Sheets',
      startupInterests: 'Circular Economy, Biomaterials, CleanTech, FoodTech',
      industries: 'Environment/Climate, Food & Water, Business & Commerce',
      preferredRole: 'Lead Seed Investor',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      achievements: 'Recognized in Forbes 30 Under 30 Finance Europe 2024.',
      openTo: 'Investment,Mentorship',
      profileCompletion: 90,
    },
  },
  {
    email: 'devansh.joshi@agridata.in',
    role: 'DEVELOPER',
    isVerified: true,
    verificationBadge: 'Verified Member',
    profile: {
      fullName: 'Devansh Joshi',
      headline: 'Full-Stack Mobile Engineer | Flutter, React Native, Offline-First Mobile Architectures',
      location: 'Ahmedabad, Gujarat, India',
      bio: 'Building blazing-fast multilingual mobile apps with SQLite sync engines for low-bandwidth rural field workers and smallholder farmers.',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
      education: 'Nirma University (BTech Information Technology)',
      skills: 'Flutter, React Native, Dart, TypeScript, SQLite, Offline Sync, Firebase, UI/UX Implementation',
      startupInterests: 'AgriTech, EdTech, Mobile Apps, Offline-First Tech',
      industries: 'Technology & Innovation, Agriculture & Farming',
      preferredRole: 'Lead Mobile Engineer',
      availability: 'Full-time',
      startupExperience: 'Early Employee',
      achievements: 'Shipped 3 apps on Google Play with 100K+ downloads and 4.7-star rating.',
      openTo: 'Co-Founder,Startup Team',
      profileCompletion: 80,
    },
  },
  {
    email: 'fatima.zahra@solarirrigation.ma',
    role: 'FOUNDER',
    isVerified: true,
    verificationBadge: 'Verified Founder',
    profile: {
      fullName: 'Fatima Zahra',
      headline: 'Founder @ SaharaFlow | Pay-As-You-Go Solar Drip Irrigation for Arid Oasis Agriculture',
      location: 'Casablanca, Morocco',
      bio: 'Empowering date palm and olive growers in North Africa with smart solar-powered IoT drip irrigation units funded through harvest-linked micro-payments.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      education: 'Hassania School of Public Works (Diplôme d\'Ingénieur d\'État)',
      skills: 'Solar PV, Drip Irrigation, IoT Automation, PAYG Financing, Agronomy, Francophone Africa GTM',
      startupInterests: 'AgriTech, Renewable Energy, Water Scarcity, Financial Inclusion',
      industries: 'Agriculture & Farming, Energy & Infrastructure, Food & Water',
      preferredRole: 'CEO / Managing Founder',
      availability: 'Full-time',
      startupExperience: 'First-time Founder',
      achievements: 'Saved 45% water across 120 pilot farms in Southern Morocco; featured in COP28 Pavilion.',
      openTo: 'Co-Founder,Startup Team,Investment',
      profileCompletion: 90,
    },
  },
  {
    email: 'kenji.takahashi@seedangels.jp',
    role: 'MENTOR',
    isVerified: true,
    verificationBadge: 'Verified Mentor',
    profile: {
      fullName: 'Kenji Takahashi',
      headline: 'Founder & CEO Emeritus @ SoftRobo | Hardware Commercialization & Supply Chain Mentor',
      location: 'Tokyo, Japan',
      bio: 'Guided over 25 hardware and IoT startups from rapid prototyping in Shenzhen and Tokyo to high-volume manufacturing and international CE/FCC certification.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      education: 'Kyoto University (BS Precision Engineering)',
      skills: 'Hardware Prototyping, DFM (Design for Manufacturing), Shenzhen Supply Chain, Industrial IoT',
      startupInterests: 'Robotics, Hardware, Industrial IoT, Automation',
      industries: 'Technology & Innovation, Other (Future Tech)',
      preferredRole: 'Hardware & Manufacturing Advisor',
      availability: 'Advisory',
      startupExperience: 'Serial Founder',
      achievements: 'Shipped 1.5M units of precision consumer and commercial robotics hardware.',
      openTo: 'Mentorship,Collaboration',
      profileCompletion: 90,
    },
  },
  {
    email: 'courtney.vance@angelpulse.com',
    role: 'INVESTOR',
    isVerified: true,
    verificationBadge: 'Verified Investor',
    profile: {
      fullName: 'Courtney Vance',
      headline: 'Managing Partner @ Aura Angels Syndicate (Demo) | B2B SaaS & Developer Infrastructure',
      location: 'San Francisco, CA, USA',
      bio: 'Leading angel syndicate of 120+ senior tech executives writing $50K–$250K checks into developer tools, AI infrastructure, and open-source commercialization.',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
      education: 'Stanford University (BS Symbolic Systems)',
      skills: 'Syndicate Lead, Angel Investing, DevTools, SaaS Metrics, Cap Table Architecture',
      startupInterests: 'Developer Tools, AI Infrastructure, Cloud, Open Source',
      industries: 'Technology & Innovation, Business & Commerce',
      preferredRole: 'Angel Syndicate Lead',
      availability: 'Advisory',
      startupExperience: 'Angel Investor',
      achievements: 'Syndicated $4.2M into 22 developer infrastructure startups.',
      openTo: 'Investment,Mentorship',
      profileCompletion: 90,
    },
  },
];
